### ISSUE TITLE
unable to handle page fault for address

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#100]
Invoked `dd bs=1G count=64 if=/dev/zero of=./some_random_file` and got
<details><summary>this</summary><code><pre>
Apr 27 15:29:27 bismuth kernel: BUG: unable to handle page fault for address: ffff9af83a8f7000
Apr 27 15:29:28 bismuth kernel: #PF: supervisor write access in kernel mode
Apr 27 15:29:28 bismuth kernel: #PF: error_code(0x0003) - permissions violation
Apr 27 15:29:28 bismuth kernel: PGD 2e5201067 P4D 2e5201067 PUD 7bef17063 PMD 7c3f9f063 PTE 80000007ba8f7061
Apr 27 15:29:28 bismuth kernel: Oops: 0003 [#1] SMP PTI
Apr 27 15:29:28 bismuth kernel: CPU: 3 PID: 21221 Comm: kworker/u8:3 Tainted: G        W         5.3.0 #1-NixOS
Apr 27 15:29:28 bismuth kernel: Hardware name: Dell Inc. Latitude E5470/0C8FKJ, BIOS 1.19.3 08/20/2018
Apr 27 15:29:28 bismuth kernel: Workqueue: events_unbound __bch2_read_endio [bcachefs]
Apr 27 15:29:28 bismuth kernel: RIP: 0010:ZSTD_decompressSequences+0xbd2/0xce0 [zstd_decompress]
Apr 27 15:29:28 bismuth kernel: Code: 83 e1 3f e9 ba f6 ff ff 4d 89 c1 49 29 c1 49 83 f9 08 0f 8e 94 00 00 00 48 89 f2 4a 8d 3c 08 4c 8b 12 48 83 c0 08 48 83 c2 08 <4c> 89 50 f8 48 39 f8 72 ec 4c 01 ce 4c 89 c0 e9 4b fc ff ff 48 8b
Apr 27 15:29:28 bismuth kernel: RSP: 0000:ffffbea25b123a58 EFLAGS: 00010286
Apr 27 15:29:28 bismuth kernel: RAX: ffff9af83a8f7002 RBX: ffff9af83a8fdc00 RCX: ffff9af83a8fdc00
Apr 27 15:29:28 bismuth kernel: RDX: ffff9af83a8f6ffa RSI: ffff9af83a8edc02 RDI: ffff9af83a8fdbf8
Apr 27 15:29:28 bismuth kernel: RBP: 0000000000000050 R08: ffff9af83a8fdbf8 R09: 000000000000ffee
Apr 27 15:29:28 bismuth kernel: R10: 0000000000000000 R11: ffff9af83a8edc00 R12: 000000000000fffe
Apr 27 15:29:28 bismuth kernel: R13: 0000000000010000 R14: 0000000000000000 R15: 0000000000000000
Apr 27 15:29:28 bismuth kernel: FS:  0000000000000000(0000) GS:ffff9af8adb80000(0000) knlGS:0000000000000000
Apr 27 15:29:28 bismuth kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 27 15:29:28 bismuth kernel: CR2: ffff9af83a8f7000 CR3: 0000000816f04003 CR4: 00000000003606e0
Apr 27 15:29:28 bismuth kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr 27 15:29:28 bismuth kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr 27 15:29:28 bismuth kernel: Call Trace:
Apr 27 15:29:28 bismuth kernel:  ? __alloc_pages_nodemask+0x2cc/0x320
Apr 27 15:29:28 bismuth kernel:  ? kmalloc_order+0x14/0x30
Apr 27 15:29:28 bismuth kernel:  ZSTD_decompressDCtx+0x335/0x430 [zstd_decompress]
Apr 27 15:29:28 bismuth kernel:  __bio_uncompress.isra.0+0x1b6/0x230 [bcachefs]
Apr 27 15:29:28 bismuth kernel:  ? mempool_alloc+0x62/0x170
Apr 27 15:29:28 bismuth kernel:  ? kmalloc_order+0x14/0x30
Apr 27 15:29:28 bismuth kernel:  bch2_bio_uncompress+0x8d/0x140 [bcachefs]
Apr 27 15:29:28 bismuth kernel:  __bch2_read_endio+0x69d/0x920 [bcachefs]
Apr 27 15:29:28 bismuth kernel:  process_one_work+0x1da/0x380
Apr 27 15:29:28 bismuth kernel:  worker_thread+0x4d/0x3f0
Apr 27 15:29:28 bismuth kernel:  kthread+0xfb/0x130
Apr 27 15:29:28 bismuth kernel:  ? process_one_work+0x380/0x380
Apr 27 15:29:28 bismuth kernel:  ? kthread_park+0x80/0x80
Apr 27 15:29:28 bismuth kernel:  ret_from_fork+0x35/0x40
Apr 27 15:29:28 bismuth kernel: Modules linked in: uinput rfcomm af_packet ctr bnep msr ccm algif_aead des_generic arc4 algif_skcipher cmac sha512_ssse3 sha512_generic md4 algif_hash af_alg nls_iso8859_1 nls_cp437 vfat fat uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_common videodev mc btusb btrtl btbcm btintel bluetooth ecdh_generic ecc crc16 snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic joydev iwlmvm mousedev lz4 mac80211 libarc4 x86_pkg_temp_thermal intel_powerclamp i915 coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 iTCO_wdt crypto_simd mei_wdt dell_laptop ledtrig_audio dell_wmi iwlwifi intel_wmi_thunderbolt sparse_keymap dell_smbios cec dell_wmi_descriptor ppdev dcdbas wmi_bmof watchdog cryptd intel_rapl_msr evdev glue_helper intel_cstate mei_hdcp cfg80211 drm_kms_helper dell_smm_hwmon snd_hda_intel input_leds drm led_class deflate efi_pstore mac_hid pstore psmouse serio_raw intel_uncore snd_hda_codec rtsx_pci_ms i2c_i801
Apr 27 15:29:28 bismuth kernel:  snd_hda_core tpm_tis tpm_tis_core efivars snd_hwdep intel_gtt e1000e intel_rapl_perf ptp memstick pps_core wmi battery button tpm agpgart parport_pc i2c_algo_bit thermal rng_core parport video acpi_pad ac fb_sys_fops syscopyarea sysfillrect sysimgblt processor_thermal_device i2c_core intel_rapl_common int3403_thermal int3400_thermal mei_me intel_pmc_core dell_rbtn intel_soc_dts_iosf intel_pch_thermal dell_smo8800 acpi_thermal_rel backlight int340x_thermal_zone mei 8250_pci rfkill zram zsmalloc ip6table_nat iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv4 ip6t_rpfilter ipt_rpfilter ip6table_raw iptable_raw xt_pkttype nf_log_ipv6 nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp ip6table_filter ip6_tables iptable_filter sch_fq_codel snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd soundcore loop cpufreq_powersave tun tap macvlan bridge stp llc kvm_intel kvm irqbypass efivarfs ip_tables x_tables ipv6 nf_defrag_ipv6 crc_ccitt autofs4 poly1305_x86_64 poly1305_generic
Apr 27 15:29:28 bismuth kernel:  chacha_x86_64 chacha_generic bcachefs libcrc32c crc32c_generic zstd_compress xor lz4_compress zstd_decompress crc64 raid6_pq sd_mod ahci libahci rtsx_pci_sdmmc mmc_core libata atkbd xhci_pci libps2 xhci_hcd usbcore scsi_mod crc32c_intel rtsx_pci usb_common i8042 rtc_cmos serio dm_mod
Apr 27 15:29:28 bismuth kernel: CR2: ffff9af83a8f7000
Apr 27 15:29:28 bismuth kernel: ---[ end trace 8b39e6c69a6ee5c5 ]---
Apr 27 15:29:28 bismuth kernel: RIP: 0010:ZSTD_decompressSequences+0xbd2/0xce0 [zstd_decompress]
Apr 27 15:29:28 bismuth kernel: Code: 83 e1 3f e9 ba f6 ff ff 4d 89 c1 49 29 c1 49 83 f9 08 0f 8e 94 00 00 00 48 89 f2 4a 8d 3c 08 4c 8b 12 48 83 c0 08 48 83 c2 08 <4c> 89 50 f8 48 39 f8 72 ec 4c 01 ce 4c 89 c0 e9 4b fc ff ff 48 8b
Apr 27 15:29:28 bismuth kernel: RSP: 0000:ffffbea25b123a58 EFLAGS: 00010286
Apr 27 15:29:28 bismuth kernel: RAX: ffff9af83a8f7002 RBX: ffff9af83a8fdc00 RCX: ffff9af83a8fdc00
Apr 27 15:29:28 bismuth kernel: RDX: ffff9af83a8f6ffa RSI: ffff9af83a8edc02 RDI: ffff9af83a8fdbf8
Apr 27 15:29:28 bismuth kernel: RBP: 0000000000000050 R08: ffff9af83a8fdbf8 R09: 000000000000ffee
Apr 27 15:29:28 bismuth kernel: R10: 0000000000000000 R11: ffff9af83a8edc00 R12: 000000000000fffe
Apr 27 15:29:28 bismuth kernel: R13: 0000000000010000 R14: 0000000000000000 R15: 0000000000000000
Apr 27 15:29:28 bismuth kernel: FS:  0000000000000000(0000) GS:ffff9af8adb80000(0000) knlGS:0000000000000000
Apr 27 15:29:28 bismuth kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 27 15:29:28 bismuth kernel: CR2: ffff9af83a8f7000 CR3: 0000000816f04003 CR4: 00000000003606e0
Apr 27 15:29:28 bismuth kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Apr 27 15:29:28 bismuth kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Apr 27 15:29:29 bismuth xsession[1411]: KCrash: Attempting to start /nix/store/cqmlbiz6ihk1g3px55xwqhnarpknigd9-plasma-workspace-5.17.5/bin/.plasmashell-wrapped from kdeinit
Apr 27 15:29:29 bismuth xsession[1411]: KCrash: Application '.plasmashell-wrapped' crashing...
Apr 27 15:29:29 bismuth xsession[1411]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7775, resource id: 46137358, major code: 15 (QueryTree), minor code: 0
Apr 27 15:29:29 bismuth xsession[1411]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7899, resource id: 46137372, major code: 15 (QueryTree), minor code: 0
Apr 27 15:29:30 bismuth xsession[1411]: Service  "org.kde.StatusNotifierHost-1642" unregistered
Apr 27 15:29:32 bismuth systemd[1]: Started Process Core Dump (PID 23777/UID 0).
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event5  - Power Button: device removed
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event7  - Video Bus: device removed
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event3  - Power Button: device removed
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event4  - Sleep Button: device removed
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event19 - Integrated_Webcam_HD: Integrate: device removed
Apr 27 15:29:37 bismuth xserver-wrapper[1316]: (II) event6  - Dell WMI hotkeys: device removed
Apr 27 15:29:38 bismuth xserver-wrapper[1316]: (II) event0  - AT Translated Set 2 keyboard: device removed
Apr 27 15:29:38 bismuth xserver-wrapper[1316]: (II) event8  - AlpsPS/2 ALPS DualPoint Stick: device removed
Apr 27 15:29:38 bismuth xserver-wrapper[1316]: (II) event9  - AlpsPS/2 ALPS DualPoint TouchPad: device removed
Apr 27 15:29:38 bismuth xserver-wrapper[1316]: (II) event1  - DELL Wireless hotkeys: device removed
Apr 27 15:29:38 bismuth xserver-wrapper[1316]: (II) event20 - MA650 Wireless (AVRCP): device removed
Apr 27 15:29:39 bismuth systemd[1]: Started Getty on tty6.
Apr 27 15:29:39 bismuth xsession[1411]: powerdevil: ACTIVE SESSION PATH CHANGED: "/"
Apr 27 15:29:39 bismuth xsession[1411]: powerdevil: Switched to inactive session - leaving unchanged
Apr 27 15:29:41 bismuth xsession[1411]: Qt: Session management error: networkIdsList argument is NULL
Apr 27 15:29:42 bismuth kernel: BUG: kernel NULL pointer dereference, address: 0000000000000050
</pre></code></details>

**Comment by koverstreet** [comment]
Fixed by 37d599c3d0
