### ISSUE TITLE
Filesystem corruption

### ISSUE THREAD

**Issue by RAOF** [koverstreet/bcachefs#101]
I've got a root filesystem that has started to exhibit corruption after multiple lockups and hard reboots (currently on 2284156e2, but the lockups have been occurring since maybe c0797e7b).

This manifests as
```
ls: cannot access '/var/cache/apt/archives.old/linux-tools-5.4.0+bcachefs.git20200502.2284156e2-1-generic_5.4.0+bcachefs.git20200502.2284156e2-1_amd64.deb': No such file or directory
total 0
drwxr-xr-x 2 root root 0 May  2 22:14 ./
drwxr-xr-x 4 root root 0 May  4 14:23 ../
-????????? ? ?    ?    ?            ? linux-tools-5.4.0+bcachefs.git20200502.2284156e2-1-generic_5.4.0+bcachefs.git20200502.2284156e2-1_amd64.deb
```
Which looks like the inode corresponding to the dentry has disappeared? (There are a bunch of different files for which this has occurred; this is just one of the examples)

I've got a `bcachefs dump` of this filesystem. At 2.6GB it's a *little* big to add as an attachment :grin:. How would you like it?

I've not filed a bug about the lockups as I've not yet managed to get a good trace (this laptop doesn't have a wired ethernet port, and netconsole over wifi appears to generate a whole bunch of spurious messages). I've just discovered `pstore` over EFI, so I'll see if I can get a good trace out of that!

**Comment by koverstreet** [comment]
What does fsck say?

I've been fixing a bunch of deadlocks. Still one or two left it looks like, but I just pushed out more fixes today.

**Comment by RAOF** [comment]
fsck is clean (at least after a clean unmount); it doesn't seem to notice this.

**Comment by RAOF** [comment]
Oh, sorry! I apparently `fsck`ed this earlier, before the corruption had set in.

fsck did a *whole bunch* of complaining about all sorts of things (wrong data type, n_links wrong, all the broken files by name) and then fixed it.
