### ISSUE TITLE
disk usage increased more than n sectors reserved

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#106]
On 37d599c3d0ebb358a413b1e9b60a4fb2a841125b. Not really new, but I wanted to make sure it was reported.
<details><summary>Log</summary><code><pre>
May 10 11:22:03 bismuth kernel: ------------[ cut here ]------------
May 10 11:22:03 bismuth kernel: disk usage increased by 1 without a reservation
May 10 11:22:03 bismuth kernel: WARNING: CPU: 2 PID: 4465 at fs/bcachefs/buckets.c:407 bch2_fs_usage_apply+0xd7/0xf0 [bcachefs]
May 10 11:22:03 bismuth kernel: Modules linked in: rfcomm af_packet ctr ccm bnep algif_aead cbc des_generic libdes ecb arc4 algif_skcipher msr cmac sha512_ssse3 sha512_generic md4 algif_hash af_alg nls_iso8859_1 nls_cp437 vfat fat snd_hda_codec_hdmi snd_hda_codec_realtek joydev snd_hda_codec_generic mousedev iwlmvm mac80211 libarc4 i915 x86_pkg_temp_thermal intel_powerclamp coretemp crc32_pclmul ghash_clmulni_intel aesni_intel crypto_simd cryptd mei_hdcp iTCO_wdt mei_wdt watchdog snd_hda_intel dell_laptop cec lz4 ledtrig_audio intel_rapl_msr ppdev uvcvideo dell_wmi e1000e input_leds snd_intel_dspcfg wmi_bmof dell_smbios sparse_keymap intel_wmi_thunderbolt iwlwifi deflate glue_helper videobuf2_vmalloc efi_pstore intel_cstate led_class dell_wmi_descriptor videobuf2_memops evdev drm_kms_helper snd_hda_codec dcdbas intel_uncore mac_hid ptp dell_smm_hwmon pstore snd_hda_core intel_rapl_perf psmouse serio_raw efivars videobuf2_v4l2 pps_core snd_hwdep i2c_i801 cfg80211 videobuf2_common drm tpm_tis btusb intel_gtt
May 10 11:22:03 bismuth kernel:  agpgart videodev tpm_tis_core btrtl btbcm btintel mc mei_me i2c_algo_bit 8250_pci bluetooth fb_sys_fops mei processor_thermal_device syscopyarea intel_pch_thermal tpm intel_rapl_common parport_pc sysfillrect sysimgblt ecdh_generic ecc crc16 libaes i2c_core intel_soc_dts_iosf thermal rng_core parport battery dell_smo8800 video backlight int3403_thermal int340x_thermal_zone wmi int3400_thermal intel_pmc_core dell_rbtn acpi_thermal_rel ac acpi_pad rfkill button zram zsmalloc ip6table_nat iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv4 ip6t_rpfilter ipt_rpfilter ip6table_raw iptable_raw xt_pkttype nf_log_ipv6 nf_log_ipv4 nf_log_common xt_LOG sch_fq_codel xt_tcpudp ip6table_filter ip6_tables iptable_filter snd_pcm_oss snd_mixer_oss snd_pcm snd_timer snd soundcore loop cpufreq_powersave tun tap macvlan bridge stp llc kvm_intel kvm irqbypass efivarfs ip_tables x_tables ipv6 nf_defrag_ipv6 crc_ccitt autofs4 poly1305_generic libpoly1305 poly1305_x86_64 chacha_generic
May 10 11:22:03 bismuth kernel:  chacha_x86_64 libchacha bcachefs libcrc32c crc32c_generic zstd_compress xor lz4_compress zstd_decompress crc64 raid6_pq sd_mod t10_pi crc_t10dif crct10dif_generic rtsx_pci_sdmmc mmc_core atkbd libps2 xhci_pci ahci xhci_hcd libahci libata usbcore crct10dif_pclmul crct10dif_common crc32c_intel scsi_mod rtsx_pci usb_common i8042 rtc_cmos serio dm_mod
May 10 11:22:03 bismuth kernel: CPU: 2 PID: 4465 Comm: kworker/2:0 Not tainted 5.6.0 #1-NixOS
May 10 11:22:03 bismuth kernel: Hardware name: Dell Inc. Latitude E5470/0C8FKJ, BIOS 1.19.3 08/20/2018
May 10 11:22:03 bismuth kernel: Workqueue: bcachefs bch2_write_index [bcachefs]
May 10 11:22:03 bismuth kernel: RIP: 0010:bch2_fs_usage_apply+0xd7/0xf0 [bcachefs]
May 10 11:22:03 bismuth kernel: Code: ff ff ff ff 4c 89 e8 e9 7a ff ff ff 4c 89 e6 48 c7 c7 08 a5 52 c0 89 4c 24 0c 48 89 14 24 c6 05 d1 b4 08 00 01 e8 3b e3 5a cd <0f> 0b 48 8b 14 24 8b 4c 24 0c eb c0 66 66 2e 0f 1f 84 00 00 00 00
May 10 11:22:03 bismuth kernel: RSP: 0018:ffffb840c5297620 EFLAGS: 00010282
May 10 11:22:03 bismuth kernel: RAX: 0000000000000000 RBX: ffff949ddf0af780 RCX: 0000000000000000
May 10 11:22:03 bismuth kernel: RDX: 000000000000002f RSI: ffffffff8efc05af RDI: 0000000000000246
May 10 11:22:03 bismuth kernel: RBP: ffff949de4990000 R08: 000001eb25b3fc01 R09: 000000000000002f
May 10 11:22:03 bismuth kernel: R10: 0000000000000000 R11: ffffffff8efc0599 R12: 0000000000000001
May 10 11:22:03 bismuth kernel: R13: 0000000000000008 R14: ffffb840c5297b50 R15: 0000000000000007
May 10 11:22:03 bismuth kernel: FS:  0000000000000000(0000) GS:ffff949dedd00000(0000) knlGS:0000000000000000
May 10 11:22:03 bismuth kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
May 10 11:22:03 bismuth kernel: CR2: 000010d8f8515000 CR3: 000000022760a006 CR4: 00000000003606e0
May 10 11:22:03 bismuth kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
May 10 11:22:03 bismuth kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
May 10 11:22:03 bismuth kernel: Call Trace:
May 10 11:22:03 bismuth kernel:  bch2_trans_fs_usage_apply+0x4c/0xa0 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? bch2_mark_key_locked+0x3be/0x730 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? bch2_mark_update+0xbd/0x200 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? bch2_replicas_entry_idx+0x7e/0xc0 [bcachefs]
May 10 11:22:03 bismuth kernel:  __bch2_trans_commit+0x1c46/0x1c70 [bcachefs]
May 10 11:22:03 bismuth kernel:  bch2_extent_update+0x2d8/0x4a0 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? __alloc_pages_nodemask+0x171/0x320
May 10 11:22:03 bismuth kernel:  ? __btree_iter_traverse_all+0x115/0x380 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? __btree_trans_get_iter+0x6d/0x4a0 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? __kmalloc_track_caller+0x165/0x250
May 10 11:22:03 bismuth kernel:  ? bch2_trans_preload_mem+0x40/0xc0 [bcachefs]
May 10 11:22:03 bismuth kernel:  bch2_write_index_default+0x1eb/0x340 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x34/0x70
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x40/0x70
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x34/0x70
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x40/0x70
May 10 11:22:03 bismuth kernel:  ? bch2_write_index_default+0x71/0x340 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? try_to_del_timer_sync+0x4f/0x80
May 10 11:22:03 bismuth kernel:  ? del_timer_sync+0x25/0x40
May 10 11:22:03 bismuth kernel:  ? schedule_timeout+0x166/0x300
May 10 11:22:03 bismuth kernel:  ? blk_mq_sched_dispatch_requests+0x11b/0x170
May 10 11:22:03 bismuth kernel:  ? update_load_avg+0x78/0x5f0
May 10 11:22:03 bismuth kernel:  ? update_curr+0xb6/0x1a0
May 10 11:22:03 bismuth kernel:  ? enqueue_entity+0xc0/0x2a0
May 10 11:22:03 bismuth kernel:  ? wakeup_preempt_entity.isra.0+0x3d/0x50
May 10 11:22:03 bismuth kernel:  ? check_preempt_wakeup+0xf2/0x220
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x40/0x70
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x34/0x70
May 10 11:22:03 bismuth kernel:  ? __switch_to_asm+0x34/0x70
May 10 11:22:03 bismuth kernel:  ? __bch2_rebalance_pred.isra.0+0x14f/0x2a0 [bcachefs]
May 10 11:22:03 bismuth kernel:  ? bch2_bkey_is_incompressible+0x6b/0x130 [bcachefs]
May 10 11:22:03 bismuth kernel:  __bch2_write_index+0x329/0x3c0 [bcachefs]
May 10 11:22:03 bismuth kernel:  bch2_write_index+0x13/0x90 [bcachefs]
May 10 11:22:03 bismuth kernel:  process_one_work+0x1e4/0x390
May 10 11:22:03 bismuth kernel:  worker_thread+0x4d/0x3f0
May 10 11:22:03 bismuth kernel:  kthread+0xfb/0x130
May 10 11:22:03 bismuth kernel:  ? process_one_work+0x390/0x390
May 10 11:22:03 bismuth kernel:  ? kthread_park+0x90/0x90
May 10 11:22:03 bismuth kernel:  ret_from_fork+0x35/0x40
May 10 11:22:03 bismuth kernel: ---[ end trace bb07e84a18741ca4 ]---
May 10 11:22:03 bismuth kernel: bcachefs (2ff5f1b8-38cb-4cc6-896c-712271a74e7e): disk usage increased more than 8 sectors reserved
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() while inserting
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 8 type extent 611724:7352 snap 0 len 8 ver 64952434: crc: c_size 8 size 8 offset 0 nonce 0 csum 3 compress 0 ptr: 0:30332248 gen 47
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() overlapping with
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 8 type extent 611724:7376 snap 0 len 88 ver 64946736: crc: c_size 8 size 88 offset 0 nonce 0 csum 3 compress 4 ptr: 0:74010736 gen 79
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() while inserting
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 7 type alloc 0:59242 snap 0 len 0 ver 0: gen 47 read_time 17262 write_time 13705 data_type 4 dirty_sectors 352 oldest_gen 46
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() overlapping with
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 7 type alloc 0:59242 snap 0 len 0 ver 0: gen 47 read_time 17262 write_time 13705 data_type 4 dirty_sectors 344 oldest_gen 46
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() while inserting
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 7 type alloc 0:144552 snap 0 len 0 ver 0: gen 79 read_time 17262 write_time 13705 data_type 4 dirty_sectors 477 oldest_gen 67
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() overlapping with
May 10 11:22:03 bismuth kernel: bcachefs: bch2_trans_fs_usage_apply() u64s 7 type alloc 0:144552 snap 0 len 0 ver 0: gen 79 read_time 17262 write_time 13705 data_type 4 dirty_sectors 476 oldest_gen 67</pre></code></details>

**Comment by koverstreet** [comment]
Any info on the workload that caused it? Are tiering or compression in use?

**Comment by hyperfekt** [comment]
zstd compression, tiering and encryption are used.
i don't really know what triggered it since i only discovered it after the fact during my occasional journal grepping.

**Comment by koverstreet** [comment]
Fixed by 278fe397bb
