### ISSUE TITLE
different types of data in the same bucket: data, btree 2: electric boogaloo

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#123]
After an unrelated kernel panic on 91fedfccb2e4d3941fe5ebe63930b52b9e800283, the reboot greets with this:
```
bcachefs (a7714f48-b261-4e01-9e84-0c6090a81640): journal read done, 0 keys in 1 entries, seq 919646
bcachefs (a7714f48-b261-4e01-9e84-0c6090a81640): starting metadata mark and sweep
bcachefs (a7714f48-b261-4e01-9e84-0c6090a81640): bucket 0:20074 gen 147 different types of data in same bucket: btree, data, exiting
bcachefs (a7714f48-b261-4e01-9e84-0c6090a81640): error in fsck: error -1 while deleting inode
bcachefs (a7714f48-b261-4e01-9e84-0c6090a81640): Error in recovery: error in recovery (-1)
```
Tiered, with zstd compression, ACLs, and encryption.
Persists with 2d63be71cfef677d615783e71c24d5939496b254.
fsck with reconstruct_alloc has lots of
`bucket 0:[num] data type cached ptr gen in the future: [num] > [num], fixing`
and the occasional
`bucket 0:[num] gen [num] different types of data in same bucket: data, btree (run fsck to correct)`.

Dumps are [here](https://files.hyperfekt.net/bcachefs-dumps/different-types-of-data-in-same-bucket.0.qcow2) and [here](https://files.hyperfekt.net/bcachefs-dumps/different-types-of-data-in-same-bucket.1.qcow2).

**Comment by koverstreet** [comment]
Closing old bugs, reopen if anyone sees it again
