### ISSUE TITLE
bcachefs.org on pages.github.com

### ISSUE THREAD

**Issue by godofdream** [koverstreet/bcachefs#125]
Many of the pages on bcachefs.org are outdated or could use some love.
Would you consider hosting bcachefs.org on https://pages.github.com/ so people can make contributions to your website using the git workflow?

**Comment by koverstreet** [comment]
I've already got the website in a git repository with a nice workflow that I like, using ikiwiki

We could perhaps move it to github and mirror it back so that people can use github style pull requests

**Comment by godofdream** [comment]
I would love to create some pullrequests for the website. But also some automation stuff like travis-ci and static analysis tools.
I hope by improving your website your project gets more funding.
