### ISSUE TITLE
bcachefs causes load to 8.00 when something goes wrong

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#128]
I have a background target on a adaptec raid6 array.
Due to its nature, the adapter sometimes re-initializes, whereby IO request to the backing device are held.
bcachefs then loads a 12-cpu (ok, 6 with ht) to a 8.00 load where the process load is 0.1% according to top.
also: it never returns to normal, even when the backing device is online again.
Is it possible to block those threads when they become unresponsive? eventually resuming them via an event listener?

**Comment by koverstreet** [comment]
Can you run perf top when it's happening and see what's going on? Check the tracepoints too: perf top -e bcachefs:*

**Comment by jpsollie** [comment]
With a load of 8, while reading a directory of files with tar, perf top -e bcachefs:*:
```
PerfTop:       0 irqs/sec  kernel: 0.0%  exact:  0.0% lost: 0/0 drop: 0/0 [bcachefs:read_split],  (all, 12 CPUs)
```
output stayed the same for almost 30s
Also tried with perf top:
```
PerfTop:     437 irqs/sec  kernel:92.7%  exact:  0.0% lost: 0/0 drop: 0/0 [4000Hz cycles],  (all, 12 CPUs)
```

**Comment by koverstreet** [comment]
Perf top should give you more output than that - which functions are running when it's spinning like that?

**Comment by jpsollie** [comment]
What do you mean with 'functions'? I'm afraid I do not understand the question :s

**Comment by koverstreet** [comment]
perf top should give you a full page of output, I need all of it

**Comment by jpsollie** [comment]
That's the weird thing: perf top did not give me any output when running with bcachefs regex.  Really nothing.
When running witthout expression, there is nothing really interesting there, I guess, no process rises above 20% usage ...
I'll see if the error occurs again, so I can provide you more info

**Comment by jpsollie** [comment]
* UPDATE * I managed to fix the underlying problem on the adaptec controller (see https://bugzilla.kernel.org/show_bug.cgi?id=208605 ) so the error does not appear again.  As I am happy with the setup being stable, I'll close the bug for now, as I'm not really encouraged to break it again
