### ISSUE TITLE
Linux 5.0 build errors

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#13]
removes current_kernel_time64 ZFS does fix this by:

https://github.com/tonyhutter/zfs/commit/a27c6e1f4582dcb52effedcd87d58f7ed282c6fa

also merging with upstream removes include/crypto/chacha20.h

**Comment by nicman23** [comment]
with linux 4.20 EOL please take a look at this.

**Comment by koverstreet** [comment]
5.0 rebase is done
