### ISSUE TITLE
bcachefs incorrect size?

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#135]
It may not be an issue, but I think it's quite a lot:
```
(parted) print                                                            
Error: /dev/sdf: unrecognised disk label
Model: ASR72405 (scsi)                                         
Disk /dev/sdf: 18.0TB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 
```
while df says:
```
df -h
Filesystem    Size  Used Avail Use% Mounted on
/dev/root       432G   65G  345G  16% /
...
/dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B768229124F-part3:/dev/disk/by-id/scsi-35000cca01306e894-part3:/dev/disk/by-id/scsi-35000cca01307d518-part2:/dev/disk/by-id/scsi-2af16557500d00000   16T  6.9G   16T   1% /data/library
```
Is this the expected behaviour? a 12.5% decrease of available size?

**edit** it becomes even worse:
```
/dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B768229124F-part4:/dev/disk/by-id/nvme-GIGABYTE_GP-GSM2NE3256GNTD_SN193808935753-part2:/dev/disk/by-id/scsi-35000cca01307d518-part1:/dev/disk/by-id/scsi-35000cca01306e894-part2:/dev/disk/by-id/scsi-2b114caeb00d00000     34T      21M   34T   1% /data/lib2
```
that's 15%! the disk is 40T according to parted. isn't it a bit greedy to take 15% of the disk? I mean, ext4 is happy with 8% ... 
Also, the show-super info lists a size between 34 and 40:
```
Device 4:
    UUID:                       6b7c27c8-9f20-4c86-b37e-731e86ea4b37
    Size:                       36.4T
    Bucket size:                512.0K
    First bucket:               0
    Buckets:                    76287980
    Last mount:                 Sat Jul 11 10:19:13 2020
    State:                      readwrite
    Group:                      HDD (1)
    Data allowed:               journal,btree,data
    Has data:                   (none)
    Replacement policy:         lru
    Discard:                    0
```

If you think this is correct, OK, but I'd be surprised if you need that much :)

**Comment by clonejo** [comment]
IIRC parted shows sizes in powers of 1000, not 1024. df shows sizes in powers of 1024 by default (try `--si`). parted also has a `unit` comand to change the behavior.
This could explain your first case, but does not account for all of the difference in the second case.

**Comment by koverstreet** [comment]
We also have to reserve some space for copygc, that's most of the rest.

**Comment by jpsollie** [comment]
Ah, thank you for the hint! I thought parted showed MiB...
I verified the disc sizes in MB reported by arcconf, and when I say mb * 1024^2 / 1000^4, I indeed end up with a 40TB space, and when I do mb / 1024^2, it ends up being a 36TiB drive. So sorry everyone, my mistake
