### ISSUE TITLE
error in fsck: error -5 / -30 while deleting inode

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#148]
Booting after a normal shutdown greeted me with this:
```
Aug 24 11:55:26 nixos kernel: bcachefs (3b810908-7c1c-48dc-9303-78301f0af401): journal read done, 0 keys in 1 entries, seq 1129431
Aug 24 11:55:29 nixos kernel: bcachefs (3b810908-7c1c-48dc-9303-78301f0af401): error in fsck: error -30 while deleting inode
Aug 24 11:55:29 nixos kernel: bcachefs (3b810908-7c1c-48dc-9303-78301f0af401): Error in recovery: error in recovery (-30)
```
The filesystem was created with a rebased 700b6bfc1817d73fcb80c52d627ed2ec19db148a, with ACLs, reflinks, encrypion, and zstd compression. The problem occurred on rebased 9622319a677f82ee659ab03b9658f302c989a63c. It will still not mount with rebased 86fa1258a3ef59adccdd1534e55ef773b82c4cb7.
Dump is [here](https://files.hyperfekt.net/bcachefs-dumps/error_deleting_inode.0.qcow2) and [here](https://files.hyperfekt.net/bcachefs-dumps/error_deleting_inode.1.qcow2), fsck log [here](https://github.com/koverstreet/bcachefs/files/5117606/fsck.log).

**Comment by koverstreet** [comment]
Fixed by 2924887c5a
