### ISSUE TITLE
error in fsck: error -5 while deleting inode

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#149]
Booting after resetting because of a system freeze had this show up:
```
Sep 15 02:39:25 nixos kernel: bcachefs (bb319b54-30a2-424a-be7a-7c4aaa918adf): bucket 1:142894 gen 101 data type user: ptr gen 5 too stale
                              while marking u64s 9 type extent 227131:3872 snap 0 len 8 ver 19371520: crc: c_size 8 size 8 offset 0 nonce 0 csum 3 compress 0 ptr: 0:989464056 gen 1 ptr: 1:73161776 gen 5 cached stale, exiting
Sep 15 02:39:25 nixos kernel: bcachefs (bb319b54-30a2-424a-be7a-7c4aaa918adf): error in fsck: error -5 while deleting inode
Sep 15 02:39:25 nixos kernel: bcachefs (bb319b54-30a2-424a-be7a-7c4aaa918adf): Error in recovery: error in recovery (-5)
```
The filesystem was created with a rebased 7e04f345cc3a1b48a1885394e210068b7bf5a0c0, with ACLs, reflinks, encrypion, and zstd compression, and the problem occured with the same commit. It will still not mount with rebased fb2821e72648f35d3cff61ac26041d634fd1dacf.
Dump is [here](https://files.hyperfekt.net/bcachefs-dumps/error_deleting_inode_again.0.qcow2) and [here](https://files.hyperfekt.net/bcachefs-dumps/error_deleting_inode_again.1.qcow2), fsck log [here](https://github.com/koverstreet/bcachefs/files/5222256/fsck.log).

 May or may not be related to #148.

**Comment by hyperfekt** [comment]
Experiencing what I believe to be another instance of this, on fb2821e72648f35d3cff61ac26041d634fd1dac. Can provide dump if required.
```
Sep 28 15:06:26 nixos kernel: bcachefs (51d7852b-dc6e-4ba3-9766-db2a85572913): bucket 1:351173 gen 109 data type user: ptr gen 13 too stale
                              while marking u64s 11 type extent 338422:872 snap 0 len 32 ver 826354: crc: c_size 120 size 128 offset 96 nonce 0 csum 3 compress 4 ptr: 0:90925400 gen 1 crc: c_size 32 size 32 offset 0 nonce 96 csum 3 compress 5 , exiting
Sep 28 15:06:26 nixos kernel: bcachefs (51d7852b-dc6e-4ba3-9766-db2a85572913): error in fsck: error -5 while deleting inode
Sep 28 15:06:26 nixos kernel: bcachefs (51d7852b-dc6e-4ba3-9766-db2a85572913): Error in recovery: error in recovery (-5)
```

**Comment by koverstreet** [comment]
Is it still possible to get a dump?

**Comment by hyperfekt** [comment]
You're a day late, unfortunately! I forgot to make one before I got rid of the fs. Sorry about that.

**Comment by koverstreet** [comment]
Damn. Well, this looks to be the most serious known outstanding bug, so let me know if you can figure out trigger it.

Are you using tiering?

**Comment by hyperfekt** [comment]
I was indeed. One SSD as promote and foreground, one HDD as background.

**Comment by hyperfekt** [comment]
I'm relatively confident I can trigger it again, considering how quickly it happened a second time - do you think a second dump will be sufficient to fix it? Or is there any other data I can collect?

**Comment by koverstreet** [comment]
I think I figured it out. The check had an off by one error, and also the
code to clean up stale ptrs seems to not be working because I never
actually finished the new version. Whoops.

**Comment by koverstreet** [comment]
Fixed by cfa372a898 and 66bb5aceb6

**Comment by hyperfekt** [comment]
Hit this again on bd6ed9fb42c0aa36d1f4a21eeab45fe12e1fb792.
```
bucket 1:439121 gen 153 data type user: ptr gen 25 too stale
while marking u64s 11 type extent 113892:1672:U32_MAX len 24 ver 52264942: crc: c_size 8 size 32 offset 0 nonce 0 csum 3 compress 4 ptr: 1:224830112 gen 25 cached crc: c_size 8 size 24 offset 0 nonce 0 csum 3 comp (run fsck to correct)
error in fsck: error -5 while deleting inode
Error in recovery: error in fsck (-5)
```

**Comment by hyperfekt** [comment]
This is the result when fscking with koverstreet/bcachefs-tools@837b76ce9507fa2a69ddeecc1e1b6d3fabb08227
```
0x7f73371b54c0U: bucket 1:40699 gen 46 data type user: ptr gen 193 too stale
while marking u64s 9 type extent 100867:23609544:U32_MAX len 16 ver 28807895: crc: c_size 16 size 16 offset 0 nonce 32 csum chacha20_poly1305_80 compress incompressible ptr: 1:20837960 gen 193 cached stale ptr: 0: (run fsck to correct)
0x7f73371b54c0U: bch2_gc_mark_key: ret -5
0x7f73371b54c0U: bch2_gc_btree_init_recurse: error -5 from bch2_gc_mark_key
0x7f73371b54c0U: bch2_gc_btree_init: ret -5
0x7f73371b54c0U: bch2_gc_btrees: ret -5
0x7f73371b54c0U: Error in recovery: error in mark and sweep (-5)
``
Two different buckets, strangely?
