### ISSUE TITLE
Kconfig.debug compiler does not like paths without "

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#15]
diff --git a/lib/Kconfig.debug b/lib/Kconfig.debug
index 49af4a9bafcb..42cef5984c2b 100644
--- a/lib/Kconfig.debug
+++ b/lib/Kconfig.debug
@@ -439,7 +439,7 @@ config DEBUG_KERNEL
 
 menu "Memory Debugging"
 
-source mm/Kconfig.debug
+source "mm/Kconfig.debug"
 
 config DEBUG_OBJECTS
  bool "Debug object operations"
@@ -1623,7 +1623,7 @@ config DYNAMIC_FAULT
  default n
  depends on DEBUG_FS
 
-source kernel/trace/Kconfig
+source "kernel/trace/Kconfig"
 
 config PROVIDE_OHCI1394_DMA_INIT
  bool "Remote debugging over FireWire early on boot"

**Comment by koverstreet** [comment]
On Sat, Feb 09, 2019 at 08:20:49AM -0800, nicman23 wrote:
> diff --git a/lib/Kconfig.debug b/lib/Kconfig.debug
> index 49af4a9bafcb..42cef5984c2b 100644
> --- a/lib/Kconfig.debug
> +++ b/lib/Kconfig.debug
> @@ -439,7 +439,7 @@ config DEBUG_KERNEL
>  
>  menu "Memory Debugging"
>  
> -source mm/Kconfig.debug
> +source "mm/Kconfig.debug"
>  
>  config DEBUG_OBJECTS
>   bool "Debug object operations"
> @@ -1623,7 +1623,7 @@ config DYNAMIC_FAULT
>   default n
>   depends on DEBUG_FS
>  
> -source kernel/trace/Kconfig
> +source "kernel/trace/Kconfig"
>  
>  config PROVIDE_OHCI1394_DMA_INIT
>   bool "Remote debugging over FireWire early on boot"

Can you send it with git send-email? Or even a github pull request?

**Comment by nicman23** [comment]
it is actually in the linux master already as i have found out. closing this as it will probably happen in the next rebase
