### ISSUE TITLE
kernel BUG at __bch2_trans_commit

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#154]
(view attachment for dmesg)
error appeared during transfer of a large file (10GiB) via NFS.
Previous transfers (on another bcachefs drive) of <3GB worked fine, but I was unable to umount them ("device busy" while all NFS shares are unmounted).  2 other drives which were untouched since last boot unmounted properly.
[dmesgoutput.txt](https://github.com/koverstreet/bcachefs/files/5416022/dmesgoutput.txt)
I tried it a 2nd time using CIFS instead of NFS, and this worked, though not sure whether that's relevant ...

**Comment by koverstreet** [comment]
Can you use scripts/faddr2line (in the kernel source tree, pass it the vmlinux file from the kernel build directory) to get me the line number where that happened? Pass it _bch2_trans_commit+0x6b3/0xa70

**Comment by jpsollie** [comment]
Sorry, but I have no experience with this script.  It also does not give me the function output you need (I guess):
```
janpieter@linuxserver /usr/src/bcachefs $ scripts/faddr2line fs/bcachefs/bcachefs.ko  _bch2_trans_commit+0x6b3/0xa70
no match for _bch2_trans_commit+0x6b3/0xa70
janpieter@linuxserver /usr/src/bcachefs $ scripts/faddr2line vmlinux _bch2_trans_commit+0x6b3/0xa70
no match for _bch2_trans_commit+0x6b3/0xa70
janpieter@linuxserver /usr/src/bcachefs $ 
```

**Comment by koverstreet** [comment]
ah, it's two underscores:

scripts/faddr2line vmlinux __bch2_trans_commit+0x6b3/0xa70

**Comment by jpsollie** [comment]
sorry, no result either:
```
linuxserver /usr/src/bcachefs # scripts/faddr2line vmlinux __bch2_trans_commit+0x6b3/0xa70
no match for __bch2_trans_commit+0x6b3/0xa70
linuxserver /usr/src/bcachefs # 

```

**Comment by koverstreet** [comment]
Is bcachefs built as a module? You'll want to pass it fs/bcachefs/bcachefs.o in that case.

Also if you've built a new kernel since then it may not work.
