### ISSUE TITLE
bcachefs master conflicts with kernel stable patch 5.9.2

### ISSUE THREAD

**Issue by Valmar33** [koverstreet/bcachefs#158]
==> Starting prepare()...
      -> Setting version...
      -> Fetch and merge stable tag from Arch vanilla kernel repository...
    remote: Enumerating objects: 6602, done.
    remote: Counting objects: 100% (6602/6602), done.
    remote: Compressing objects: 100% (1045/1045), done.
    remote: Total 5226 (delta 4369), reused 5033 (delta 4176), pack-reused 0
    Receiving objects: 100% (5226/5226), 923.55 KiB | 709.00 KiB/s, done.
    Resolving deltas: 100% (4369/4369), completed with 1340 local objects.
    From https://git.archlinux.org/linux
     * tag                         v5.9.2-arch1 -> FETCH_HEAD
    Auto-merging mm/filemap.c
    CONFLICT (content): Merge conflict in mm/filemap.c
    Auto-merging lib/Makefile
    Auto-merging lib/Kconfig.debug
    Auto-merging kernel/module.c
    Auto-merging kernel/locking/lockdep_internals.h
    Removing include/dt-bindings/mux/mux-j721e-wiz.h
    Auto-merging block/blk-core.c
    Automatic merge failed; fix conflicts and then commit the result.
    ==> ERROR: A failure occurred in prepare().
        Aborting...

**Comment by HittingSmoke** [comment]
There are several changes to filemap.c which conflict with Kent's bcachefs patches after 5.9.1. There are also some patches in the openSUSE kernel patch set which conflict, indicating there may be more issues soon in the future.

**Comment by koverstreet** [comment]
rebased to 5.10, no longer applies
