### ISSUE TITLE
compression leads to filesystem hangs

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#16]
When I create a filesystem with` bcachefs format --compression=zstd --background_compression=zstd --foreground_target=/dev/sda1 --background_target=/dev/sdb1 --promote_target=/dev/sda1 --encrypted --label=nixos --force /dev/sdb1 --discard /dev/sda1` and attempt to install NixOS on it the install hangs on an `fdatasync` syscall with 100% CPU usage on one core not attributed to any process in `top`.
[Here](https://github.com/koverstreet/bcachefs/files/2848182/hang.log) is the `strace -f` log, with anything from line 76676 onwards trigged by sending SIGINT, which does not stop the hang.

**Comment by hyperfekt** [comment]
I'm also getting hangs trying to copy data off of the filesystem.
[hangcp.log](https://github.com/koverstreet/bcachefs/files/2848218/hangcp.log)

**Comment by koverstreet** [comment]
Which commits were you reverting?

I'm not seeing anything with xfstests, and I wouldn't expect a hang in fdatasync to have anything to do with the format options, so something weird is going on...

Can you try without zstd?

**Comment by hyperfekt** [comment]
Sorry, I should have used the term 'amended', it seems you made this change at some point and I was referring to it happening even with it:
```
diff --git a/fs/bcachefs/btree_gc.h b/fs/bcachefs/btree_gc.h
index 1905acfa028a..8af5f841a537 100644
--- a/fs/bcachefs/btree_gc.h
+++ b/fs/bcachefs/btree_gc.h
@@ -109,7 +109,7 @@ static inline bool gc_visited(struct bch_fs *c, struct gc_pos pos)
 
        do {
                seq = read_seqcount_begin(&c->gc_pos_lock);
-               ret = gc_pos_cmp(pos, c->gc_pos) < 0;
+               ret = gc_pos_cmp(pos, c->gc_pos) <= 0;
        } while (read_seqcount_retry(&c->gc_pos_lock, seq));
 
        return ret;
```

I'm still installing but I got past the point where it usually hangs by omitting zstd, looks like that is where the problem lies.

**Comment by hyperfekt** [comment]
The issue seems to also occur with lz4, but I can confirm it does not happen without compression.

**Comment by koverstreet** [comment]
Oh, it might be because of the background_compression option. Can you try
without that?

**Comment by hyperfekt** [comment]
Happens with only `--compression`, too.

**Comment by koverstreet** [comment]
Can you get me some backtraces from when it happens? perf top output?

cat /proc/pid/stack is useful for getting backtraces.

I've got a torture test running with lz4 - copying some data to a
filesystem, doing a sync (which hits the same paths as fdatasync), deleting
and starting over - but I'm not seeing anything so far.

Can you tell me anything more about how to repro it?

**Comment by hyperfekt** [comment]
[perf top output](https://github.com/koverstreet/bcachefs/files/2849984/perf-top.log)
[backtrace](https://github.com/koverstreet/bcachefs/files/2849985/backtrace.log)

You should be able to reproduce it by starting a NixOS ISO, creating the filesystem, mounting it under `/mnt`, doing `nixos-generate-config --root /mnt`, copying `this file` to `/mnt/etc/nixos` and adding it to the imports list of the `/mnt/etc/nixos/configuration.nix` file. Then do `nix-channel --add http://nixos.org/channels/nixos-unstable nixos-unstable` and run `nixos-install --root /mnt`. The installation should hang with the output of `querying info about missing paths`. Make sure you've provided networking.

**Comment by koverstreet** [comment]
I managed to repro it - working on it now.

**Comment by koverstreet** [comment]
I think I've got it fixed - can you test it?

**Comment by hyperfekt** [comment]
The install works fine now, thanks for the quick fix! I got another problem, but I'll open a separate issue for that.
