### ISSUE TITLE
bcachefs still writes to devices after umount

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#166]
After umount tiered fs kernel thread ` bch-rebalance/f` is still writing to devices but it shouldn't touch it after umount.

**Comment by marcin-github** [comment]
Path `/sys/fs/bcachefs/<uuid>` still exists.

**Comment by koverstreet** [comment]
Are you sure the filesystem wasn't mounted in more than one place?

**Comment by marcin-github** [comment]
I'm sure.
