### ISSUE TITLE
fsck error after system reset

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#17]
My system froze up, as a reaction to which I reset it.
When booting back up, bcachefs greeted me with
```
unreachable directory found (inum 2879383), exiting
Unable to continue, halting
bch2_fs_recovery() Error in recovery: error in fsck (1)
filesystem contains errors: please report this to the developers
bch2_fs_open() bch_fs_open err opening /dev/disk/by-partlabel/nixos-fast: fsck error
```
when trying to mount after unlocking. nixos-fast is the partition on the fast foreground-target and promote-target device.
I have refrained from mounting with fix-errors, since when I had this problem in the past and did so it would lead to a completely empty file system.

[Here](https://files.hyperfekt.net/bcachefs-dumps/fsck-error.0.qcow2) and [here](https://files.hyperfekt.net/bcachefs-dumps/fsck-error.1.qcow2) are the metadata dump files produced by the bcachefs-tools.

**Comment by hyperfekt** [comment]
I eventually used `bcachefs fsck` which reported similar problems every time it was run ("x should be y, fixing"), but the filesystem became mountable (with those problems repeated upon mount).
After another unclean shutdown (I really gotta figure out why those happen), I got a different set of problems which I'm not sure are related but led to an fsck error as well.
Running `bcachefs fsck` this time around always repeats this output when repeated:</summary>
```
journal entries 123600-123600 missing! (replaying 123600-124093), fixing
journal entries 123603-123603 missing! (replaying 123600-124093), fixing
journal entries 123606-123606 missing! (replaying 123600-124093), fixing
journal entries 123609-123609 missing! (replaying 123600-124093), fixing
journal entries 123612-123612 missing! (replaying 123600-124093), fixing
journal entries 123615-123615 missing! (replaying 123600-124093), fixing
journal entries 123618-123618 missing! (replaying 123600-124093), fixing
journal entries 123621-123621 missing! (replaying 123600-124093), fixing
journal entries 123624-123624 missing! (replaying 123600-124093), fixing
journal entries 123627-123627 missing! (replaying 123600-124093), fixing
Ratelimiting new instances of previous error
journal read done, 724371 keys in 368 entries, seq 124093
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
6 ptr gen in the future: 2 > 1, fixing
Ratelimiting new instances of previous error
Fixed gens, restarting mark and sweep:
bcachefs: libbcachefs/btree_gc.c:45: gc_pos_set: Assertion `!(gc_pos_cmp(new_pos, c->gc_pos) <= 0)' failed.
Aborted
```

`bcachefs dump` fails with the following output:
```
journal entries 123600-123600 missing! (replaying 123600-124093), exiting
Unable to continue, halting
bcachefs: bch2_fs_recovery() Error in recovery: cannot allocate memory (1)
filesystem contains errors: please report this to the developers
mount with -o fix_errors to repair
bcachefs: bch2_fs_open() bch_fs_open err opening /dev/sda1: fsck error
error opening /dev/sda1: Invalid argument
```

**Comment by koverstreet** [comment]
Eesh, that's not good.

The missing journal entries are going to be the root cause of all the other errors, we need to figure out why that's happening.

You're using multiple devices, right? Can you give me the exact bcachefs format command you used?

Very peculiar that it's every third journal entry..

**Comment by hyperfekt** [comment]
The exact format command would be `bcachefs format --compression=lz4 --background_compression=zstd --foreground_target=/dev/sda1 --background_target=/dev/sdb2 --promote_target=/dev/sda1 --encrypted --label=nixos --force /dev/sdb2 --discard /dev/sda1`.

**Comment by koverstreet** [comment]
Can you try to reproduce with discards disabled?

**Comment by hyperfekt** [comment]
I'll give it my worst ;)

**Comment by koverstreet** [comment]
The missing journal entries are just bizarre. I wrote a multi device
torture test for that, with discard enabled, and I'm not seeing it.

I think this might not be the first report of missing journal entries, so
I'd really like to get to the bottom of that one...

I have at least fixed the code that handles bucket gen issues, though.

**Comment by hyperfekt** [comment]
If that helps, I seem to only ever have encountered these kinds of issues
with hardware resets.

>

**Comment by nicman23** [comment]
@koverstreet same issue, sent you a DM in telegram :/

The worst thing is that everything worked. I just saw some corruption on a specific inode (4381) for a couple of power cycles and something about wrong bucket sizes and wanted to fsck just to be safe. On reboot it would not mount.

**Comment by hyperfekt** [comment]
I encountered this again, after another system reset (I'm thinking maybe the battery sensor is out of whack and cuts power to the system before it has had a chance to signal it to go to sleep):
`unreachable directory found (inum 919678), exiting`

This time the format command was `bcachefs format --compression=lz4 --background_compression=zstd --foreground_target=/dev/sda1 --background_target=/dev/sdb2 --promote_target=/dev/sda1 --encrypted --label=nixos --force /dev/sdb2 /dev/sda1`
Note that it is the same as before, except this time without `--discard`.

The used version of bcachefs was ea43593a9d07594e8a14eb44f9373c238a981612.

The probability of this happening after a system reset definitely seems to be above 10%, since I don't see those very often.

**Comment by hyperfekt** [comment]
Here you have a [new](https://drive.google.com/open?id=1CAZGVTUW7Sm_AIc77n8Qn2_5eNnuefP7) [dump](https://drive.google.com/open?id=1SCtq3fJS3yWNcT3LwcODgTxp8OCgBq4D), I figure the old one is encrypted.
Creating it (using  commit 894d547501fb9306ae7b1c669b66a7b49fb2205) printed this, though:
```
journal read done, 0 keys in 1 entries, seq 2504951
error validating btree node at btree 0 level 0/1
pos 529007:8 node offset 0 bset u64s 21582: invalid checksum
```
I can't recall if that happened the last time too, but I figure if it had I would've written about it.

Let me know what you want me to do to gather more data - I'll refrain from running fsck or nuking this filesystem for now. If that helps we could also try and have you SSH into my machine to do some forensics.

**Comment by koverstreet** [comment]
Are you using suspend or hibernate?

**Comment by hyperfekt** [comment]
They really didn't have to put that button right there. ^-^'

I often use suspend and it seems to work just fine.
This error occurs for me when the system goes from running normally to completely off instantly.

**Comment by koverstreet** [comment]
so, two different bugs it looks like - btree node checksum error, and unreachable directory.

The btree node that had the checksum error is in the extents btree, so it wouldn't have caused the unreachable directory - I don't see any way for them to be related.

I'll keep thinking about this one, we may need to wait for more data and a pattern to emerge.

**Comment by hyperfekt** [comment]
Mounting the filesystem with `-o fix_errors` with commit ffe09df1065dd1b326913b21381ed1ad35ab8ef9 gives
```
Mar 27 21:58:04 nixos kernel: bcachefs (8d863c45-eaed-4b3f-b209-3c06fe786add): journal read done, 0 keys in 1 entries, seq 2504951
Mar 27 21:58:16 nixos kernel: bcachefs (8d863c45-eaed-4b3f-b209-3c06fe786add): unreachable directory found (inum 919678) (run fsck to correct)
Mar 27 21:58:16 nixos kernel: bcachefs (8d863c45-eaed-4b3f-b209-3c06fe786add): error in fs gc: error -30 while deleting inode
Mar 27 21:58:16 nixos kernel: bcachefs: bch2_fs_recovery() Error in recovery: error in fsck (-30)
Mar 27 21:58:16 nixos kernel: bcachefs: bch2_fs_open() bch_fs_open err opening /dev/sda1: cannot allocate memory
```

Running `bcacefs fsck` with commit 365d3450058ba0a8d282d8155bfcc2057837ab95 gives
```
journal read done, 0 keys in 1 entries, seq 2504951
error validating btree node at btree 0 level 0/1
pos 529007:8 node offset 0 bset u64s 21582: invalid checksum
unreachable directory found (inum 919678) (run fsck to correct)
error in fs gc: error -30 while deleting inode
bcachefs: bch2_fs_recovery() Error in recovery: error in fsck (-30)
bcachefs: bch2_fs_open() bch_fs_open err opening /dev/sda1: cannot allocate memory
error opening /dev/sda1: Invalid argument
```
