### ISSUE TITLE
fs usage: not a bcachefs filesystem

### ISSUE THREAD

**Issue by davidak** [koverstreet/bcachefs#172]
even tho it is one. maybe the issue is that it's mounted?

```
[root@workstation:~]# bcachefs fs usage /dev/nvme0n1p1
error opening /dev/nvme0n1p1: not a bcachefs filesystem
```

```
[root@workstation:~]# mount
...
/dev/nvme0n1p1 on / type bcachefs (rw,noatime,errors=continue,discard)
...
```

**update**: i see it works with `bcachefs fs usage /`. it's not clear that it is intended to be used like that and the other don't work

**Comment by jpsollie** [comment]
I think it is an issue for bcachefs-tools, not bcachefs, you should it ask up there.

**Comment by davidak** [comment]
yes. feel free to move the issue
