### ISSUE TITLE
power loss causes last_seq > seq

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#174]
Every time I reset my computer with a bcachefs mounted, trying to mount that fs after fails with `invalid journal entry: last_seq > seq`. Running fsck detects and fixes a large number of instances of this error.
Commit is 0b96cd54d25c8676c400ec3ac96d4c0035d34c56, formatted with `bcachefs format --acl --reflink --encrypted compression=zstd --foreground_target=/dev/sda --background_target=/dev/sdb2 --promote_target=/dev/sda --label=nixos --force /dev/sdb2 --discard /dev/sda`.

**Comment by koverstreet** [comment]
Do you have the journal_no_flush feature enabled? (bcachefs show-super)

**Comment by hyperfekt** [comment]
I do, it seems to be by default.

**Comment by koverstreet** [comment]
Fixed by 7d57e9b703
