### ISSUE TITLE
Use of tags feature on GitHub

### ISSUE THREAD

**Issue by CodingSpiderFox** [koverstreet/bcachefs#181]
bcachefs is very interesting for me. But I still want to wait before switching.
But I also don't want to lose the project from my radar.

Watching the whole repo creates too much mails.
I'd only like to watch the releases but unfortunately the feature was last used 2017

**Comment by davidak** [comment]
The releases are mainline linux releases, so it don't makes sense to create tags in this repo. It would only make it harder to upstream the changes.

What are you waiting for? When it get upstreamed, you will probably see it in the news, like on phoronix. Before that, i wouldn't trust it with any real data.

You can test it on a test machine and report issues, so it gets stable faster.

**Comment by clonejo** [comment]
Kent Overstreet also posts update summaries on [Patreon](https://www.patreon.com/bcachefs/posts) roughly every couple of months. It's not for free, i believe the minimum monthly donation is 2 USD.

**Comment by davidak** [comment]
I'm not sure if you get new posts when you just follow. I get them even tho i don't donate anymore. I did until my paypal account had issues and i can't pay anymore. So when you don't want to donate, but get the posts by e-mail, you can just donate for 1 month and stop then. But when you can, donating is good to help the development.

**Comment by CodingSpiderFox** [comment]
> 
> 
> The releases are mainline linux releases, so it don't makes sense to create tags in this repo. It would only make it harder to upstream the changes.
> 
> What are you waiting for? When it get upstreamed, you will probably see it in the news, like on phoronix. Before that, i wouldn't trust it with any real data.
> 
> You can test it on a test machine and report issues, so it gets stable faster.

OK thanks for the hint :)
