### ISSUE TITLE
different types of data in the same bucket: data, btree

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#19]
Filesystem created with `bcachefs format --compression=lz4 --background_compression=zstd --foreground_target=/dev/sda1 --background_target=/dev/sdb2 --promote_target=/dev/sda1 --encrypted --label=nixos --force /dev/sdb2 /dev/sda1` from commit ea43593a9d07594e8a14eb44f9373c238a981612.

Boot fails with `different types of data in the same bucket: data, btree`.

Output of `bcachefs fsck` (even repeatedly) is this:
```
journal checksum bad, sector 857600: fix? (y,n) y
journal read done, 1255070 keys in 1672 entries, seq 1370513
different types of data in same bucket: data, btree
emergency read only
error invalidating buckets: -30
error invalidating buckets: -30
journal replay: error -5 while replaying key
bcachefs: bch2_fs_recovery() Error in recovery: journal replay failed (-5)
bcachefs: bch2_fs_open() bch_fs_open err opening /dev/sda1: IO error
error writing out alloc info -30
error opening /dev/sda1: Invalid argument
```

`bcachefs dump` also fails, with
```
journal checksum bad, sector 857600, exiting
Unable to continue, halting
bcachefs: bch2_fs_recovery() Error in recovery: cannot allocate memory (1)
filesystem contains errors: please report this to the developers
mount with -o fix_errors to repair
bcachefs: bch2_fs_open() bch_fs_open err opening /dev/sda1: fsck error
error opening /dev/sda1: Invalid argume
```

I tried both of those commands with both the original commit and 97d1478c44d97c72a226f659d9c981954716166f.

**Comment by koverstreet** [comment]
Fixed by 0de1d00039
