### ISSUE TITLE
bcachefs metadata_target not assigned

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#195]
when performing:
ˋˋˋ
bcachefs format -L software --group SSDM --discard /dev/disk/by-partlabel/satasoftmeta1 /dev/disk/by-partlabel/sataM2softmeta2 /dev/disk/by-partlabel/satasoftmeta3 /dev/disk/by-partlabel/sassoftmeta4 --group SSDC --discard /dev/disk/by-partlabel/nvmSoftwareCache /dev/disk/by-partlabel/sassoftcache3 --group HDD /dev/disk/by-path/pci-0000\:42\:00.0-scsi-0\:0\:0\:0 --foreground_target=SSDC --metadata_target=SSDM --background_target=HDD --promote_target=SSDC --metadata_replicas=2 --root_reserve_percent=0 --acl
ˋˋˋ
and then mounting, it seems like metadata_target is not assigned:
ˋˋˋ
# cat /sys/fs/bcachefs/3a1e64ef-bc74-4e92-8622-94173ef814b0/options/metadata_target
# cat /sys/fs/bcachefs/3a1e64ef-bc74-4e92-8622-94173ef814b0/options/foreground_target
SSDC
ˋˋˋ
not implemented yet? or a bug in bcachefs format?

**Comment by jpsollie** [comment]
I found it: it was not declared in bcachefs-tools: https://github.com/koverstreet/bcachefs-tools/pull/43
Though not sure whether the driver currently knows how to handle it

**Comment by koverstreet** [comment]
Also metadata allocations use foreground_target if metadata_target isn't specified
