### ISSUE TITLE
Does erasure coding repair file corruption

### ISSUE THREAD

**Issue by b-r-o-w-n** [koverstreet/bcachefs#198]
I create a filesystem with erasure coding enabled and then corrupt a file. The file is then not readable.
I've been lead to believe that erasure coding is parity in raid. 

kernel version: 5.10.0-ge2b8120595b8
bcachefs tool version v0.1-275-gfb2d506

Create fs
bcachefs format --erasure_code /dev/sda1 /dev/sda2 /dev/sda3

mount it
mount -t bcachefs /dev/sda1:/dev/sda2:/dev/sda3 /mnt/bcachefs1

create a small file that's easy to find on the partition.... corrupt file.... 

remount fs
mount -t bcachefs /dev/sda1:/dev/sda2:/dev/sda3 /mnt/bcachefs1
[   54.030110] bcachefs (a5598448-d7e0-496f-894e-9df68a311962): recovering from clean shutdown, journal seq 12
[   54.133973] bcachefs (a5598448-d7e0-496f-894e-9df68a311962): mounted with opts: erasure_code
[   54.134394] mount (1662) used greatest stack depth: 7840 bytes left

read file
xxd ./F0
xxd: Input/output error

dmesg
[   95.667229] bcachefs (sda1 inum 6917529027641081856 offset 0): data checksum error: expected 0:6dfad270 got 0:a8e16e7e (type 5)
[   95.667250] bcachefs (a5598448-d7e0-496f-894e-9df68a311962 inum 6917529027641081856): no device to read from
[   95.667467] bcachefs (sda1 inum 6917529027641081856 offset 0): data checksum error: expected 0:6dfad270 got 0:a8e16e7e (type 5)   

 Am I doing something wrong here?

**Comment by b-r-o-w-n** [comment]
Thanks., You are correct, 

Actually. part of the problem is there are not many examples of the format command.
Or at least that I have found.

**Comment by b-r-o-w-n** [comment]
I will give this another try when I get a format string for raid6.

**Comment by YellowOnion** [comment]
by the way, EC is unstable at the moment. Best to just use plain old redundancy for now. @b-r-o-w-n
