### ISSUE TITLE
64-bit checksum casted to 32-bit -> checksum error

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#199]
while writing data with CRC64 checksum:
```
[71060.735974] bcachefs (nvme0n1p5 inum 4035225266123964416 offset 384): data checksum error: expected 0:8344fc82 got 0:6fc65a738344fc82 (type 6)
```
it looks like the 64-bit int crc value is casted to 32-bits somewhere ...
I also saw this when playing with xxh64 algorithm
I tried to dump it with bcachefs list, but it doesn't actually show me the checksums, so no idea whether it is at read or write

**Comment by jpsollie** [comment]
By applying this patch into checksum.h:
```
@@ -132,7 +135,7 @@ static inline bool bch2_crc_cmp(struct bch_csum l, struct bch_csum r)
         * XXX: need some way of preventing the compiler from optimizing this
         * into a form that isn't constant time..
         */
-       return ((l.lo ^ r.lo) | (l.hi ^ r.hi)) != 0;
+       return ((((l.lo ^ r.lo) & 0xffffffff) | (((l.hi ^ r.hi) != 0) & 0xffffffff)));
 }
 
```
the code works flawlessly, for both crc64 and xxhash.  So at some point the 64-bit value gets casted to 32-bit, but not yet sure where it's actually going wrong.

**Comment by koverstreet** [comment]
Sounds like we might be picking the wrong size crc entry, I'd look at bch2_extent_crc_pack

**Comment by jpsollie** [comment]
problem has been fixed
