### ISSUE TITLE
error validating btree node at btree alloc level 0/1

### ISSUE THREAD

**Issue by jdgoncalves** [koverstreet/bcachefs#205]
Issue began to occur with a kernel that was compiled on March 20th, I ran into issues with the running system and rebooted to fsck the filesystem as it is the root partition. 

Attached  is the super information that is associated with they file system and and example log  file when mounted with `-o fix_errors,fsck,verbose` with commit b402057f6a9b5efeaca09c096f66d5f17c43e50b
```

Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): error validating btree node at btree alloc level 0/1
                                    u64s 11 type btree_ptr_v2 1:364634:0 len 0 ver 0: seq cd65deccf937c2a4 written 0 min_key 1:359862:0 ptr: 1:185272832 gen 30
                                    node offset 0 bset u64s 14509: keys out of order: u64s 7 type alloc 1:363947:0 len 0 ver 0 > u64s 7 type alloc_v2 1:363916:0 len 0 ver 0
Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): emergency read only
Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): error reading alloc info: -5
Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): Error in recovery: error reading allocation information (-5)
Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): shutting down
Mar 27 19:12:15 archlinux kernel: bcachefs (dcc16479-d529-40ae-ac31-3e73e610515e): shutdown complete
Mar 27 19:12:15 archlinux kernel: bcachefs: bch2_fs_open() ret -5
```
The same error occurs with bcachefs-tools when attempting to fsck or dump metadata/journal.

[Kernel-log.txt](https://github.com/koverstreet/bcachefs/files/6217942/Kernel-log.txt)
[super.log](https://github.com/koverstreet/bcachefs/files/62179)

**Comment by koverstreet** [comment]
This is troubling, this should've been caught in the write path. I wonder what went wrong.

But, fortunately it's just one key - I'll write repair code for this.

**Comment by koverstreet** [comment]
Ah, this is a single bit flip - you've got bad ram.

Checksums still should have caught this, and we validate in the write path after checksumming (unless encryption is enabled).

**Comment by koverstreet** [comment]
Kernel and tools repositories have been updated with repair code.

**Comment by jdgoncalves** [comment]
Checksums are enabled and encryption is not enabled. I reattached the super-block as it appears I initially messed up on attaching it.
[super.log](https://github.com/koverstreet/bcachefs/files/6219490/super.log)
