### ISSUE TITLE
Rebase to newer version?

### ISSUE THREAD

**Issue by YellowOnion** [koverstreet/bcachefs#209]
Is there a release schedule for rebases to new kernel versions (minor or major?)

Is there also a possibility for a patch-set to apply to a newer version? (to make things easier for upgrading up stream?)

I'm running NixOS which pulls from the 5.9 branch, which is the latest stable branch of bcachefs, but it's still on 5.9.0, when version 5.9.16 is out, which has me worried about security and other issues like performance regressions.

I think there's a regression in [linux 5.9.0](https://www.phoronix.com/scan.php?page=article&item=linux-59-fairness&num=1), that causes performance issues (stuttering audio, mouse cursor) during heavy file system copies.

It seems logical to pin bcachefs to a LTS release like 5.4 and 5.10 and not bother porting to intermediaries like 5.9 which is already EOL.

I would consider attempting to rebase but I have zero clue where to start.

**Comment by hyperfekt** [comment]
You can usually apply the entirety of bcachefs as a patchset on top of the latest minor without issues. If you use GitHub's compare tool and have or provide you a diff you don't even have to fiddle with git. Take a look [here](https://raw.githubusercontent.com/hyperfekt/nix-exp/master/config/bcachefs-support.nix).

**Comment by YellowOnion** [comment]
@hyperfekt I tried doing something similar to what you did, but my kernel would segfault/panic during stage 1, compiling just the 5.10.0 bcachefs kernel worked, is dontStrip required? Or perhaps upstream patches weren't being applied properly?

I also tried a rebase and it wouldn't compile due to an uncomprehensible make error.
