### ISSUE TITLE
newly created filesystem creates thousands of warnings on first mount

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#216]
On e455e478dd8ce2731e882b18aa921a4e7b179604, with options `--acl --encrypted --compression=zstd --foreground_target=/dev/sda --promote_target=/dev/sda --background_target=/dev/sdb2`, I get [this](https://files.hyperfekt.net/bcachefs-dumps/mark-metadata-bucket_dev-usage-update.txt) spewn into my log on the first mount, which takes considerably longer than usual.

**Comment by hyperfekt** [comment]
Still occurring on b6d54265513ceb7532e3983163338c1ad28a0284.

**Comment by hyperfekt** [comment]
Still present on ae6f512de8cdd129ce873e14eab84b8e0746daed.

**Comment by koverstreet** [comment]
Should be fixed in the testing branch
