### ISSUE TITLE
corrupt metadata before write

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#217]
On a freshly formatted filesystem using commit e455e478dd8ce2731e882b18aa921a4e7b179604, with options `--acl --encrypted --compression=zstd --foreground_target=/dev/sda --promote_target=/dev/sda background_target=/dev/sdb2` a prolonged write workload triggers the following:
<details><summary>Log</summary><pre><code>
[ 1718.077108] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67): corrupt metadata before write: error validating btree node before write at btree extents level 0/1                                                                                                        
                 u64s 11 type btree_ptr_v2 2305843009213739898:8:U32_MAX len 0 ver 0: seq 166401b397fa95c0 written 0 min_key 2305843009213739861:621841:0 ptr: 1:26822656 gen 1                                                                                           
                 node offset 168 bset u64s 2592: invalid bkey: bad size field                                                        
               u64s 5 type deleted 2305843009213739866:47968:U32_MAX len 4294967295 ver 12662972:                                    
[ 1718.077144] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67): 
[ 1718.077227] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67): emergency read only
[ 1718.077234] CPU: 1 PID: 2910 Comm: kworker/1:9 Tainted: G        W         5.10.30 #1-NixOS
[ 1718.077236] Hardware name: Dell Inc. Latitude E5470/0C8FKJ, BIOS 1.19.3 08/20/2018
[ 1718.077255] Workqueue: bcachefs bch2_write_index [bcachefs]
[ 1718.077260] Call Trace:
[ 1718.077267]  dump_stack+0x8b/0xb0
[ 1718.077280]  validate_bset_for_write+0x61/0xb0 [bcachefs]
[ 1718.077295]  __bch2_btree_node_write+0xd39/0xfb0 [bcachefs]
[ 1718.077330]  bch2_btree_init_next+0x180/0x230 [bcachefs]
[ 1718.077345]  do_bch2_trans_commit+0x3d1/0x17a0 [bcachefs]
[ 1718.077356]  ? __btree_iter_unpack+0x60/0x150 [bcachefs]
[ 1718.077372]  ? btree_iter_set_search_pos+0x503/0x5e0 [bcachefs]
[ 1718.077383]  ? __btree_iter_peek+0x19e/0x4d0 [bcachefs]
[ 1718.077397]  ? bch2_btree_iter_verify+0x47/0x90 [bcachefs]
[ 1718.077408]  ? __bch2_trans_get_iter+0x638/0x760 [bcachefs]
[ 1718.077425]  ? bch2_btree_iter_verify+0x47/0x90 [bcachefs]
[ 1718.077461]  __bch2_trans_commit+0x954/0xc40 [bcachefs]
[ 1718.077483]  bch2_extent_update+0x195/0x290 [bcachefs]
[ 1718.077503]  ? __lock_acquire+0x39f/0x1e50
[ 1718.077517]  ? reacquire_held_locks+0xde/0x200
[ 1718.077562]  ? __bch2_trans_get_iter+0x692/0x760 [bcachefs]
[ 1718.077576]  ? __btree_iter_traverse_all+0xa6/0x5c0 [bcachefs]
[ 1718.077599]  ? sched_clock+0x5/0x10
[ 1718.077603]  ? sched_clock_cpu+0xc/0xb0
[ 1718.077613]  ? six_unlock_intent+0x1a/0x40
[ 1718.077633]  bch2_write_index_default+0x1d7/0x340 [bcachefs]
[ 1718.077670]  ? bch2_write_index_default+0x74/0x340 [bcachefs]
[ 1718.077752]  ? bch2_bkey_is_incompressible+0x62/0xc0 [bcachefs]
[ 1718.077773]  __bch2_write_index+0x27f/0x360 [bcachefs]
[ 1718.077793]  bch2_write_index+0x13/0xd0 [bcachefs]
[ 1718.077798]  process_one_work+0x27b/0x580
[ 1718.077826]  worker_thread+0x4f/0x3e0
[ 1718.077846]  ? process_one_work+0x580/0x580
[ 1718.077853]  kthread+0x12f/0x150
[ 1718.077857]  ? __kthread_bind_mask+0x60/0x60
[ 1718.077864]  ret_from_fork+0x22/0x30
[ 1718.078391] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 2305843009213739866): write error -30 from btree update
[ 1718.079099] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 2305843009213739866): write error -30 from btree update
[ 1718.081018] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 6917529027641158863): write error -30 from btree update
[ 1718.081099] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 6917529027641158864): write error -30 from btree update
[ 1718.081242] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 6917529027641158865): write error -30 from btree update
[ 1718.081281] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 6917529027641158866): write error -30 from btree update
[ 1718.081283] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 107170): write error -30 from btree update
[ 1718.081329] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 107169): write error -30 from btree update
[ 1718.081340] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 107171): write error -30 from btree update
[ 1718.081355] bcachefs (b849f05e-5807-45d4-a08c-3f6befc98c67 inum 107164): write error -30 from btree update
</code></pre></details>

**Comment by hyperfekt** [comment]
Still present on ae6f512de8cdd129ce873e14eab84b8e0746daed.

**Comment by koverstreet** [comment]
Fixed by 0cd3e1d27a
