### ISSUE TITLE
data target flags may be incorrectly set

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#232]
I think the flags of "which device contains which data?" are not set appropriately:
dev-5 is foreground + background data
dev-1 is metadata
dev-0 is background data

```
linuxserver ~ # cat /sys/fs/bcachefs/f746d471-ffb0-4956-89d4-99d08d863e81/dev-5/has_data
journal,user,cached
linuxserver ~ # cat /sys/fs/bcachefs/f746d471-ffb0-4956-89d4-99d08d863e81/dev-1/has_data
journal,btree,user,cached
linuxserver ~ # cat /sys/fs/bcachefs/f746d471-ffb0-4956-89d4-99d08d863e81/dev-0/has_data
journal,user
```
why does dev-1 contain cached/user data? it's supposed to be used for metadata only! (as I made an SSD raid of them to be able to browse the filesystem before accessing the files)

**Comment by dlrobertson** [comment]
I could be misunderstanding things, but what mount flags did you use? Per https://github.com/koverstreet/bcachefs/issues/223 target mount options are likely not set properly.

**Comment by jpsollie** [comment]
current mount options in fstab:
`noatime,user,nofail,noauto,fix_errors`

**Comment by koverstreet** [comment]
I think we may be able to get rid of this superblock field - it predates disk space accounting by replica sets.

**Comment by jpsollie** [comment]
fixed by @koverstreet
