### ISSUE TITLE
BCacheFS 5.0 rebase fails to build ~ failure on building drivers/staging/media/ipu3/ipu3-dmamap.c

### ISSUE THREAD

**Issue by Valmar33** [koverstreet/bcachefs#26]
I get this error with building the BCacheFS 5.0 rebase, but not from the 5.0 kernel, with or without the stable patches:

[kernel error.log](https://github.com/koverstreet/bcachefs/files/3042584/kernel.error.log)

I use this kernel config file for both (.txt extension because GitHub complains, otherwise):

[config.txt](https://github.com/koverstreet/bcachefs/files/3042598/config.txt)

**Comment by Valmar33** [comment]
Not really sure where to begin with bisecting. :/

**Comment by koverstreet** [comment]
Fix is pushed

**Comment by Valmar33** [comment]
Cool, thanks. :)
