### ISSUE TITLE
`make modules` fails ~ "bio_iov_iter_get_pages" undefined

### ISSUE THREAD

**Issue by Valmar33** [koverstreet/bcachefs#27]
Error output:

    ERROR: "bio_iov_iter_get_pages" [fs/bcachefs/bcachefs.ko] undefined!
    make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1
    make: *** [Makefile:1264: modules] Error 2

**Comment by eadwu** [comment]
I don't think this regression is present in 5.0 but in the current stable. Anyway you probably want to revert this [1].

[1] https://github.com/torvalds/linux/commit/0374e1132217711bc2e920cde877dd7fc3dbd2d9

**Comment by Valmar33** [comment]
Yeah, it's present in 5.0.0, unfortunately, according to that commit.

**Comment by Valmar33** [comment]
It builds fine when I revert that commit. :)

**Comment by koverstreet** [comment]
Yeah, reverted that.
