### ISSUE TITLE
copygc taking a long time with no effect

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#280]
Using a filesystem on 1a510b0 with encryption, ACLs, reflinks, zstd compression, and separate foreground/promote and background devices, that has a number of bad blocks, bcachefs will regularly report `copygc finished but 91615/91615 sectors, 18401/18401 buckets not moved (move stats: moved 0 sectors, raced 0 keys, 0 sectors)` (numbers varying but always 100% not moved and 0 for the move stats), and pretty consistently keep one core pinned at 100%.

The `stack` file in procfs is empty, but `perf` reports <details><summary>this distribution:</summary><pre><code>36,24%  bch-copygc/0a1e  [kernel.kallsyms]  [k] copygc_pred 
8,00%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_iter_verify_locks 
6,72%  bch-copygc/0a1e  [kernel.kallsyms]  [k] btree_iter_set_search_pos 
6,53%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_extent_crc_unpack 
6,45%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_iter_peek
5,89%  bch-copygc/0a1e  [kernel.kallsyms]  [k] btree_cache_find  
4,05%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __bch2_move_data  
3,72%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_iter_verify 
2,58%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __bch2_bkey_cmp_left_packed  
1,77%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_iter_verify_entry_exit▒
1,55%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __bch2_btree_node_iter_advance▒
1,38%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_varint_decode
1,15%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_bkey_unpack  
1,14%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __btree_iter_unpack 
0,92%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_bkey_nr_ptrs_allocated  
0,85%  bch-copygc/0a1e  [kernel.kallsyms]  [k] debug_lockdep_rcu_enabled 
0,78%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __x86_retpoline_rax 
0,65%  bch-copygc/0a1e  [kernel.kallsyms]  [k] btree_iter_prefetch 
0,57%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_inode_unpack 
0,56%  bch-copygc/0a1e  [kernel.kallsyms]  [k] lock_acquire
0,48%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_iter_advance
0,46%  bch-copygc/0a1e  [kernel.kallsyms]  [k] lock_release
0,37%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_node_iter_advance 
0,34%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __x86_indirect_thunk_rax  
0,31%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __bch2_trans_get_iter  
0,28%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_bkey_ptrs_c  
0,27%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_node_prefetch  
0,17%  bch-copygc/0a1e  [kernel.kallsyms]  [k] kthread_should_stop 
0,16%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_node_iter_init 
0,15%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_opts_to_inode_opts
0,15%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_copygc 
0,07%  bch-copygc/0a1e  [kernel.kallsyms]  [k] generic_swap
0,07%  bch-copygc/0a1e  [kernel.kallsyms]  [k] eytzinger0_sort
0,05%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_trans_iter_put 
0,05%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bucket_offset_cmp 
0,05%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_btree_node_get 
0,04%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_io_opts_apply
0,03%  bch-copygc/0a1e  [kernel.kallsyms]  [k] rcu_read_unlock_strict 
0,02%  bch-copygc/0a1e  [kernel.kallsyms]  [k] i8042_interrupt
0,02%  bch-copygc/0a1e  [kernel.kallsyms]  [k] six_trylock_read  
0,02%  bch-copygc/0a1e  [kernel.kallsyms]  [k] six_unlock_read
0,02%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_bkey_pack_pos_lossy  
0,02%  bch-copygc/0a1e  [kernel.kallsyms]  [k] do_raw_spin_trylock 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] six_relock_read
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] native_write_msr  
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de01059036
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de0105902b
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de0105900c
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de0105901b
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] native_irq_return_iret 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] btree_iter_traverse_one
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] bch2_bkey_cmp_packed
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] read_tsc 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] timekeeping_advance 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de1ab3800c
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] timerqueue_add 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de1ab38025
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de1ab38031
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] hrtimer_interrupt 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] ahci_single_level_irq_intr
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __bch2_bkey_cmp_packed_format_checked  ▒
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] pvclock_gtod_notify 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] trigger_load_balance
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] 0x000028de1ab38018
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] perf_event_task_tick
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] update_curr 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] native_read_msr
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __update_load_avg_se
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] __hrtimer_run_queues
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] rcu_sched_clock_irq 
0,01%  bch-copygc/0a1e  [kernel.kallsyms]  [k] ahci_handle_port_interrupt</code></pre></details>

**Comment by PythonNut** [comment]
This looks similar to #261 and #274

**Comment by hyperfekt** [comment]
Thanks, they do indeed look very similar! I had assumed I was the only one to hit this without searching because it was seemingly triggered by bad blocks.

**Comment by hyperfekt** [comment]
Not observed anymore.
