### ISSUE TITLE
Very long filename limitation

### ISSUE THREAD

**Issue by caadar** [koverstreet/bcachefs#3]
In some setups there are need to increase NAME_MAX (see e.g. https://www.spinics.net/lists/linux-ext4/msg10172.html or https://github.com/zfsonlinux/zfs/issues/2344).

Is it safe with Bcachefs? What is the maximal limit of NAME_MAX?

Let's test.

1. Increase value in the kernel (include/uapi/linux/limits.h):
`````
#define NAME_MAX               1023 	/* # chars in a file name */
`````

2. Start primitive test:
`````
i=1; n="1"; while touch $n 2> /dev/null; do n="1$n"; i=$(($i + 1)); done; echo $i
`````
=> 1035

 (Looks OK, but 1024 expected.)

And log's chunk:

`````
May 30 17:44:53 localhost kernel: [  843.197180] bcachefs (sdd2): invalid key in journal: dirent name too big
May 30 17:44:53 localhost kernel: [  843.197180] u64s 39 type 128 4096:8591153449688515752 snap 0 len 0 ver 0: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111, exiting
May 30 17:44:53 localhost kernel: [  843.197182] bcachefs (sdd2): Unable to continue, halting
May 30 17:44:53 localhost kernel: [  843.197189] bcachefs (sdd2): emergency read only
`````

BTW, mount command shows ```/dev/sdd2 on /mnt/mnt type bcachefs (rw,relatime)``` i.e. read-write status.

**Comment by caadar** [comment]
Now it seems pretty fine:

```i=1; n="1"; while touch $n 2> /dev/null; do n="1$n"; i=$(($i + 1)); done; echo $i```

=> 1992

Log is clean.

**Comment by koverstreet** [comment]
Yeah fixed it, just hadn't gotten around to fixing the bug :)

Also not relying on NAME_MAX anymore, as you probably noticed.

**Comment by beedell-roke** [comment]
@koverstreet, does this mean that BCacheFS can safely exceed <del>`PATH_MAX`</del> `NAME_MAX`?

**Comment by koverstreet** [comment]
PATH_MAX is for paths, not filenames, and that's more of a VFS thing.

The max length of a bcachefs filename used to be NAME_MAX * 2 (IIRC), but we lowered it when introducing casefolding.

And the "safety" issues were mostly a combination of old C code and trying to put a limit on how much kernel memory userspace can pin, they're less applicable today.

**Comment by beedell-roke** [comment]
@koverstreet, apologies; I typed the wrong variable.

> The max length of a bcachefs filename used to be `NAME_MAX * 2` (IIRC), but we lowered it when introducing casefolding.

Is the reason for this limit documented? I'm attempting to ascertain why it's limited at all.
