### ISSUE TITLE
upgrade to snapshot-enabled bcachefs ruined all checksums

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#331]
Command which was used to format the disks:
`bcachefs format -L multimedia --inodes_32bit --data_checksum=xxhash --metadata_checksum=xxhash --root_reserve_percent=0 --group HDD /dev/disk/by-id/scsi-23355e35b00d00000 --group SSDM --discard /dev/disk/by-partlabel/satamultmeta1 /dev/disk/by-partlabel/sataM2multmeta2 /dev/disk/by-partlabel/satamultmeta3 /dev/disk/by-partlabel/sasmultmeta4 --group SSDC --discard /dev/disk/by-partlabel/satammcache1 /dev/disk/by-partlabel/nvmMMCache /dev/disk/by-partlabel/sasmmcache3 --foreground_target=SSDC --metadata_target=SSDM --background_target=HDD --promote_target=SSDC --metadata_replicas=2`

After moving from pre-snapshot code to snapshot code, this disk failed.  While the files are still visible (so I assume metadata is ok), any file access gives a checksum error (you can see this in dmesg log)
the bcachefs filesystem we're talking about is aa7411b1-8276-4b8a-bd42-3f0441f2b238, others upgraded without an issue.

I also added the output of 
`bcachefs fsck -p -f --reconstruct_alloc` 
as an attachment.  Running the command multiple times gives a similar output.
The bcachefs version used here is `bcachefs tool version v0.1-417-gabd9d5b`
[dmesg.txt](https://github.com/koverstreet/bcachefs/files/7520685/dmesg.txt)
[fsck.zip](https://github.com/koverstreet/bcachefs/files/7520701/fsck.zip)
For people whose knowledge about bcachefs internal data structures are far beyond mine, also bcachefs list & list_journal output (xz compressed txt file, wrapped inside zip as github requires it):
[list_journal.txt.xz.zip](https://github.com/koverstreet/bcachefs/files/7520832/list_journal.txt.xz.zip)
[list.txt.001.zip](https://github.com/koverstreet/bcachefs/files/7520859/list.txt.001.zip)
[list.txt.002.zip](https://github.com/koverstreet/bcachefs/files/7520863/list.txt.002.zip)
[list.txt.003.zip](https://github.com/koverstreet/bcachefs/files/7520865/list.txt.003.zip)
*edit: 7-zip made a .zip.001, .zip.002 and .zip.003, I swapped the number / extension to make it be accepted by github, but it may be swapping it back is neccessary

Any help here? The latest backup I have of this device is a few days before, I'd like to get the files back.  I don't care if I have to reformat everything afterwards, but having those data back would be nice

**Comment by koverstreet** [comment]
From the dmesg log, this is the machine you're running xxhash on.

--reconstruct_alloc was _definitely_ not something you wanted to run for this, and may have broken things worse.

I don't think this had anything to do with the snapshots upgrade, most likely something about the 5.13 - 5.15 upgrade broke xxhash - or upstream kernel changed something about the xxhash implementation on us and broke it.

I'm going to take out xxhash so this doesn't break anyone else.

As far as getting your data back, you'll have to edit the source code to disable the checksum checks.
