### ISSUE TITLE
dkms release for more automated maintenance

### ISSUE THREAD

**Issue by brainchild0** [koverstreet/bcachefs#339]
I understand that a wish has been expressed for  broader experimentation with `bcachefs`.

Naturally, the effort currently required for deployment is an obstacle  against wider  use, even while such more widespread deployment might facilitate eventual adoption into the main kernel.

I little doubt the question has arisen before, but having found no public discussion through basic searches, I wondered about the feasibility of releasing a DKMS version. Especially applied in conjunction with distribution package managers, DKMS offers a means for installation  of non-standard kernel modules  requiring extremely little manual maintenance.

Is a DKMS release possible in principle, and if so, has it been considered?

**Comment by koverstreet** [comment]
Not feasible, bcachefs requires patches to core kernel code

**Comment by brainchild0** [comment]
Is there any chance the patches might be accepted into the main kernel, without the support for the full file system, then allowing the full file system  to be offered  in module form?

**Comment by mmoya** [comment]
Link to LWN's [Merging bcachefs](https://lwn.net/Articles/934692/) that has useful contextual information on merging status.

**Comment by iHad168** [comment]
I today finded bcachefs-dkms-git package on Arch linux
https://aur.archlinux.org/packages/bcachefs-dkms-git

But
```
[🔴] × sudo dkms install bcachefs/6.5.0.r2787.gefd200a
Sign command: /usr/lib/modules/6.5.2-zen1-1-zen/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Error! The /var/lib/dkms/bcachefs/6.5.0.r2787.gefd200a/6.5.2-zen1-1-zen/x86_64/dkms.conf for module bcachefs includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
```

```
==> dkms install --no-depmod bcachefs/6.5.0.r2787.gefd200a -k 6.5.2-zen1-1-zen
Error! The /var/lib/dkms/bcachefs/6.5.0.r2787.gefd200a/6.5.2-zen1-1-zen/x86_64/dkms.conf for module bcachefs includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
==> WARNING: `dkms install --no-depmod bcachefs/6.5.0.r2787.gefd200a -k 6.5.2-zen1-1-zen' exited 77
```

/usr/src/bcachefs-6.5.0.r2787.gefd200a/dkms.conf
```
PACKAGE_NAME="bcachefs"
PACKAGE_VERSION="6.5.0.r2724.g493c276"
BUILT_MODULE_NAME[0]="bcachefs"
BUILT_MODULE_LOCATION[0]="src/fs/bcachefs"
DEST_MODULE_LOCATION[0]="/kernel/fs/bcachefs"
BUILD_EXCLUSIVE_KERNEL="6\.5"
BUILD_EXCLUSIVE_CONFIG="CONFIG_CLOSURES CONFIG_MEAN_AND_VARIANCE"
AUTOINSTALL="yes"
```
