### ISSUE TITLE
disk hang when delete snapshots

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#341]
As the disk usage is not enough ,I want to delete snapshots to get more disk space. I have 10+ snapshots now in the filesystem. When I delete one or more , "bcachefs subvolume delete" command hangs , the disk in high IOPS .Finanlly the whole desktop hang ,I can not do anything ,even to swith terminal to see dmesg. The disk LED stop twinkling. I have to hard reboot the PC. And the disk space seeems not be released after restarting , the snapshot does be deleted.
[1640871325.txt](https://github.com/koverstreet/bcachefs/files/7795083/1640871325.txt)

**Comment by koverstreet** [comment]
It appears bch2_evict_subvolume_inodes() needs work.

In your dmesg log, after you rebooted, do you see a line about "restarting deletion of dead snapshots"? There's a background task that has to run to reclaim space after deleting snapshots.

**Comment by bhzhu203** [comment]
> It appears bch2_evict_subvolume_inodes() needs work.
> 
> In your dmesg log, after you rebooted, do you see a line about "restarting deletion of dead snapshots"? There's a background task that has to run to reclaim space after deleting snapshots.

No,I can not find the line after rebooting, neither at mount time .
[1640917534.txt](https://github.com/koverstreet/bcachefs/files/7795162/1640917534.txt)

**Comment by bhzhu203** [comment]
updated to version 7c05f28521c6d6ed3c8fb3892776d775297751a8 

There are many "bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!" messages in dmesg. The disk has much read often.

```
[30747.883173] bch2_copygc: 826 callbacks suppressed
[30747.883175] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.888336] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.893425] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.898528] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.903570] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.908587] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.913558] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.918633] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.923683] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
[30747.928744] bcachefs (e5efb599-5285-48ad-a21c-c148d342e273): copygc requested to run but found no buckets to move!
```

[1641261035.txt](https://github.com/koverstreet/bcachefs/files/7804888/1641261035.txt)

**Comment by bhzhu203** [comment]
updated to version 50ac18afbb522a3103cecff9aaf9519d4eb5e908

After delete 10+ snapshots ,the bcachefs command do not hang anymore and the diskspace did reclaimed.

But the bch-copygc/0000 process  keep runing out of one CPU core , some other processes/threads(firefox) not working well(laging).
[1641369480.txt](https://github.com/koverstreet/bcachefs/files/7813113/1641369480.txt)
![2022-01-05_15-27](https://user-images.githubusercontent.com/3523160/148182810-2a68be8c-877a-4f02-99a9-f4412e04cbb6.png)
![2022-01-05_15-32](https://user-images.githubusercontent.com/3523160/148182814-3a32e90f-2da4-4bc5-8200-2a48b6b94f6b.png)

**Comment by bhzhu203** [comment]
updated to be0da59 (bcachefs: New data structure for buckets waiting on journal commit)
The disk not lag anymore ,disk read OPS becomes normal (droping).But still 100% CPU of bch-copygc/0000 in one core.

**Comment by koverstreet** [comment]
copygc spinning and using excessive CPU is going to be an issue until I get backpointers done.

Which is coming...

**Comment by bhzhu203** [comment]
> copygc spinning and using excessive CPU is going to be an issue until I get backpointers done.
> 
> Which is coming...

Ok ,thank you . the version 644ffd747d5ed096a980e71086bff313b0ac70ba is more stable now

**Comment by bhzhu203** [comment]
updated to 02174e13101cdc4c6bda1a0d72d64608074d6661

After mounted disk for 10 seconds ,the whole system panic and lost response , I can not get the dmesg . I have tried for 3 times , it is the same.

vesion d9b3fe55be51bdcda48b8b27804bbd7d60bdd31c is good

**Comment by bhzhu203** [comment]
updated to bf340e68c74cdb70c692698ef7367b9dc6f6e61f 

I enter the filesystem for a long time(20m+) now . It is more smooth than before.

But there is a chance(near 100% after about 15m~20m+) to trigger a panic (which I can not get the dmesg ,whole system hanged ) ,when click something in the Desktop enviroment

**Comment by bhzhu203** [comment]
> updated to [bf340e6](https://github.com/koverstreet/bcachefs/commit/bf340e68c74cdb70c692698ef7367b9dc6f6e61f)
> 
> I enter the filesystem for a long time(20m+) now . It is more smooth than before.
> 
> But there is a chance(near 100% after about 15m~20m+) to trigger a panic (which I can not get the dmesg ,whole system hanged ) ,when click something in the Desktop enviroment

I have got the dmesg when the disk hanged

```
❰bhzhu❙~/source/bcachfs-github/bcachefs(git≠master)❱✘≻ 
scripts/faddr2line  /lib/modules/bcachefs.ko-20220111-1-bad  bch2_set_bucket_needs_journal_commit+0x119/0x310
bch2_set_bucket_needs_journal_commit+0x119/0x310:
bch2_set_bucket_needs_journal_commit 于 /home/bhzhu/source/bcachfs-github/bcachefs/fs/bcachefs/buckets_waiting_for_journal.c:111 (discriminator 2)
❰bhzhu❙~/source/bcachfs-github/bcachefs(git≠master)❱✔≻ scripts/faddr2line  /lib/modules/bcachefs.ko-20220111-1-bad  __bch2_trans_init+0xb5/0x150
__bch2_trans_init+0xb5/0x150:
__list_add 于 /home/bhzhu/source/bcachfs-github/bcachefs/./include/linux/list.h:70
(已内连入)list_add 于 /home/bhzhu/source/bcachfs-github/bcachefs/./include/linux/list.h:86
(已内连入)__bch2_trans_init 于 /home/bhzhu/source/bcachfs-github/bcachefs/fs/bcachefs/btree_iter.c:3043
```

[1641902025.txt](https://github.com/koverstreet/bcachefs/files/7846540/1641902025.txt)

**Comment by bhzhu203** [comment]
the version f1f72491d1eefd0f3a64c2c59411e443c2cf26fd still panic , the kdump in my system not setup correctly . I can not get the dmesg

**Comment by bhzhu203** [comment]
I have used the method of bisection to find the bad commit in 0f60abf72ad85dcfb1acce77c432de9126a5d0c4 to e352802093dd040ccfb126ecaeea7fa9a8b8fed4 
@koverstreet

**Comment by bhzhu203** [comment]
0f60abf72ad85dcfb1acce77c432de9126a5d0c4 does not trigger the whole system hang , but sometimes trigger processes hang.

```
scripts/faddr2line /lib/modules/5.15.0-uksm+/kernel/fs/bcachefs/bcachefs.ko bch2_set_bucket_needs_journal_commit+0x119/0x310
bch2_set_bucket_needs_journal_commit+0x119/0x310:
bch2_set_bucket_needs_journal_commit at /home/bhzhu/source/bcachfs-github/bcachefs/fs/bcachefs/buckets_waiting_for_journal.c:111 (discriminator 2)

```

**Comment by bhzhu203** [comment]
> I have used the method of bisection to find the bad commit in [0f60abf](https://github.com/koverstreet/bcachefs/commit/0f60abf72ad85dcfb1acce77c432de9126a5d0c4) to [e352802](https://github.com/koverstreet/bcachefs/commit/e352802093dd040ccfb126ecaeea7fa9a8b8fed4) @koverstreet
> 
> the second stage is [0f60abf](https://github.com/koverstreet/bcachefs/commit/0f60abf72ad85dcfb1acce77c432de9126a5d0c4)(good) to [6bd2a20](https://github.com/koverstreet/bcachefs/commit/6bd2a203c11fd09dc9563e4c7e93036aab9545d6)
> 
> the 3th stage is [0f60abf](https://github.com/koverstreet/bcachefs/commit/0f60abf72ad85dcfb1acce77c432de9126a5d0c4)(good) to [3e29f2a](https://github.com/koverstreet/bcachefs/commit/3e29f2a5c29648191481fbef9e44330b5dcd233c) the version [3e29f2a](https://github.com/koverstreet/bcachefs/commit/3e29f2a5c29648191481fbef9e44330b5dcd233c) panic . So the bad commit is [3e29f2a](https://github.com/koverstreet/bcachefs/commit/3e29f2a5c29648191481fbef9e44330b5dcd233c)
> 
> I open the firefox and clicked it randomly then the whole system hanged .
> 
> ![Firefox_Screenshot_2022-01-12T14-14-33 207Z](https://user-images.githubusercontent.com/3523160/149156844-312a1fdd-d8cf-4a78-87d7-47894cddefb5.jpg)

The system still hang (maybe panic , can not get the dmesg) in 24309e2e9f2f8c818cd58b9950fc198375c775aa .
Because the bad commit 82a17b55350c65f9af63786d0a5e51678d7af367 exists .
