### ISSUE TITLE
The bcachefs still panic in the latest version

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#352]
The system still hang (maybe panic , can not get the dmesg) in 24309e2e9f2f8c818cd58b9950fc198375c775aa .
Because the bad commit 82a17b55350c65f9af63786d0a5e51678d7af367 exists .

related in #341

**Comment by Madouura** [comment]
Can confirm.

**Comment by bhzhu203** [comment]
updated to f76e97e4ef2ef12027087a17dac89b3438730a6c  , after working well for 2 hours , when I downloaded a pic from firefox , the system panic and hang.

The bad commit "bcachefs: iter->update_path" should be dealed with
