### ISSUE TITLE
Linux executable binary files  read corruption

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#357]
many execute binary files runing failed in the bcachefs disk in version 7d0925084b6927ad8c631bde92fb1c41cc6270c2
The cinnamon desktop Enviroment startup error and some settings seems to be error

'''
./firefox
bash: ./firefox: cannot execute binary file: Exec format error
'''

mounting the filesystem 
'''
[ 4291.839048] bcachefs (00000000c0634e7a): recovering from clean shutdown, journal seq 2255293
[ 4296.217905] bcachefs (00000000c0634e7a): going read-write
[ 4296.219710] bcachefs (00000000c0634e7a): error creating gc thread: -4
[ 4296.219712] bcachefs (00000000c0634e7a): error starting gc thread
[ 4322.681470] bcachefs (000000004b1ee5ab): recovering from unclean shutdown
[ 4468.111361] bcachefs (000000004b1ee5ab): journal read done, 0 keys in 1 entries, seq 2255295
[ 4472.524304] bcachefs (000000004b1ee5ab): journal replay done
[ 4532.672503] bcachefs (000000004b1ee5ab): going read-write
[ 4532.681538] bcachefs (000000004b1ee5ab): mounted with opts: compression=lz4,foreground_target=cache,background_target=back,promote_target=prom,noinodes_use_key_cache,nojournal_transaction_names
[ 4532.681936] mount (10380) used greatest stack depth: 10168 bytes left
'''

when umount the filesystem:
bcachefs (000000004b1ee5ab): error 1 from bch2_move_data() in copygc

**Comment by bhzhu203** [comment]
updated to 9d554fa16def4f6310d2df74092c5568419e69e3  still the same .
many file read corruption


'''
bhzhu@bhzhuos /m/b/s/b/bcachefs> git status
error: bad signature 0x00000000
fatal: index file corrupt

bash-4.3$ /mnt/bhzhu/gocryptfs
bash: /mnt/bhzhu/gocryptfs: cannot execute binary file: Exec format error
bash-4.3$ /mnt/bhzhu/firefox/firefox
bash: /mnt/bhzhu/firefox/firefox: cannot execute binary file: Exec format error
'''

'''
[13270.312400] bcachefs (000000001ded2859): error 1 from bch2_move_data() in copygc
[13326.364768] bcachefs (000000007504deec): recovering from clean shutdown, journal seq 2258168
[13330.768120] bcachefs (000000007504deec): going read-write
[13330.770051] bcachefs (000000007504deec): mounted with opts: compression=lz4,foreground_target=cache,background_target=back,promote_target=prom,noinodes_use_key_cache,nojournal_transaction_names
'''


version f76e97e4ef2ef12027087a17dac89b3438730a6c can read files Correctly ,but the panic issue exists  #352

**Comment by bhzhu203** [comment]
"Linux executable binary files read corruption"  issue solved in 79b1c2e3ed094400df0244f6c08e34bcb77cfcda

I start format a brand new bcachefs , a single device , open option  compress:lz4 ; backgrand_compress:lz4

using rsync copy my btrfs home directory  data (3000000+ files , 176G )  to bcachefs directory ,   when reaching 80G bcachefs , the whole system panic . Everytime I want to continue rsync , the whole system panic in 5mins again and again

**Comment by koverstreet** [comment]
Did you get the log?

**Comment by bhzhu203** [comment]
Good news : I have update to version e318fabeb424d4b8fdd46329125c30aaa4f9006a , then I can do the disk rsync copy completely. And I have using bcachefs for several days , there is no panic issue .

More stable now. But the "bch-rebalance/s" process often runing in the backgroud ,sometimes laging. The good thing is the "bch-rebalance/s"  not using full of the disk read bandwidth

**Comment by bhzhu203** [comment]
Unfortunately,after 2 hours I was writing the feedback , The system panic.

I had deleted tons of small files :

rm -rvf  ~/.cache/fontconfig/*

deleting faild ,out of the list.So I using the rsync to delete

rsync -avP --delete  ~/null/ ~/.cache/fontconfig/


At this time, the system was not painc yet.

Finally I search the bookmark in the firefox,trying poping out a new window,the whole system panic.

Maybe firefox stores many small files in the disk. Deleting and creating often.


Then I reboot the system ,mounting the disk ,when entering the Cinannom desktop , the system panic immediately.
I have to mount the disk in other system , let the bcachefs  "bch-rebalance/s" runing completed (iotop -o showing no active process).

The FS becomes normal now.

**Comment by koverstreet** [comment]
Are you using snapshots? I just fixed several transaction path overflows when using snapshots

**Comment by bhzhu203** [comment]
> Are you using snapshots? I just fixed several transaction path overflows when using snapshots

Yes I am using snapshots. @koverstreet 

This version is 62cdb94d54b37e9e1fb8c73d1fe2b8ab35a88d2f now. Quite stable when doing rsync and using Firefox browser . I have keept/test this version nearly for a week , not experienced any panic issue this version yet.

But I find some performance issues:
1. When the disk mounted , "bch-rebalance/s" process will run for about 5mins. At this time ,the desktop is laging. The good thing is that "bch-rebalance/s" seems be limited at disk bandwidth , not runing out of the disk read bandwidth after hours using.

2.Bcachefs performance drops than before. Virtualbox Windows10 vm on Bcachefs:

tested at 2021.11.15
![as-ssd-bench VBOX HARDDISK 2021 11 15 9-44-49](https://user-images.githubusercontent.com/3523160/158997274-0c545dee-7da7-426e-9465-fed7bbab6f52.png)


tested at 2022.3.3
![as-ssd-bench VBOX HARDDISK 2022 3 3 17-48-41](https://user-images.githubusercontent.com/3523160/158997355-e54a7671-7e5f-417d-8c97-7209c262d63a.png)

I will continue test more snapshots on the latest version .Thanks

**Comment by bhzhu203** [comment]
> Was this actually fixed?

Yes, It is more stable now.  using the version=new_data_types .  But there is  slow/low HDD disk random read IOPS  with many snapshots issue 

https://github.com/koverstreet/bcachefs/issues/387
@koverstreet
