### ISSUE TITLE
Feature request: bcachefs volumes

### ISSUE THREAD

**Issue by DemiMarie** [koverstreet/bcachefs#360]
There are several use-cases, such as virtualization and iSCSI, for which a block device is as useful, if not more useful, than a file system.  Of course, one can use a regular file with a loop device, but loop devices are slow.

Obviously, you are under no obligation to implement this, but when bcachefs gets upstreamed I could see this feature being useful in Qubes OS.

**Comment by koverstreet** [comment]
Loopback has an O_DIRECT mode now, which is fast.

**Comment by DemiMarie** [comment]
> Loopback has an O_DIRECT mode now, which is fast.

Interesting!  I had seen that mode, but I was not aware it was fast.  Last I checked it still created a kernel thread for I/O operations, and many people did not recommend loop devices for production use.  There was talk of a faster dm-loop driver but it never materialized.

**Comment by colttt** [comment]
duplicate of #164

**Comment by DemiMarie** [comment]
yeah, whoops :)
