### ISSUE TITLE
multi-tiered filesystem does not organize properly

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#361]
On a server with 2 bcachefs filesystems:

Each filesystem has 3 groups: HDD (background storage), SSDC (Caching storage), and SSDM (metadata storage).

I saw something interesting in the output of "fs usage".  To make sure this was not a temporary issue, I ran "fsync", and "data rereplicate" on the filesystem + verified in top there was no process waiting for IO:

[output1.txt](https://github.com/koverstreet/bcachefs/files/8122405/output1.txt)
[output2.txt](https://github.com/koverstreet/bcachefs/files/8122407/output2.txt)

Interesting, isn't it?
The first filesystem hosts user data on 3 devices, even after data rereplicate, and the second doesn't.
To make it even more interesting:
The second filesystem was actively being used at that time (a few network clients having SMB connections on this fs), but had nothing cached, while the first one was not...

**Comment by YellowOnion** [comment]
Can you clarify what is so interesting?

**Comment by jpsollie** [comment]
when a filesystem is being used (= remote SMB connection), you'd expect to have something cached.  Here, there is no caching at all on the second filesystem

**Comment by YellowOnion** [comment]
I'm having trouble understanding what I'm looking at because the numbers are rather big (you can use `-h` to humanise), but caching isn't always distinct from other data types, is there an inconsistently between the use of `foreground` and `promote` in both your fs'?

**Comment by jpsollie** [comment]
fs no longer available. closing bug
