### ISSUE TITLE
trans path overflow during rereplication

### ISSUE THREAD

**Issue by mBornand** [koverstreet/bcachefs#373]
Hello,

Each time i'am doing `bcachefs data rereplicate /` the kernel panics

it first happened after i changed replica metadata_replica count to 2 and run rereplicate.

It was last tested with `f67089dc9b3d` and I got this:

![IMG_20220305_195522](https://user-images.githubusercontent.com/63592189/156897058-f760fb95-eba6-47b4-8b9e-606d3ea3736b.jpg)

Afterwards I sometimes need to run fsck to repair.

Sometimes the kernel also just panics while a task is running.

**Comment by mBornand** [comment]
I don't know if it helps, but I have tried with commit `2943928673` and it  panics to.

**Comment by koverstreet** [comment]
I think this should be fixed now - can you give the latest commit a try?

**Comment by mBornand** [comment]
commit `fa2970b41c9c6` worked

thank you

In fs/bcachefs/btree_iter.c there is a probably typo, oveflow should probably by overflow in trans path overflow.
