### ISSUE TITLE
Mounting encrypted filesystems seemingly broken by UUID format string specifier change

### ISSUE THREAD

**Issue by JJJollyjim** [koverstreet/bcachefs#374]
I have been attempting to debug the `-126`/ENOKEY [issue](https://www.reddit.com/r/bcachefs/comments/syo440/encryption_problem_with_yesterday_pull_unable_to/) when mounting an encrypted filesystem (which I have experienced both in a QEMU-based NixOS integration test, and on bare-metal on Arch Linux), using the commit 8ffb42b3d09418642680d23401a7a71d6ff87e3a (more recent ones not tested).

I have bisected the issue down to 45837110a361f1900566377e8c92935e8bf19bec "bcachefs: Log & error message improvements", and confirmed that reverting the commit fixed the issue.

I suspect the issue is related to the use of the wrong format string specifier – the commit switches from `%pUb` to `%plU`. For one thing, I'm not sure if the endianness change is intentional. For another, if little-endianness is indeed correct, the docs I can see say that the endianness-specifier should be after the U (`%pUl`) – as it was before.

Hopefully that helps narrow down the issue – I suspect the TPM theory as you said on reddit (or TFM on GitHub, which I assume was a mistake?) is a red herring.

**Comment by JJJollyjim** [comment]
Kicking off test runs based on the latest master with each of `pUb`/`pUl`/`pU`, will post results when I wake up.

**Comment by koverstreet** [comment]
Nice job tracking this down - thanks!

We just need to be printing UUIDs out the same way kernel side and in userspace, which it appears we were doing already - my bad on changing that.

Will fix tomorrow...

**Comment by koverstreet** [comment]
Can you confirm the fix I just pushed?

**Comment by JJJollyjim** [comment]
Yep, that solves it, thanks!

**Comment by Madouura** [comment]
@koverstreet Seem to have a similar problem to this as of at least c38b7167aa5f3b1b91dcc93ade57f30e95064590, the current commit NixOS is on.
I can make an encrypted system, but only with ``--no_passphrase set``, I cannot make it with a passphrase, nor can I change it to have a passphrase later.
I suspect it may also be related to a hang while unmounting, one that I haven't been patient enough to see how long it takes before my old friend, ``REISUB`` starts.
However, I'm not 100% sure this is an issue with the code here, and may be an issue with systemd on NixOS, in which I'm performing further testing to determine...

**Comment by Madouura** [comment]
It may just be using it on the USB drive with NixOS, as I only get this error on it.
![20220329_150441](https://user-images.githubusercontent.com/93990818/160699225-dafb0273-ca08-4fb3-a841-91dada73b67e.jpg)
![20220329_150544](https://user-images.githubusercontent.com/93990818/160699243-a390baab-8f41-47d0-8c8e-da17d865d90a.jpg)
![20220329_150415](https://user-images.githubusercontent.com/93990818/160699262-fee57b9c-5ce3-46d5-a900-39710ed98c0b.jpg)

**Comment by Madouura** [comment]
I do actually get the ``mount: /mnt: cannot mount /dev/sdb read only`` on my full system too, but it seems to be random.

**Comment by Madouura** [comment]
My issue is a bad interaction between nixos-stable and the nixos-unstable parts that using the unstable version of the package pulls, and is thus not a bcachefs issue.
That said, I do need to do ``keyctl link @u @s`` in the usb installation.
