### ISSUE TITLE
Thread 1 "bcachefs" received signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by b-r-o-w-n** [koverstreet/bcachefs#391]
This is my first 5.16.0 compile and test! This did not happen in 5.15.0....

 5.16.0-g367a8fad4592+ 
bcachefs tool version v0.1-481-ge76dbf1+

bcachsfs-tools make:
make update-bcachefs-sources LINUX_DIR=/usr/src/bcachefs-kernel; make clean;make -j13

GNU gdb (Gentoo 11.2 vanilla) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/src/bcachefs-tools/bcachefs...
Starting program: /usr/src/bcachefs-tools/bcachefs format -f --label=hdd /dev/sdb /dev/sdc /dev/sde /dev/sdf --data_replicas=2 --metadata_replicas=2 --bucket=2M --compression=lz4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff79b1600 (LWP 14559)]
[New Thread 0x7ffff79a8600 (LWP 14560)]
[New Thread 0x7ffff799f600 (LWP 14561)]
[New Thread 0x7ffff7996600 (LWP 14562)]
[New Thread 0x7ffff798d600 (LWP 14563)]
[New Thread 0x7ffff797f600 (LWP 14564)]
[New Thread 0x7ffff7976600 (LWP 14565)]

Thread 1 "bcachefs" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a5d0e6 in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7a5d0e6 in ?? () from /lib64/libc.so.6
#1  0x00007ffff7a20d88 in ?? () from /lib64/libc.so.6
#2  0x00007ffff7a30e98 in ?? () from /lib64/libc.so.6
#3  0x00005555555f8a08 in vsnprintf (__ap=0x7fffffffd8c0, __fmt=0x55555562e024 "%s: too small (min %llu)",
    __n=<optimized out>, __s=<optimized out>) at /usr/include/bits/stdio2.h:85
#4  bch2_pr_buf (out=0x7fffffffd9d8, fmt=fmt@entry=0x55555562e024 "%s: too small (min %llu)") at libbcachefs/util.c:130
#5  0x00005555555d339c in bch2_opt_validate (opt=<optimized out>, v=<optimized out>, err=<optimized out>)
    at libbcachefs/opts.c:231
#6  0x0000555555565e98 in bch2_parse_opts (strs=...) at libbcachefs.c:609
#7  0x000055555560b5f9 in cmd_format (argc=<optimized out>, argc@entry=11, argv=argv@entry=0x7fffffffe238)
    at cmd_format.c:128
#8  0x000055555555e1bb in main (argc=<optimized out>, argv=0x7fffffffe238) at bcachefs.c:195

I have done no additional investigation , It looks like it does not like the format string!

**Comment by koverstreet** [comment]
Update your -tools - I think this is already fixed

**Comment by b-r-o-w-n** [comment]
You are correct.. You fixed it last night. I did not update today.
