### ISSUE TITLE
-Werror=format-security

### ISSUE THREAD

**Issue by mBornand** [koverstreet/bcachefs#398]
Hello,

When building bcachefs-tools with `-Werror=format-security` there is an error in `fs/bcachefs/util.h` in the function `pr_uuid`. The compiler complains: "format not a string literal and no format arguments".

I think `uuid_str` will probably never contain a %, but it would be consistent with the use in `pr_time` from the same file. Maybe this isn't an issue. If should open a pull request for one line I could but i thought it wasn't necessary.

Commit id of the kernel source: `40a2993bf6e9f2`

**Comment by koverstreet** [comment]
Hey thanks for the report - I just pushed the fix.
