### ISSUE TITLE
BUG: unable to handle kernel paging request [...] IP: ZSTD_compressSequences_internal

### ISSUE THREAD

**Issue by BlackLotus** [koverstreet/bcachefs#4]
Created a bcachefs for testing with
> ./mkfs.bcachefs --compression_type=zstd  --background_compression_type=zstd -L bcacheMedia /dev/sdc1

Get this when doing an rsync to it.
Here is the dmesg output https://gist.github.com/BlackLotus/e158b7ed7dea45c5ef21923729f78d13

Kernel is compiled from git master 0eb4ad1d972af77b94073f328c85f958b53e3fdb

**Comment by koverstreet** [comment]
How long did it take you to hit it? I've got my zstd test running but I'm not having any luck reproducing it so far.

**Comment by BlackLotus** [comment]
took about 200G tested it with only background compression and didn't hit it that way.
I'm not exactly sure what both compression options do to be honest couldn't find any accurate description best I found was https://bcachefs.org/IoTunables/
Is there any way how I can help to debug it? Don't really know how I could best help to reproduce this.

**Comment by BlackLotus** [comment]
Ok same setup as in the original issue:
``` # 1  Extended offline    Completed without error       00%     10436         -```

dmesg: https://gist.github.com/39471242334a9dd5d74c8d0f6c11546a
/dev/sdd1       840G    481G  359G   58% /mnt/extern
