### ISSUE TITLE
unable to handle kernel paging request: anon_unlink_vmas

### ISSUE THREAD

**Issue by hyperfekt** [koverstreet/bcachefs#40]
During a boot attempt today I had this occur, the next boot went fine.
(Didn't land in persistent storage, sorry for the screenshots.)
![IMG_20190507_214651](https://user-images.githubusercontent.com/9434715/57331759-ad78b180-7119-11e9-9690-512961dde528.jpg)
![IMG_20190507_214639](https://user-images.githubusercontent.com/9434715/57331866-e2850400-7119-11e9-9f7a-b4c86e8bb7b0.jpg)
![IMG_20190507_214610](https://user-images.githubusercontent.com/9434715/57331954-14966600-711a-11e9-8927-342264b72015.jpg)

Commit was 1f34297.

**Comment by koverstreet** [comment]
I don't think this is a bcachefs issue or related to any of my other kernel changes - closing this unless you have some other reason to think it might be

**Comment by hyperfekt** [comment]
That's great to hear! I hope you don't mind me reporting things like this, I thought it could be related given that bcachefs is by far the most experimental part of my system and it got logged right after the mount - but I don't have any further indication that it would be bcachefs' fault.
