### ISSUE TITLE
encrypted bcachefs crashes when writing (installer) [fad6d13]

### ISSUE THREAD

**Issue by Madouura** [koverstreet/bcachefs#419]
**Version**
fad6d13aa55f96e01cc6ff516cdfea53b2fc9eb1

**Generic info**
This bug seems to happen at completely random times, each time I have tried to test this it's completely different each time.
https://gist.github.com/Madouura/90e92652fc799b83074c296593a67743
https://gist.github.com/Madouura/647fa43c65d2ed77125d8a8cec73a7bc

**Kernel bugs**
>Compile the kernel with these flags:

>```
>CONFIG_PREEMPT=y
>CONFIG_BCACHEFS_DEBUG=y
>CONFIG_KALLSYMS=y
>CONFIG_KALLSYMS_ALL=y
>CONFIG_DEBUG_FS=y
>CONFIG_DYNAMIC_FTRACE=y
>CONFIG_FTRACE=y
>```
PREEMPT didn't compile for whatever reason.
I don't think dmesg will help here as this is a vm and thus kernel messages should be displayed.
https://gist.github.com/Madouura/ad575242cc40e178f7cca5e107104dda
Also, it locks up where the end of the log is, normally I'd be able to get a complete log with ``nix-log`` IIRC - that's impossible due to this.

**Optional Advanced**

>If lockup or performance issues:
>* run `perf record` and `perf record -e 'bcachefs:*' -o events.data` both during the window of issue and then ctrl+c.
>* run `perf archive` to dump symbols.
>* archive, compress and upload the files: `perf.data`, `events.data` and `perf.data.tar.bz2`.

>Upload large files to a file storage provider:
>* provide the output of `bcachefs list_journal -a <list of devices> | zstd -f -T0 -o ../journal.log.zst`
>*compress & upload all the `metdata.dump.*` files from: bcachefs dump -o metadata.dump <list of devices>

Unsure how to effectively do this part, as this is in a VM that's data is removed before and after usage.

**Comment by Madouura** [comment]
I should also mention I did change the linux-kernels.nix to have bcachefs use 5.18, so it's not an incompatibility with 5.17.

**Comment by koverstreet** [comment]
Fixed by e3773ba3c8
