### ISSUE TITLE
BUG: using smp_processor_id() in preemptible [00000000] code: mount/455

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#42]
https://pastebin.com/1XemC2Jw

also sometimes the fs just stops responding and i have to use magic keys to manually reboot but as the whole system just freezes i cannot get any output

**Comment by nicman23** [comment]
this is a screenshot of when such hangs happen. there a 30% chance that the system with recover if i perform some action such as login off from an ssh instance or taking a screenshot.

https://imgur.com/a/EdSY1yU

**Comment by nicman23** [comment]
https://imgur.com/a/1uSlMPV

0 relevant messages on dmesg and journalctl after sysrq + r,e and "normal" shutdown with ctrl alt del from a tty

**Comment by koverstreet** [comment]
fixed by a8c7411995

**Comment by nicman23** [comment]
https://pastebin.com/symR54Cv with latest master
