### ISSUE TITLE
Add information about commit

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#43]
It would be nice to have possibility to check on which commit bcachefs is used. Maybe info in dmesg or something under /sys/module/bcachefs/...

**Comment by nicman23** [comment]
nah just add it to the uname

**Comment by marcin-github** [comment]
I'm using bcachefs as module, it will not work.

**Comment by koverstreet** [comment]
This exists for the kernel - CONFIG_LOCALVERSION_AUTO.

Having it available per-module would be nice, but outside the scope of bcachefs...
