### ISSUE TITLE
util.c:(.text+0x73e): undefined reference to `__udivdi3'

### ISSUE THREAD

**Issue by lekto** [koverstreet/bcachefs#431]
Hi, I'm trying to build kernel for x86 (Core Duo U2500) and I'm ending with this error:

>  LD      vmlinux.o
>  MODPOST vmlinux.symvers
>  MODINFO modules.builtin.modinfo
>  GEN     modules.builtin
>  LD      .tmp_vmlinux.kallsyms1
> ld: fs/bcachefs/util.o: in function `__bch2_strtoh.constprop.0`:
> util.c:(.text+0x73e): undefined reference to `__udivdi3`
> make: *** [Makefile:1158: vmlinux] Error 1

Bcachefs is built in, when I disabled it I can successfully build and run kernel.
Kernel version: 5.18.0-g18a7b73e0882
gcc: 11.3.0
binutils: 2.37
glibc: 2.34

**Comment by koverstreet** [comment]
Fixed by 977d583e52
