### ISSUE TITLE
BCH_IOCTL_USAGE error: Numerical result out of range

### ISSUE THREAD

**Issue by wilson111** [koverstreet/bcachefs#44]
First, thank Kent for writing such promising fs for Linux. I'm a Patreon supporter and I've been testing bcachefs since a year ago.   I'm using multiple devices as a backup target filesystem for testing bcachefs (with different Ubuntu distributions).  I find that "bcachefs fs usage" command always gives this BCH_IOCTL_USAGE error.  Is it normal or something that I did wrong during fs creation?

root@nas2:~# bcachefs format --group hdd /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/sdg /dev/sdi --group ssd /dev/sdj --foreground_target ssd --background_target hdd --promote_target ssd

root@nas2:~# bcachefs fs usage /mnt
BCH_IOCTL_USAGE error: Numerical result out of range

root@nas2:~# bcachefs version
bcachefs tool version v0.1-65-g93bdfcb

root@nas2:~# df
Filesystem                                                                1K-blocks       Used   Available Use% Mounted on
udev                                                                        1508708          0     1508708   0% /dev
tmpfs                                                                        306944       2580      304364   1% /run
/dev/sda1                                                                  60406860   35291088    22024164  62% /
tmpfs                                                                       1534712          0     1534712   0% /dev/shm
tmpfs                                                                          5120          4        5116   1% /run/lock
tmpfs                                                                       1534712          0     1534712   0% /sys/fs/cgroup
/dev/sdb:/dev/sdc:/dev/sdd:/dev/sde:/dev/sdf:/dev/sdg:/dev/sdi:/dev/sdj 18428465192 7835295628 10593169564  43% /mnt
tmpfs                                                                        306940          0      306940   0% /run/user/1000

root@nas2:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

root@nas2:~# for drive in /dev/sd?; do echo $drive; smartctl -i $drive; done | egrep 'dev|Family|Model|Capacity'
/dev/sda
/dev/sda: Unknown USB bridge [0x0080:0xa001 (0x204)]
Please specify device type with the -d option.
/dev/sdb
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdc
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdd
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sde
Model Family:     Hitachi Deskstar 7K3000
Device Model:     Hitachi HDS723020BLA642
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdf
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdg
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdh
Model Family:     Seagate Barracuda 7200.14 (AF)
Device Model:     ST3000DM001-1ER166
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdi
Model Family:     Toshiba 3.5" DT01ACA... Desktop HDD
Device Model:     TOSHIBA DT01ACA300
User Capacity:    3,000,592,982,016 bytes [3.00 TB]
SMART support is: Available - device has SMART capability.
/dev/sdj
Model Family:     Crucial/Micron MX100/MX200/M5x0/M600 Client SSDs
Device Model:     Crucial_CT512MX100SSD1
User Capacity:    512,110,190,592 bytes [512 GB]
SMART support is: Available - device has SMART capability.

root@nas2:~# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0 74.5G  0 disk 
├─sda1   8:1    0 58.7G  0 part /
├─sda2   8:2    0    1K  0 part 
└─sda5   8:5    0 15.9G  0 part [SWAP]
sdb      8:16   1  2.7T  0 disk /mnt
sdc      8:32   1  2.7T  0 disk 
sdd      8:48   1  2.7T  0 disk 
sde      8:64   1  1.8T  0 disk 
sdf      8:80   1  2.7T  0 disk 
sdg      8:96   1  2.7T  0 disk 
sdh      8:112  1  2.7T  0 disk 
sdi      8:128  1  2.7T  0 disk 
sdj      8:144  1  477G  0 disk

**Comment by koverstreet** [comment]
Upgrade bcachefs-tools

**Comment by wilson111** [comment]
root@nas2:~# git clone http://evilpiepirate.org/git/bcachefs-tools.git
Cloning into 'bcachefs-tools'...
warning: redirecting to https://evilpiepirate.org/git/bcachefs-tools.git/
remote: Enumerating objects: 5079, done.
remote: Counting objects: 100% (5079/5079), done.
remote: Compressing objects: 100% (2767/2767), done.
remote: Total 5079 (delta 3839), reused 2994 (delta 2174)
Receiving objects: 100% (5079/5079), 2.70 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (3839/3839), done.

root@nas2:~# cd bcachefs-tools
root@nas2:~/bcachefs-tools# ls
bcachefs.8      cmd_attr.c    cmd_format.c  cmd_migrate.c  config.h  debian         initramfs      libbcachefs.h  nix      README
bcachefs.c      cmd_data.c    cmd_fs.c      cmd_run.c      COPYING   default.nix    INSTALL        linux          qcow2.c  tools-util.
ccan            cmd_debug.c   cmd_fsck.c    cmds.h         crypto.c  fsck.bcachefs  libbcachefs    Makefile       qcow2.h  tools-util.
cmd_assemble.c  cmd_device.c  cmd_key.c     cmd_version.c  crypto.h  include        libbcachefs.c  mkfs.bcachefs  raid

root@nas2:~/bcachefs-tools# make

root@nas2:~/bcachefs-tools# ./bcachefs version
bcachefs tool version v0.1-66-g7e35389
root@nas2:~/bcachefs-tools# ./bcachefs fs usage /mnt
BCH_IOCTL_USAGE error: Numerical result out of range

Still not working after a fresh new git clone.  Anything else should I look into?

**Comment by stintel** [comment]
Having the same problem for as long as I can remember. Mentioned it on IRC a few times, first time on 5/10/2018. Can't recall if it ever worked. At some point I suspected it could be related to me using musl libc, but that's a very wild guess.

**Comment by koverstreet** [comment]
Whoops, it was broken for > 4 devices because it was checking for the wrong error code. Fixed now.

**Comment by wilson111** [comment]
It works now.  Many thanks.
