### ISSUE TITLE
Kernel crash caused by rand insert (Perf Test, Version 5.19)

### ISSUE THREAD

**Issue by alkkkj** [koverstreet/bcachefs#459]
I use the following command to test random insert performance, but unfortunately kernel crash. 

Command:
echo "rand_insert 10000000 10" > perf_test

Super block information:
# bcachefs show-super /dev/nvme1n1 
External UUID:                  57b62d41-394c-4d44-b95b-e6bf630cb1c4
Internal UUID:                  70973416-5e21-4964-b772-fc669e7ce813
Device index:                   0
Label:                          
Version:                        backpointers
Oldest version on disk:         backpointers
Created:                        Fri Sep 23 13:21:02 2022
Sequence number:                8
Superblock size:                3648
Clean:                          0
Devices:                        1
Sections:                       members,replicas_v0,clean,journal_v2,counters
Features:                       new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4.00 KiB
  btree_node_size:              64.0 KiB
  errors:                       continue [ro] panic
  metadata_replicas:            1
  data_replicas:                1
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64.0 KiB
  metadata_checksum:            none [crc32c] crc64 xxhash
  data_checksum:                none [crc32c] crc64 xxhash
  compression:                  [none] lz4 gzip zstd
  background_compression:       [none] lz4 gzip zstd
  str_hash:                     crc32c crc64 [siphash]
  metadata_target:              none
  foreground_target:            none
  background_target:            none
  promote_target:               none
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0 B
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
 

Kernel crash information:

[ 7251.075605] INFO: task kworker/3:2:3095 blocked for more than 122 seconds.
[ 7251.075615]       Tainted: G S                5.19.0 #1
[ 7251.075618] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 7251.075621] task:kworker/3:2     state:D stack:    0 pid: 3095 ppid:     2 flags:0x00004000
[ 7251.075630] Workqueue: bcachefs_btree_io btree_node_write_work [bcachefs]
[ 7251.075713] Call Trace:
[ 7251.075716]  <TASK>
[ 7251.075721]  __schedule+0x3f4/0x980
[ 7251.075733]  schedule+0x44/0xb0
[ 7251.075740]  __six_lock_type_slowpath+0x1c3/0x5e0
[ 7251.075748]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.075820]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.075901]  ? do_six_trylock_type.constprop.18+0x29/0x120
[ 7251.075907]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.075969]  btree_path_traverse_one+0x11f3/0x1250 [bcachefs]
[ 7251.076028]  ? bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.076091]  ? btree_path_alloc+0x1c3/0x2e0 [bcachefs]
[ 7251.076153]  ? bch2_path_get+0x23f/0x330 [bcachefs]
[ 7251.076215]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.076282]  bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.076345]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.076411]  bch2_btree_node_update_key_get_iter+0x7c/0x110 [bcachefs]
[ 7251.076479]  ? bch2_trans_begin+0x245/0x830 [bcachefs]
[ 7251.076557]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.076620]  btree_node_write_work+0x2e4/0x380 [bcachefs]
[ 7251.076684]  ? btree_node_write_work+0x2c6/0x380 [bcachefs]

[ 7251.076748]  process_one_work+0x1f8/0x3c0
[ 7251.076756]  ? process_one_work+0x3c0/0x3c0
[ 7251.076762]  worker_thread+0x2a/0x3b0
[ 7251.076769]  ? process_one_work+0x3c0/0x3c0
[ 7251.076774]  kthread+0xe8/0x110
[ 7251.076780]  ? kthread_complete_and_exit+0x20/0x20
[ 7251.076787]  ret_from_fork+0x22/0x30
[ 7251.076796]  </TASK>
[ 7251.076799] INFO: task kworker/21:2:3109 blocked for more than 122 seconds.
[ 7251.076803]       Tainted: G S                5.19.0 #1
[ 7251.076805] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 7251.076807] task:kworker/21:2    state:D stack:    0 pid: 3109 ppid:     2 flags:0x00004000
[ 7251.076813] Workqueue: events_long bch2_do_discards_work [bcachefs]
[ 7251.076865] Call Trace:
[ 7251.076866]  <TASK>
[ 7251.076869]  __schedule+0x3f4/0x980
[ 7251.076877]  schedule+0x44/0xb0
[ 7251.076883]  __six_lock_type_slowpath+0x1c3/0x5e0
[ 7251.076889]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.076954]  ? bch2_bucket_do_index+0x21f/0x3a0 [bcachefs]
[ 7251.077003]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.077067]  ? do_six_trylock_type.constprop.18+0x29/0x120
[ 7251.077073]  ? bch2_trans_mark_alloc+0x160/0x3d0 [bcachefs]
[ 7251.077123]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.077189]  __bch2_btree_node_lock_write+0x9e/0x140 [bcachefs]
[ 7251.077256]  do_bch2_trans_commit+0x865/0xfe0 [bcachefs]

[ 7251.077325]  ? bch2_do_discards_work+0x652/0x9a0 [bcachefs]
[ 7251.077375]  __bch2_trans_commit+0x615/0x7b0 [bcachefs]
[ 7251.077443]  ? bch2_do_discards_work+0x624/0x9a0 [bcachefs]
[ 7251.077493]  bch2_do_discards_work+0x652/0x9a0 [bcachefs]
[ 7251.077570]  ? find_busiest_group+0x41/0x340
[ 7251.077579]  ? bch2_do_discards_work+0xbd/0x9a0 [bcachefs]
[ 7251.077625]  ? bch2_do_discards_work+0x4dc/0x9a0 [bcachefs]
[ 7251.077668]  ? bch2_do_discards_work+0xfc/0x9a0 [bcachefs]
[ 7251.077712]  process_one_work+0x1f8/0x3c0
[ 7251.077719]  ? process_one_work+0x3c0/0x3c0
[ 7251.077724]  worker_thread+0x2a/0x3b0
[ 7251.077731]  ? process_one_work+0x3c0/0x3c0
[ 7251.077737]  kthread+0xe8/0x110
[ 7251.077742]  ? kthread_complete_and_exit+0x20/0x20
[ 7251.077747]  ret_from_fork+0x22/0x30
[ 7251.077755]  </TASK>
[ 7251.077765] INFO: task kworker/39:0:4304 blocked for more than 122 seconds.
[ 7251.077768]       Tainted: G S                5.19.0 #1
[ 7251.077771] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 7251.077773] task:kworker/39:0    state:D stack:    0 pid: 4304 ppid:     2 flags:0x00004000
[ 7251.077780] Workqueue: bcachefs_btree_io btree_node_write_work [bcachefs]
[ 7251.077837] Call Trace:
[ 7251.077839]  <TASK>
[ 7251.077841]  __schedule+0x3f4/0x980
[ 7251.077848]  schedule+0x44/0xb0
[ 7251.077854]  __six_lock_type_slowpath+0x1c3/0x5e0
[ 7251.077859]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]

[ 7251.077918]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.077973]  ? do_six_trylock_type.constprop.18+0x29/0x120
[ 7251.077979]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.078034]  btree_path_traverse_one+0x11f3/0x1250 [bcachefs]
[ 7251.078087]  ? bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.078140]  ? btree_path_alloc+0x1c3/0x2e0 [bcachefs]
[ 7251.078193]  ? bch2_path_get+0x23f/0x330 [bcachefs]
[ 7251.078245]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.078310]  bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.078373]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.078440]  bch2_btree_node_update_key_get_iter+0x7c/0x110 [bcachefs]
[ 7251.078517]  ? bch2_trans_begin+0x245/0x830 [bcachefs]
[ 7251.078580]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.078644]  btree_node_write_work+0x2e4/0x380 [bcachefs]
[ 7251.078707]  ? btree_node_write_work+0x2c6/0x380 [bcachefs]
[ 7251.078771]  process_one_work+0x1f8/0x3c0
[ 7251.078778]  ? process_one_work+0x3c0/0x3c0
[ 7251.078784]  worker_thread+0x2a/0x3b0
[ 7251.078791]  ? process_one_work+0x3c0/0x3c0
[ 7251.078797]  kthread+0xe8/0x110
[ 7251.078802]  ? kthread_complete_and_exit+0x20/0x20
[ 7251.078808]  ret_from_fork+0x22/0x30
[ 7251.078816]  </TASK>
[ 7251.078819] INFO: task kworker/17:1:4325 blocked for more than 122 seconds.
[ 7251.078823]       Tainted: G S                5.19.0 #1
[ 7251.078825] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 7251.078827] task:kworker/17:1    state:D stack:    0 pid: 4325 ppid:     2 flags:0x00004000

[ 7251.078833] Workqueue: bcachefs_btree_io btree_node_write_work [bcachefs]
[ 7251.078894] Call Trace:
[ 7251.078896]  <TASK>
[ 7251.078898]  __schedule+0x3f4/0x980
[ 7251.078906]  schedule+0x44/0xb0
[ 7251.078912]  __six_lock_type_slowpath+0x1c3/0x5e0
[ 7251.078918]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.078984]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.079048]  ? do_six_trylock_type.constprop.18+0x29/0x120
[ 7251.079054]  ? bch2_check_for_deadlock+0xb0/0xb0 [bcachefs]
[ 7251.079120]  btree_path_traverse_one+0x11f3/0x1250 [bcachefs]
[ 7251.079182]  ? bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.079245]  ? btree_path_alloc+0x1c3/0x2e0 [bcachefs]
[ 7251.079306]  ? bch2_path_get+0x23f/0x330 [bcachefs]
[ 7251.079369]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.079436]  bch2_btree_iter_traverse+0xb2/0x120 [bcachefs]
[ 7251.079499]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.079574]  bch2_btree_node_update_key_get_iter+0x7c/0x110 [bcachefs]
[ 7251.079643]  ? bch2_trans_begin+0x245/0x830 [bcachefs]
[ 7251.079708]  ? bch2_btree_node_update_key_get_iter+0x72/0x110 [bcachefs]
[ 7251.079775]  btree_node_write_work+0x2e4/0x380 [bcachefs]
[ 7251.079837]  ? btree_node_write_work+0x2c6/0x380 [bcachefs]
[ 7251.079901]  process_one_work+0x1f8/0x3c0
[ 7251.079909]  worker_thread+0x2a/0x3b0
[ 7251.079915]  ? process_one_work+0x3c0/0x3c0
[ 7251.079921]  kthread+0xe8/0x110
[ 7251.079926]  ? kthread_complete_and_exit+0x20/0x20

**Comment by koverstreet** [comment]
Fixed by e9077773c7
