### ISSUE TITLE
backpointer inconsistency [v5.19]

### ISSUE THREAD

**Issue by BingoLiuX** [koverstreet/bcachefs#460]
As running fio write/randwrite on bcachefs file, the bcachefs becomes read-only. 

Is this a bug?

# **bcachefs show-super /dev/nvme1n1** 
External UUID:                  ff904c68-8665-473f-bd23-5e41aacfb274
Internal UUID:                  c60657a7-e59c-4274-9d25-82dac47f1330
Device index:                   0
Label:                          
Version:                        backpointers
Oldest version on disk:         backpointers
Created:                        Fri Sep 23 15:16:11 2022
Sequence number:                15
Superblock size:                3680
Clean:                          0
Devices:                        1
Sections:                       members,replicas_v0,clean,journal_seq_blacklist,journal_v2,counters
Features:                       journal_seq_blacklist_v3,new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4.00 KiB
  btree_node_size:              256 KiB
  errors:                       continue [ro] panic
  metadata_replicas:            1
  data_replicas:                1
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64.0 KiB
  metadata_checksum:            none [crc32c] crc64 xxhash
  data_checksum:                none [crc32c] crc64 xxhash
  compression:                  [none] lz4 gzip zstd
  background_compression:       [none] lz4 gzip zstd
  str_hash:                     crc32c crc64 [siphash]
  metadata_target:              none
  foreground_target:            none
  background_target:            none
  promote_target:               none
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0 B
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        100

members (size 64):
  Device:                       0
    UUID:                       faf42d3e-bf48-47ad-95b5-65a232332089
    Size:                       1.46 TiB
    Bucket size:                32.0 MiB
    First bucket:               0
    Buckets:                    47694
    Last mount:                 Fri Sep 23 17:22:48 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree,user
    Discard:                    0
    Freespace initialized:      1
	

# **bcachefs fs usage /mnt/bfs-4/**
Filesystem: ff904c68-8665-473f-bd23-5e41aacfb274
Size:                  1472295007744
Used:                   770400975872
Online reserved:                   0

Data type       Required/total  Devices
btree:          1/1             [nvme1n1]                 2488795136
user:           1/1             [nvme1n1]               759255269376

(no label) (device 0):       nvme1n1              rw
                                data         buckets    fragmented
  free:                            0           16618
  sb:                        3149824               2      63958016
  journal:                8589803520             256
  btree:                  2488795136             248    5832577024
  user:                 759255269376           30568  266420957184
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               2
  erasure coded:                   0               0
  capacity:            1600320660480           47694

# **ls -lish /mnt/bfs-4/**
total 708G
973078528 702G -rw-r--r--. 1 root root 1.3T Sep 23 17:06 f5

**fio command:**
# fio -filename=/mnt/bfs-4/f5  -iodepth 1 -thread -rw=randwrite -ioengine=libaio -bs=256K -direct=1 -numjobs=10 -group_reporting  -name=randread -runtime=1d  --time_based

**dmesg:**

Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1): backpointer doesn't match extent it points to:#012  bucket: 0:16629:0#012  backpointer pos: 0:1115941424128:0#012  btree=extents l=0 offset=5032:0 len=128 pos=973078528:864640:U32_MAX#012  u64s 7 type extent 973078528:864640:U32_MAX len 128 ver 0: crc: c_size 128 size 128 offset 0 nonce 0 csum crc32c compress none ptr: 0:260:5032 gen 11
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1): inconsistency detected - emergency read only
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1): transaction updates for __bch2_evacuate_bucket journal seq 0
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:06:56 qs62 kernel: bcachefs (nvme1n1): error from bch2_move_data() in copygc: EROFS

**After umount and remount:**
Sep 23 17:15:37 qs62 kernel: bcachefs (nvme1n1): recovering from unclean shutdown
Sep 23 17:15:42 qs62 kernel: bcachefs (nvme1n1): journal read done, 178220 keys in 41 entries, seq 153624
Sep 23 17:15:42 qs62 kernel: bcachefs (nvme1n1): dropped unflushed entries 153606-153623
Sep 23 17:15:42 qs62 kernel: bcachefs (nvme1n1): going read-write
Sep 23 17:15:52 qs62 kernel: bcachefs (nvme1n1): journal replay done
Sep 23 17:15:52 qs62 kernel: bcachefs (nvme1n1): mounted version=backpointers opts=noinodes_use_key_cache
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 201326592): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:58 qs62 kernel: bcachefs (nvme1n1 inum 973078528): misaligned write
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1): backpointer doesn't match extent it points to:#012  bucket: 0:32117:0#012  backpointer pos: 0:2155353371648:0#012  btree=extents l=0 offset=49682:0 len=128 pos=973078528:157210240:U32_MAX#012  u64s 7 type extent 973078528:157210240:U32_MAX len 128 ver 0: crc: c_size 128 size 128 offset 0 nonce 0 csum crc32c compress none ptr: 0:15732:49682 gen 2
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1): inconsistency detected - emergency read only
Sep 23 17:15:59 qs62 kernel: __bch2_write_index: 18 callbacks suppressed
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1): fatal error writing btree node
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1): transaction updates for __bch2_evacuate_bucket journal seq 0
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1): error from bch2_move_data() in copygc: EIO
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS
Sep 23 17:15:59 qs62 kernel: bcachefs (nvme1n1 inum 973078528): write error while doing btree update: EROFS

**Comment by YellowOnion** [comment]
Yeah I've been hitting this bug, It's not an easy fix, hopefully I can find it in the next week.

**Comment by koverstreet** [comment]
We just merged a backpointer fix - I'm not sure if it's the same as this bug or if we had two outstanding, YellowOnion?

**Comment by koverstreet** [comment]
Closing this - please reopen if it turns out it's not fixed
