### ISSUE TITLE
Upgrade the patch for 5.19.x kernel tree

### ISSUE THREAD

**Issue by sergiall** [koverstreet/bcachefs#461]
Have a nice day! I try to build prestine tar linux kernel release from kernell.org hub with latest common patchset what I can find on Sir Lucian's kernel-patches repo, so '0001-bcachefs-5.18-introduce-bcachefs-patchset.patch' , but this causes multiple errors around . Yes, I know, what versions of patch is too old, but where search actualy patch for me? Exactly the kernel tree of this bcachefs repo is also too old, and as I think based on 5.19-rc kernel branch ... Sorry for my bad french :(( Please, give any link to 5.19 patchset, standalone of kernel tree.
Thanks and regards!

**Comment by bhzhu203** [comment]
You could use this command to make the patch:

diff -Naru filePath(standar kernel source) filePath(bcachefs source) > differences.patch

**Comment by sergiall** [comment]
Thank for advance! But workaround above create too lage otput file ~1,5G, so i resolve this in another case:
`
$ less 0001-bcachefs-5.18-introduce-bcachefs-patchset.patch #for view and copy/save list of affected files in ktree
$ cat $list | awk '{print $1}' > flist
$ cp $flist to both filePath(standard kernel source) & filePath(bcachefs source)

$ mkdir -p a b

$cd  filePath(bcachefs source);for F  in $(cat $flist);do cp -var --parents $F ../b/;done

$cd  filePath(standart kernel source);for  F  in $(cat $flist);do cp -var --parents $F ../a/;done

cd ..;diff -rupN a/ b/ > bcachefs.patch
`
Result:
[bcachefs-5.19.11.patch.md](https://github.com/koverstreet/bcachefs/files/9660138/bcachefs-5.19.11.patch.md)

Thank you again!

**Comment by koverstreet** [comment]
We're on 6.0 now

**Comment by sergiall** [comment]
Sorry fo my letter, you are right. And we have introduce 6.0 patch right now!
[bcachefs-6.0.patch.md](https://github.com/koverstreet/bcachefs/files/9759291/bcachefs-6.0.patch.md)
