### ISSUE TITLE
rand insert 10 billions key took long[v5.17]

### ISSUE THREAD

**Issue by BingoLiuX** [koverstreet/bcachefs#462]
I tried rand insert 1 billion keys ,it seems good, but got worse when keys reaches 10 billion.

**[12485.858727] rand_insert: 953M with 12 threads in   730 sec,  8769 nsec per iter,  1.3M per sec**

Then I tried to rand insert **10 billion** keys, it took more than **13 hours**, still running.

So will it be a performance problem when the B+ tree get big enough ?

**perf command:**
# echo rand_insert 10000000000 12 > perf_test

# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme1n1    1.4T  **327G** 1022G  25% /mnt/bfs-4

**device iostat:**
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
nvme1n1           0.00     0.00 2024.00 4362.00   253.00    22.51    88.36     1.27    0.20    0.61    0.01   0.16  99.40

# bcachefs show-super /dev/nvme1n1 
External UUID:                  c0286cd1-d077-49f8-b1c7-23e7fc2d6d69
Internal UUID:                  8a86f1c4-5c93-41ed-96b5-bf690de80031
Device index:                   0
Label:                          
Version:                        new_data_types
Oldest version on disk:         inode_v2
Created:                        Mon Sep 26 22:09:49 2022
Sequence number:                8
Superblock size:                68024
Clean:                          0
Devices:                        1
Sections:                       journal,members,replicas_v0,clean,counters
Features:                       new_siphash,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   4.00 KiB
  btree_node_size:              256 KiB
  errors:                       continue [ro] panic
  metadata_replicas:            1
  data_replicas:                1
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64.0 KiB
  metadata_checksum:            none [crc32c] crc64 xxhash
  data_checksum:                none [crc32c] crc64 xxhash
  compression:                  [none] lz4 gzip zstd
  background_compression:       [none] lz4 gzip zstd
  str_hash:                     crc32c crc64 [siphash]
  metadata_target:              none
  foreground_target:            none
  background_target:            none
  promote_target:               none
  erasure_code:                 0
  inodes_32bit:                 1
  shard_inode_numbers:          1
  inodes_use_key_cache:         1
  gc_reserve_percent:           8
  gc_reserve_bytes:             0 B
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        100

members (size 64):
  Device:                       0
    UUID:                       6f4a978d-e3c9-475e-8ee7-486cf6cf8e67
    Size:                       1.46 TiB
    Bucket size:                1.00 MiB
    First bucket:               0
    Buckets:                    1526185
    Last mount:                 Mon Sep 26 22:10:03 2022
    State:                      rw
    Label:                      (none)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree
    Discard:                    0
    Freespace initialized:      1

# bcachefs fs usage
Filesystem: c0286cd1-d077-49f8-b1c7-23e7fc2d6d69
Size:                  1472295285760
Used:                   358867173376
Online reserved:            10485760

Data type       Required/total  Devices
btree:          1/1             [nvme1n1]               350262394880

(no label) (device 0):       nvme1n1              rw
                                data         buckets    fragmented
  free:                            0         1060651
  sb:                        3149824               4       1044480
  journal:                8589934592            8192
  btree:                350262394880          457314  129266089984
  user:                            0               0
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0              24
  erasure coded:                   0               0
  capacity:            1600320962560         1526185

# cat io_latency_stats_write 
count:          187914837
rate:           3049/sec
frequency:      327 us
avg duration:   12 us
max duration:   5 ms
quantiles (us): 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8

**Comment by koverstreet** [comment]
That's expected when you're doing random updates an the b-tree no longer fits in ram.
