### ISSUE TITLE
getfattr does not seem to be able to read file/directory options with backpointers.

### ISSUE THREAD

**Issue by MoraFermi** [koverstreet/bcachefs#472]
This is kernel version 83edfde and bcachefs-tools [72add88](https://github.com/koverstreet/bcachefs-tools/commit/72add8822c47e5801d4ac6d42af8c5d9d7b4d3c9)

I have created a new filesystem using `bcachefs format -L internal --acl --usrquota --block_size=4k --label ssd.0 --discard /dev/nvme0n1 --label ssd.1 --discard /dev/nvme1n1 --label hdd.0 /dev/sdb --label hdd.1 /dev/sdc`

I am using the following to set caching for a directory that will need to absorb a lot of writes:
`bcachefs setattr --foreground_target=ssd --background_target=hdd ProBook`

Previously, these settings were easy to verify using `getattr -d`.

With the current kernel/bcachefs-tools combination, getfattr doesn't seem to work anymore:

```
# bcachefs setattr --foreground_target=ssd --background_target=hdd ProBook
# getfattr -d -m ’^bcachefs\.’ ProBook
# getfattr -d -m ’^bcachefs_effective\.’ ProBook
# 
```

**Comment by koverstreet** [comment]
Do you know a version when this used to work?

**Comment by koverstreet** [comment]
Your exact example worked for me - after I fixed the quote characters (github mangling?)

**Comment by MoraFermi** [comment]
Huh...

It turns out that the mangling is in the bcachefs manual pdf -- https://bcachefs.org/bcachefs-principles-of-operation.pdf
I simply copy-pasted the command from there. 
On my terminal, the whatever-apostrophe the document contains is indistinguishable from the normal one, so I never realised the issue.
