### ISSUE TITLE
Background compression is busted

### ISSUE THREAD

**Issue by koverstreet** [koverstreet/bcachefs#48]
It will keep trying to compress uncompressable data over and over

**Comment by minorsecond** [comment]
Is there any way to disable background compression (or any options in general) once the filesystem is created?

**Comment by YellowOnion** [comment]
Is this still a problem @koverstreet ? this might be causing me problems with fragmentation...

@minorsecond yes there is in the /sys/fs/bcachefs interface, just echo none to the background_compression option.
