### ISSUE TITLE
can not delete snaptshots and FS turns into ro

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#487]
**Please search for duplicates**

**Version**
84505cfd37957accbff6fa7e4477bfd9c4c23ba6

After fsck , the subvolume can not be deleted and not found ,FS become ro

```[  274.825621] pool (1499) used greatest stack depth: 8864 bytes left
[  345.798608] bcachefs (sdb9): missing subvolume 30
[  345.798614] bcachefs (sdb9): inconsistency detected - emergency read only
[  345.798634] bcachefs (sdb9): error deleting subvolume 30: EIO
[  345.921697] bcachefs (sdb9): error deleting snapshot keys: erofs_trans_commit
````

I think the fsck might  lead to subvolumes can not be deleted correctly

[1215.txt](https://github.com/koverstreet/bcachefs/files/10237264/1215.txt)

**Comment by bhzhu203** [comment]
I have updated to the latest bcachefs version , there is no big issue yet .And the snapshot deletion works well for now. But There were some warning in the 1th /2th time  deletion

I can do  batch deletion now ,I will do more tests for that.
[snapshot-deletion-warnning-1220.txt](https://github.com/koverstreet/bcachefs/files/10273815/snapshot-deletion-warnning-1220.txt)

**Comment by jpsollie** [comment]
I have the same issue:
```
linuxserver # bcachefs sub volume snapshots -r .snapshots/test
```
This works fine.

... but deleting it shows in dmesg:
```
[ 1199.954954] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): missing subvolume 0                             
[ 1199.954964] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): inconsistency detected - emergency read only
```
when i unmount & performance a fsck, it fixes the inconsistency, but the snapshot is gone

**Comment by bhzhu203** [comment]
> I have the same issue:
> 
> ```
> linuxserver # bcachefs sub volume snapshots -r .snapshots/test
> ```
> 
> This works fine.
> 
> ... but deleting it:
> 
> ```
> linuxserver # bcachefs subvolume delete .snapshots/test
> BCH_IOCTL_SUBVOLUME_DESTROY ioctl error: No such file or directory
> ```
> 
> ... but the snapshot is deleted after all. The real problem starts when creating a second one:
> 
> ```
> bcachefs subvolume snapshot -r .snapshots/test                                   
> BCH_IOCTL_SUBVOLUME_CREATE ioctl error: No such file or directory
> ```
> 
> and it shows in dmesg:
> 
> ```
> [ 1199.954954] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): missing subvolume 0                             
> [ 1199.954964] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): inconsistency detected - emergency read only
> ```
> 
> when i unmount & perform a fsck, it fixes the inconsistency, but there is no snapshot

How about the latest version ?

**Comment by jpsollie** [comment]
to help locate the problem, I ran a small perf record on the PC:
ˋˋˋ
29.35%  mount            [kernel.vmlinux]            [k] bch2_btree_node_iter_init
11.92%  mount            [kernel.vmlinux]            [k] bch2_btree_path_traverse_one                                                                           4.44%  mount            [kernel.vmlinux]            [k] bch2_btree_iter_peek_upto
3.57%  mount            [kernel.vmlinux]            [k] __do_six_trylock_type
3.25%  mount            [kernel.vmlinux]            [k] __bch2_btree_path_set_pos
3.23%  mount            [kernel.vmlinux]            [k] six_unlock_ip_read
3.09%  mount            [kernel.vmlinux]            [k] bch2_btree_key_cache_find
3.08%  mount            [kernel.vmlinux]            [k] sched_clock_cpu
ˋˋˋ
I hope it will help someone to diagnose

**Comment by bhzhu203** [comment]
> just updated ([6a25267](https://github.com/koverstreet/bcachefs/commit/6a252676f712fe07c087169391386f7edc579a6c)): when mounting:
> 
> ```
> [  653.489276] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): starting journal replay, 11 keys
> [  653.489293] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): going read-write
> [  654.634130] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): journal replay done
> [  654.634134] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking need_discard and freespace btrees
> [  655.820812] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking lrus
> [  656.948226] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking backpointers to alloc keys
> [  656.948934] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking backpointers to extents
> [  668.060405] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking extents to backpointers
> [  679.752443] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): checking alloc to lru refs
> [  681.844445] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): starting fsck
> [  684.669864] bcachefs (d759d0a7-09c4-472b-9cd0-ed0d9a76e7fa): mounted version=lru_v2 opts=metadata_replicas=3,data_checksum=xxhash,metadata_target=SSDM,foreground_target=SSDC,background_target=HDD,promote_target=SSDC,fsck,fix_errors,nojournal_transaction_names
> ```
> 
> so this looks good, but afterwards, the log starts flooding:
> 
> ```
> [  787.960546] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960559] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960566] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960580] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960587] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960595] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960603] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960615] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960628] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960631] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960646] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960657] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960666] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960674] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960687] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960705] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960712] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960719] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960724] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960729] transaction updates for bch2_gc_btrees journal seq 0
> [  787.960736] transaction updates for bch2_gc_btrees journal seq 0
> ```
> 
> this ultimately ends, but mount needs quite a lot of time to fix it. Bcachefs subvolume snapshot create results in a IOCTL_SUBVOLUME_CREATE error, something like above (tested on newly-formatted filesystem:
> 
> ```
> # bcachefs subvolume snapshot -r .snapshots/subvoltest
> BCH_IOCTL_SUBVOLUME_CREATE ioctl error: No such file or directory
> # dmesg | tail
> ...
> [ 3015.745089] bcachefs (a9e62f0f-3a9d-4c7d-a8f9-444cfc2dabd2): missing subvolume 0
> [ 3015.745099] bcachefs (a9e62f0f-3a9d-4c7d-a8f9-444cfc2dabd2): inconsistency detected - emergency read only
> ```
> 
> _EDIT_: don't know whether it is important, but this command DOES work:
> 
> ```
> bcachefs subvolume snapshot -r . .snapshots/subvoltest
> ```

Maybe you should do the fsck with the latest version bacachefs-tools  https://github.com/koverstreet/bcachefs-tools

bcachefs fsck -y /dev/sda

**Comment by jpsollie** [comment]
the ehaviour is exactly the same, both tools and kernel.
That's how I got the GDB stacktrace btw :)

**Comment by jpsollie** [comment]
bug is solved with recent snapshot updates, @YellowOnion , can you close this bug?
