### ISSUE TITLE
After intensive I/O operations I/O locked up [e0b7ba4acdca]

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#490]
After intensive I/O operations I have at least two fs locked, no io to disk. Loong kern.log is here [https://cpy.pt/N4azFk8M](https://cpy.pt/N4azFk8M)

**Comment by phedders** [comment]
I am seeing the same issue on current git (as of 24hrs ago, and since the last week). I do not see anything logged, all writes to the FS are blocked.

What more info can I get to help debug?

I wonder if 0b75db49ea89c1b5b31adf09d6bb28f86883dfd4 might resolve it - compiling now.

**Comment by Gelma** [comment]
> If interested, I can setup a deep investigation. I could enable remote syslog and more debug compile feature in the kernel (I saw in the last days new bcachefs compile options about debugging).

Just for the record, this week first time I didn't have lock ups doing this, and fill up partition without troubles.
Now I repeat it with kasan on.

Dunno which commit fixed this.

**Comment by marcin-github** [comment]
I didn't see it from some time.
