### ISSUE TITLE
alibaba cloud VM and real server boot failed in kernel 6.2.0

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#516]
**Version**
dc2c35d5b4638fc3c569f7630da8782b096fb819

![2023-03-14_18-27](https://user-images.githubusercontent.com/3523160/224974198-fa51098a-ae60-490d-906b-ce334f5ef5d6.png)

![2023-03-14_17-46_1](https://user-images.githubusercontent.com/3523160/224974525-e2308784-8571-4244-b99d-af193de788ab.png)

![2023-03-14_17-46](https://user-images.githubusercontent.com/3523160/224974578-fd60be58-23a5-400e-9ee6-eec4c3b77137.png)

![2023-03-14_16-03](https://user-images.githubusercontent.com/3523160/224974683-4cf94185-baca-4f78-9dda-b6ff8b5f8302.png)

![2023-03-14_16-02](https://user-images.githubusercontent.com/3523160/224974813-61bf4074-6163-447c-9ae5-573903cd8f88.png)

![2023-03-14_16-01_1](https://user-images.githubusercontent.com/3523160/224974953-85706c70-6ece-4e3f-9b75-aa237a616556.png)

I have using the offical kernel source 6.2.6  (https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.2.6.tar.xz)  with the same config (make oldconfig ) .The offical kernel can boot into the system.
 

[config.txt](https://github.com/koverstreet/bcachefs/files/10967340/config.txt)

**Comment by koverstreet** [comment]
try disabling memory allocation profiling/alloc tagging

**Comment by bhzhu203** [comment]
> try disabling memory allocation profiling/alloc tagging

disable  "CONFIG_MEM_ALLOC_PROFILING" solved
