### ISSUE TITLE
Fails boot NULL dereference [0342eebf85b7]

### ISSUE THREAD

**Issue by FlyingWombat** [koverstreet/bcachefs#520]
System occasionally hangs on boot, or shutdown. This happens before bcachefs mount starts.
I captured the system log on one boot failure, and noticed a NULL dereference error.
This only happens with `CONFIG_MEM_ALLOC_PROFILING=y` and `CONFIG_CODE_TAG_TESTING=y`.
Note there are also a series of "allocated at module unload" warnings, that I am omitting from the system log, because they are a know issue with alloc-profiling.
Possible duplicate of #516 

**Version**
bcachefs 0342eebf85b7be76f01bacec8f958c6e6039535b
bcachefs-tools 5bb8ed863c034a338e027be886badd4bfb86f461

**Generic info**
Nixos v6.2.6 
CPU Intel i7-12700k
MB MSI PRO Z690-A WIFI DDR4(MS-7D25)
Notable kernel params:  ibt=off

Kernel options different from Nixos default:
```
MODULE_COMPRESS_ZSTD = yes;
BCACHEFS_FS = yes;
BCACHEFS_QUOTA = yes;
BCACHEFS_POSIX_ACL = yes;
MEM_ALLOC_PROFILING = yes;
CODE_TAG_TESTING = yes;
BCACHEFS_LOCK_TIME_STATS = yes;
BCACHEFS_DEBUG = yes;
PREEMPT = yes;
KALLSYMS = yes;
KALLSYMS_ALL = yes;
DEBUG_FS = yes;
DYNAMIC_FTRACE = yes;
FTRACE = yes;
```
system log:  
Possible items of interest are at lines:  
`59│Mar 16 14:37:51.995482 wombat-pc kernel: alloc_tag was not set`  
`134│Mar 16 14:37:52.411062 wombat-pc kernel: list_add corruption. prev->next should be next `  
`231│Mar 16 14:37:52.424169 wombat-pc kernel: BUG: kernel NULL pointer dereference, address: 0000000000000000`  
`225│Mar 16 14:37:52.543424 wombat-pc kernel: WARNING: CPU: 18 PID: 105 at lib/percpu-refcount.c:197 percpu_ref_switch_to_atomic_rcu`

[wombat-pc-bcachefs-6.2.6-0342eebf85b7-alloc-tag-bootcrash_trim.txt](https://github.com/koverstreet/bcachefs/files/10996449/wombat-pc-bcachefs-6.2.6-0342eebf85b7-alloc-tag-bootcrash_trim.txt)

**Comment by collinmay** [comment]
I've seen similar memory corruption occurring, also when `CONFIG_MEM_ALLOC_PROFILING=y`, which makes me think I'm having the same issue. I'm not sure about the state of the other config option during my testing since I found this issue after bisecting suggested it was related to `CONFIG_MEM_ALLOC_PROFILING`. First buggy commit is dbcc48e0854facc647430fd082f39f64833bbad5.

**Comment by koverstreet** [comment]
Dropped from the bcachefs tree (and I believe this has been fixed in the memory profiling tree); closing this bug.
