### ISSUE TITLE
FS overlap (files corrupted) with snapshots while capacity  is over 85%

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#533]
Mariadb files are  corrupted again while running no issue  over   7 days .  

The  scripts make snapshots and delete snapshots hour/everyday.

This time I have found that the capacity  was over 85% .

version 309e540f841146db6a893a4b702573830a4b3533

**Comment by jpsollie** [comment]
are your snapshot files also corrupted? or only recent ones?

**Comment by bhzhu203** [comment]
> are your snapshot files also corrupted? or only recent ones?

Original files corrupted

**Comment by koverstreet** [comment]
Fixed by 3012736674
