### ISSUE TITLE
linux master rebase

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#54]
~~after a rebase with upstream linux master there were a couple of changes needed - mainly from upstream clean up of unused variables:~~

~~cba20a84cd00522138106ca0613a18b01f283bde~~
~~0645d94f9302d4ae7c43f988f9df9363d5b736ec~~

~~i did not make a pull request as it is a bit massive~~

ignore this, it was my first attempt and the master branch for some reason had some commits twice.

rebasing without the doubly applied commits and with this commit b81d050a4ef4b4ef8e1c8f96cb27cbd247c36a29
i was able to boot to 5.3.0-rc2 and writing this from it

my method was using git rebase -i taking only your commits and applying them to master

e: uptime 3 hours, only dmesg for bcachefs is 
`bucket sector count overflow: 65535 + -128 > U16_MAX`

**Comment by eadwu** [comment]
Not sure about whether or not `cordic.c` was actually removed?

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/math/cordic.c?h=v5.3-rc3

**Comment by nicman23** [comment]
sorry i meant moved to lib/math/cordic.c from lib/cordic.c

**Comment by eadwu** [comment]
Can confirm it works fine in `5.2.6`. Only changes are without the `migrate_page_move_mapping` parameter being removed since it isn't in the stable kernel yet.

For the patch it would probably be better to remove the new `generic_file_buffered_read` change since it'll be present after the rebase.

**Comment by nicman23** [comment]
just to reiterate this is for 5.3 and i have not tested it in 5.2

also for generic_file_buffered_read yes i might have messed that up. oh well, it is unused

**Comment by nicman23** [comment]
updated - on par with master

**Comment by eadwu** [comment]
The [failed] trivial patch for 5.5 which fails with some closure symbols being missing
```diff
diff --git a/fs/bcachefs/checksum.c b/fs/bcachefs/checksum.c
index 6f1afa4a3119..5ece98fe7d01 100644
--- a/fs/bcachefs/checksum.c
+++ b/fs/bcachefs/checksum.c
@@ -13,6 +13,7 @@
 #include <crypto/chacha.h>
 #include <crypto/hash.h>
 #include <crypto/poly1305.h>
+#include <crypto/internal/skcipher.h>
 #include <keys/user-type.h>
 
 static u64 bch2_checksum_init(unsigned type)
diff --git a/fs/bcachefs/journal.h b/fs/bcachefs/journal.h
index ec61137df00a..f0da2c52581c 100644
--- a/fs/bcachefs/journal.h
+++ b/fs/bcachefs/journal.h
@@ -269,7 +269,7 @@ static inline void bch2_journal_res_put(struct journal *j,
 	if (!res->ref)
 		return;
 
-	lock_release(&j->res_map, 0, _THIS_IP_);
+	lock_release(&j->res_map, _THIS_IP_);
 
 	while (res->u64s)
 		bch2_journal_add_entry(j, res,
diff --git a/kernel/locking/six.c b/kernel/locking/six.c
index 9fa58b6fadc9..c778123505d0 100644
--- a/kernel/locking/six.c
+++ b/kernel/locking/six.c
@@ -15,7 +15,7 @@
 #endif
 
 #define six_acquire(l, t)	lock_acquire(l, 0, t, 0, 0, NULL, _RET_IP_)
-#define six_release(l)		lock_release(l, 0, _RET_IP_)
+#define six_release(l)		lock_release(l, _RET_IP_)
 
 struct six_lock_vals {
 	/* Value we add to the lock in order to take the lock: */
```

```
Kernel: arch/x86/boot/bzImage is ready  (#1)
ERROR: "closure_sub" [drivers/md/bcache/bcache.ko] undefined!
ERROR: "__closure_wake_up" [drivers/md/bcache/bcache.ko] undefined!
ERROR: "closure_put" [drivers/md/bcache/bcache.ko] undefined!
ERROR: "__closure_sync" [drivers/md/bcache/bcache.ko] undefined!
ERROR: "closure_wait" [drivers/md/bcache/bcache.ko] undefined!
ERROR: "closure_sub" [fs/bcachefs/bcachefs.ko] undefined!
ERROR: "__closure_wake_up" [fs/bcachefs/bcachefs.ko] undefined!
ERROR: "closure_put" [fs/bcachefs/bcachefs.ko] undefined!
ERROR: "__closure_sync" [fs/bcachefs/bcachefs.ko] undefined!
ERROR: "closure_wait" [fs/bcachefs/bcachefs.ko] undefined!
make[2]: *** [../scripts/Makefile.modpost:94: __modpost] Error 1
make[1]: *** [/build/linux-5.5-rc6/Makefile:1282: modules] Error 2
make: *** [../Makefile:179: sub-make] Error 2
```

**Comment by eadwu** [comment]
The fix was actually pretty straightforward, I just for some reason never decided to look at the log for `closure.c`. https://github.com/eadwu/bcachefs/commit/183fcbaaceef5bd32042bbd60954ec4415aeb6a1
