### ISSUE TITLE
Files on original subvolume are corrupted when writing into snapshots

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs#544]
vesion 5729a4cb0775a8bc15de33fbf481a719dc01a5ee

The original subvolume keep runing a mariadb instance whith slave writing. At the same time a script make FS snaphots every 10mins . Another script delete snaphots and keep snapshots in 2 days.  As now on , it works well.

But when I running a recovery instance on a snapshot ,after 20 minutes , the original mariadb has files corrpution. docker run -it --name  1684381801  -p 3306 -v /data/snapshots/1684381801/mysql:/mysql mariadb-copy /start.sh

![图片](https://github.com/koverstreet/bcachefs/assets/3523160/2e36be7a-68c6-461a-86be-d5999013d38d)

**Comment by koverstreet** [comment]
Does the recovery process write to the snapshot?

**Comment by bhzhu203** [comment]
> Does the recovery process write to the snapshot?

Yes , a new mariadb process

**Comment by koverstreet** [comment]
Fixed by 3012736674
