### ISSUE TITLE
How would I go about adding different compression level support?

### ISSUE THREAD

**Issue by chayleaf** [koverstreet/bcachefs#557]
My server has a super slow HDD. Obviously I can just patch my kernel to make whatever zstd level I want to use the default, but if I want to contribute it as a feature, would this be the correct plan of action:

- add `compression_level` and `background_compression_level` options (I guess it's fine to make it u8, though zstd supports negative compression levels)
- Create a copy of `bch_fs`'s `zstd_params` struct field for background compression (as the levels could be different), and for other algos store the compression level (a union could be used)

Finally, there are three options from there:
- Store the compression level on the filesystem, the sole reason being so that background_compression knows it needs to recompress the files with the updated settings
- Don't store it, make this a "suggestion" for newly compressed files only, as the compression level isn't needed for decompression (this is what btrfs does).
- Or a middle ground - store whether the data has been compressed be the foreground or background compressor, and assume that level had been used unless the algorithm is different.

While the first and third choice are more "robust", it is much much easier to implement the second one for obvious reasons. Would such a feature be accepted? It could potentially be extended in the future by storing the compression level on the filesystem.

As far as I understand, the first solution would be challenging as adding the compression level to extent data is undesirable (there's no space for it right now), making it an inode field is a possibility, but I'd have to make rebalancing aware of that, which seems unlikely.

The third solution is to store a flag in extent data (most significant bit of compression type - 8 compression types seems like it's plenty for a very long time, or the unused bit) specifying whether something was compressed with background or foreground compression (for cases such as "foreground compression uses zstd:3, background compression uses zstd:15"), it would only take one bit of storage but wouldn't be as precise in case those options are changed.

Also, shouldn't this

```c
struct bch_extent_crc32 {
#if defined(__LITTLE_ENDIAN_BITFIELD)
        __u32                   type:2,
                                _compressed_size:7,
                                _uncompressed_size:7,
                                offset:7,
                                _unused:1,
                                csum_type:4,
                                compression_type:4;
        __u32                   csum;
#elif defined (__BIG_ENDIAN_BITFIELD)
        __u32                   csum;
        __u32                   compression_type:4,
                                csum_type:4,
                                _unused:1,
                                offset:7,
                                _uncompressed_size:7,
                                _compressed_size:7,
                                type:2;
#endif
} __packed __aligned(8);
```

be defined as

```c
struct bch_extent_crc32 {
#if defined(__LITTLE_ENDIAN_BITFIELD)
        __u32                   type:2,
                                _compressed_size:7,
                                _uncompressed_size:7,
                                offset:7,
                                _unused:1,
                                csum_type:4,
                                compression_type:4;
#elif defined (__BIG_ENDIAN_BITFIELD)
        __u32                   compression_type:4,
                                csum_type:4,
                                _unused:1,
                                offset:7,
                                _uncompressed_size:7,
                                _compressed_size:7,
                                type:2;
#endif
        __u32                   csum;
} __packed __aligned(8);
```

instead?

**Comment by Valmar33** [comment]
Am rather interested in this.

**Comment by ojab** [comment]
https://github.com/koverstreet/bcachefs/commit/e14d7c7195b974bbaf400f9c3f2bdaa94fc8d372
