### ISSUE TITLE
bcachefs device remove: BCH_IOCTL_DISK_REMOVE ioctl error: Invalid argument

### ISSUE THREAD

**Issue by stintel** [koverstreet/bcachefs#56]
Unable to remove devices:
```
ministore /usr/src/bcachefs-tools # ./bcachefs device remove /dev/sdg
BCH_IOCTL_DISK_REMOVE ioctl error: Invalid argument
```
This is with a single bcachefs mounted. Running commit 9ef7b784cb7eed750893b7aa4957681fdcfb8ff6

```
ministore /usr/src/bcachefs-tools # ls -l  /sys/fs/bcachefs/df917528-5b27-4c3b-9396-7df0f5364729/dev-*/block
lrwxrwxrwx 1 root root 0 Aug 21 14:29 /sys/fs/bcachefs/df917528-5b27-4c3b-9396-7df0f5364729/dev-0/block -> ../../../../devices/pci0000:00/0000:00:01.1/0000:02:00.0/host6/port-6:1/end_device-6:1/target6:0:1/6:0:1:0/block/sdc
lrwxrwxrwx 1 root root 0 Aug 21 14:29 /sys/fs/bcachefs/df917528-5b27-4c3b-9396-7df0f5364729/dev-1/block -> ../../../../devices/pci0000:00/0000:00:14.0/usb4/4-2/4-2:1.0/host8/target8:0:0/8:0:0:0/block/sdg
```

I will try to bisect later.

**Comment by stintel** [comment]
I should have checked dmesg:
```
[  938.500512] bcachefs (sdg): Cannot remove without losing data
```
But then after evacuating the device, I still cannot remove it:
```
ministore /usr/src/bcachefs-tools # ./bcachefs device evacuate /dev/sdg
0% complete: current position none
Done
ministore /usr/src/bcachefs-tools # ./bcachefs device remove /dev/sdg
BCH_IOCTL_DISK_REMOVE ioctl error: Invalid argument
```

**Comment by stintel** [comment]
Did some more testing, and it appears this is because of replicas=1. There are two disks, each in their own disk group. Are we not supposed to be able to remove disks in this case, even after evacuate? After changing data_replicas and metadata_replicas to 2, I was able to remove one of the disks from the filesystem.

**Comment by demizer** [comment]
I am also experiencing this error when I try to remove a failed device (completely disappeared from /dev/disk/by-id, device is DEAD).

Command: `sudo bcachefs device remove 5 /mnt/data`

I created the pool using two replicas and two metadata replicas, so not sure why I am getting "cannot remove without losing data". I wish the error were more descriptive. Perhaps add a arg to show detailed info?

**Comment by trougnouf** [comment]
I am experiencing the same issue with Linux 6.14.2 / bcachefs-tools 3:1.25.1
