### ISSUE TITLE
Commits b2827b1 "mm: vmalloc: Enable memory allocation profiling" and 400b3ab "memory allocation profiling: more hooking" break compiling

### ISSUE THREAD

**Issue by hardfalcon** [koverstreet/bcachefs#567]
Some change(s) between commit 6059c459e8b13d6ae25efc4d0169edc4e0bcb867 and commit 1320de26ee1fb9ebdd7c1b1752af53852512e823 break compiling the kernel on Archlinux Testing with GCC 131.1 for me in several places. My primary suspect is commit b2827b1f6d4bb1a067c022f77db49be932591b5c.

I'm using kernel 6.4.3 with the following changes added on top:
- all [patches from the stable queue](https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/temp-6.4?h=v6.4.3) (except for `netfilter-nf_tables-unbind-non-anonymous-set-if-rule.patch`, because the changes from that commit are already included in the `linux-hardened` patch mentioned further down),
- a custom patch integrating [v4l2loopback](https://github.com/umlaeute/v4l2loopback/tree/9ba7e294ea6f45410a15f192381d4918e8df4f02),
- a rebased version of the [bcachefs-testing branch @ commit 1320de26ee1fb9ebdd7c1b1752af53852512e823](https://github.com/koverstreet/bcachefs/tree/1320de26ee1fb9ebdd7c1b1752af53852512e823),
  1320de26ee1fb9ebdd7c1b1752af53852512e823,
- a rebased version of the [linux-hardened patch](https://github.com/anthraxx/linux-hardened/releases/tag/6.4.2-hardened1) (as mentioned above, this requires dropping `netfilter-nf_tables-unbind-non-anonymous-set-if-rule.patch` from the stable-queue patches),
- a [patch](https://github.com/hardfalcon/linux-hardened/commit/e150834d9e5d19754daf7724d72a46073ed288ac) disabling all `RNDIS` protocol drivers,
- a [patch](https://github.com/hardfalcon/linux-hardened/commit/ea530fb715107d4a2d4104b4841a4aa209513f7b) restricting access to `TIOCLINUX` selection functions,
- a trivial custom [patch](https://github.com/hardfalcon/linux-hardened/commit/e150834d9e5d19754daf7724d72a46073ed288ac) disabling `IO_URING` by default.

I know this sounds like "probably an issue with one of all those other patches". However, I've successfully built a functioning kernel with the very same changes/patches just a few hours before (the only differences being the kernel 6.4.3 changes taken from the stable queue instead of the kernel tarball, because 6.4.3 was not released yet when I started the first/successfull compile run, and the rebased bcachefs patch being derived from the [bcachefs-testing branch @ commit 1320de26ee1fb9ebdd7c1b1752af53852512e823](https://github.com/koverstreet/bcachefs/tree/1320de26ee1fb9ebdd7c1b1752af53852512e823) instead of the [bcachefs-testing branch @ commit 6059c459e8b13d6ae25efc4d0169edc4e0bcb867](https://github.com/koverstreet/bcachefs/tree/6059c459e8b13d6ae25efc4d0169edc4e0bcb867)

Thereforce, I'm reaonably confident that these issues are caused by some change(s) between commit 6059c459e8b13d6ae25efc4d0169edc4e0bcb867 and commit 1320de26ee1fb9ebdd7c1b1752af53852512e823 break compiling the kernel for me in several places, most likely commit b2827b1f6d4bb1a067c022f77db49be932591b5c.

I've attached a combined stdout/stderr log, and a tarball containing the PKGBUILD and all patches I've used.
[stdouterrcombined.log](https://github.com/koverstreet/bcachefs/files/12013282/stdouterrcombined.log)
[linux-hardened-6.4.3.hardened0-0.src.tar.gz](https://github.com/koverstreet/bcachefs/files/12013297/linux-hardened-6.4.3.hardened0-0.src.tar.gz)

**Comment by hardfalcon** [comment]
Update: Dropping commit b2827b1f6d4bb1a067c022f77db49be932591b5c was *part* of the solution but not enough to get the kernel to compile. I also had to drop commit c4f23a088fa3f23700a177307e388365394e9e26 for the compiling to actually succeed.

When I only drop commit b2827b1f6d4bb1a067c022f77db49be932591b5c but keep commit c4f23a088fa3f23700a177307e388365394e9e26, `modpost` complains about `kmemdup` being undefined in various filesystem modules:

```
  LD [M]  drivers/infiniband/hw/hfi1/hfi1.o
  AR      built-in.a
  AR      vmlinux.a
  LD      vmlinux.o
  OBJCOPY modules.builtin.modinfo
  GEN     modules.builtin
  GEN     .vmlinux.objs
  MODPOST Module.symvers
ERROR: modpost: "kmemdup" [fs/fscache/fscache.ko] undefined!
ERROR: modpost: "kmemdup" [fs/reiserfs/reiserfs.ko] undefined!
ERROR: modpost: "kmemdup" [fs/ext4/ext4.ko] undefined!
ERROR: modpost: "kmemdup" [fs/nfs/nfs.ko] undefined!
ERROR: modpost: "kmemdup" [fs/nfs/blocklayout/blocklayoutdriver.ko] undefined!
ERROR: modpost: "kmemdup" [fs/nfsd/nfsd.ko] undefined!
ERROR: modpost: "kmemdup" [fs/smb/client/cifs.ko] undefined!
ERROR: modpost: "kmemdup" [fs/smb/server/ksmbd.ko] undefined!
ERROR: modpost: "kmemdup" [fs/ntfs3/ntfs3.ko] undefined!
ERROR: modpost: "kmemdup" [fs/jffs2/jffs2.ko] undefined!
WARNING: modpost: suppressed 269 unresolved symbol warnings because there were too many)
WARNING: modpost: modpost: Found 55299 writable function pointers.
To see full details build your kernel with:
'make CONFIG_DEBUG_WRITABLE_FUNCTION_POINTERS_VERBOSE=y'
make[1]: *** [scripts/Makefile.modpost:137: Module.symvers] Error 1
make: *** [Makefile:1978: modpost] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by hardfalcon** [comment]
See also https://github.com/koverstreet/bcachefs/issues/566

**Comment by koverstreet** [comment]
Did you try a make clean?

**Comment by hardfalcon** [comment]
I always build in a clean chroot using the procedure described here: https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Convenience_way

I do use this with an additional custom repo, but I'm reasonably confident that that repo isn't relevant for this bug because, as described above, essentially the same kernel/codebase built cleanly last night when I used a bcachefs patch created from running `git diff` on a rebased 6059c459e8b13d6ae25efc4d0169edc4e0bcb867 vs. a vanilla kernel 6.4.2.

**Comment by Mjasnik** [comment]
I have the same compilation error and I always cleanbuild the package. In ArchLinux that's easy, `makepkg -sfc`

My build routine is as follows:
1. delete build dir, all of it
2. pull latest changes from linux-stable
3. export git to build dir
4. apply PDS (CPU scheduler patches)
5. pull latest changes from bcachefs
6. get bcachefs patch and apply it to build dir
7. compile

**Comment by hardfalcon** [comment]
@koverstreet: FYI, this is still broken as of 0e34fff3bdce77254eb4fc1f822d9b3e13e6caa5 (rebased onto kernel 6.4.4):
```
  CC [M]  drivers/staging/media/ipu3/ipu3-v4l2.o
In file included from ./include/linux/printk.h:564,
                 from ./include/linux/kernel.h:30,
                 from drivers/staging/media/atomisp/pci/hmm/hmm.c:23:
drivers/staging/media/atomisp/pci/hmm/hmm.c: In function ‘__hmm_alloc’:
drivers/staging/media/atomisp/pci/hmm/hmm.c:208:41: error: ‘vmalloc’ undeclared (first use in this function); did you mean ‘mm_alloc’?
  208 |                 bo->start, bytes, type, vmalloc);
      |                                         ^~~~~~~
./include/linux/dynamic_debug.h:222:29: note: in definition of macro ‘__dynamic_func_call_cls’
  222 |                 func(&id, ##__VA_ARGS__);                       \
      |                             ^~~~~~~~~~~
./include/linux/dynamic_debug.h:248:9: note: in expansion of macro ‘_dynamic_func_call_cls’
  248 |         _dynamic_func_call_cls(_DPRINTK_CLASS_DFLT, fmt, func, ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/dynamic_debug.h:271:9: note: in expansion of macro ‘_dynamic_func_call’
  271 |         _dynamic_func_call(fmt, __dynamic_dev_dbg,              \
      |         ^~~~~~~~~~~~~~~~~~
./include/linux/dev_printk.h:155:9: note: in expansion of macro ‘dynamic_dev_dbg’
  155 |         dynamic_dev_dbg(dev, dev_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~
drivers/staging/media/atomisp/pci/hmm/hmm.c:207:9: note: in expansion of macro ‘dev_dbg’
  207 |         dev_dbg(atomisp_dev, "pages: 0x%08x (%zu bytes), type: %d, vmalloc %p\n",
      |         ^~~~~~~
drivers/staging/media/atomisp/pci/hmm/hmm.c:208:41: note: each undeclared identifier is reported only once for each function it appears in
  208 |                 bo->start, bytes, type, vmalloc);
      |                                         ^~~~~~~
./include/linux/dynamic_debug.h:222:29: note: in definition of macro ‘__dynamic_func_call_cls’
  222 |                 func(&id, ##__VA_ARGS__);                       \
      |                             ^~~~~~~~~~~
./include/linux/dynamic_debug.h:248:9: note: in expansion of macro ‘_dynamic_func_call_cls’
  248 |         _dynamic_func_call_cls(_DPRINTK_CLASS_DFLT, fmt, func, ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/dynamic_debug.h:271:9: note: in expansion of macro ‘_dynamic_func_call’
  271 |         _dynamic_func_call(fmt, __dynamic_dev_dbg,              \
      |         ^~~~~~~~~~~~~~~~~~
./include/linux/dev_printk.h:155:9: note: in expansion of macro ‘dynamic_dev_dbg’
  155 |         dynamic_dev_dbg(dev, dev_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~
drivers/staging/media/atomisp/pci/hmm/hmm.c:207:9: note: in expansion of macro ‘dev_dbg’
  207 |         dev_dbg(atomisp_dev, "pages: 0x%08x (%zu bytes), type: %d, vmalloc %p\n",
      |         ^~~~~~~
  CC [M]  drivers/platform/chrome/cros_ec_lpc.o
make[5]: *** [scripts/Makefile.build:252: drivers/staging/media/atomisp/pci/hmm/hmm.o] Error 1
make[4]: *** [scripts/Makefile.build:494: drivers/staging/media/atomisp] Error 2
make[4]: *** Waiting for unfinished jobs....
```

In case it's relevant or it helps you tracking down when/where this issue is originating from: I have tried building a kernel like a dozen times this week alone, each time with the latest state of your bcachefs-testing branch rebased upon the latest state of Greg-KH's linux-6.4.y branch, and it consistently failed each and every time.

**Comment by hardfalcon** [comment]
I was on holiday for a few weeks, so I haven't been able to follow the changes here as closely, but it seems that at least as of commit 07bb798f7d25d28978a3defc89863aab3409dc1a, this issue has been solved.
