### ISSUE TITLE
v6.4 Compilation Error [f37513acffac21a08b7d8078c692ce719d84166a]

### ISSUE THREAD

**Issue by Butyllithium** [koverstreet/bcachefs#572]
Hi,  I encountered an error while trying to compile. This is the error message I received when running the `make -j16` command with regular user privileges.

[Makelogs_orgin.txt](https://github.com/koverstreet/bcachefs/files/12041317/Makelogs_orgin.txt)

I am in China, and I tried to import the environment variables, but it didn't take effect. Here is the translated version:

[Makelogs_English.txt](https://github.com/koverstreet/bcachefs/files/12041128/Makelogs_English.txt)

I have imported the following compilation flags:
```
CONFIG_PREEMPT=y
CONFIG_BCACHEFS_DEBUG=y
CONFIG_KALLSYMS=y
CONFIG_KALLSYMS_ALL=y
CONFIG_DEBUG_FS=y
CONFIG_DYNAMIC_FTRACE=y
CONFIG_FTRACE=y
```
This is my .config file.
[config.txt](https://github.com/koverstreet/bcachefs/files/12041417/config.txt)

This is my `dmesg` output.

[dmesg_output.txt](https://github.com/koverstreet/bcachefs/files/12045718/dmesg_output.txt)

English is not my native language; please excuse typing errors.

**Comment by koverstreet** [comment]
should be fixed
