### ISSUE TITLE
Goes readonly mode after few minutes of uptime

### ISSUE THREAD

**Issue by NikolayKuzmin** [koverstreet/bcachefs#602]
**Version**
6.5.6.arch2.r1204816.6628827a8707
bcachefs v0.1-749-gd320a4e

**Generic info**
show super:
[showsuper.txt.gz](https://github.com/koverstreet/bcachefs/files/13218944/showsuper.txt.gz)
fs usage:
[fsusage.txt.gz](https://github.com/koverstreet/bcachefs/files/13218947/fsusage.txt.gz)
dmesg:   
[dmesg.txt.gz](https://github.com/koverstreet/bcachefs/files/13218931/dmesg.txt.gz)

bcachefs fsck during initramfs startup fixes unknown journal entries and removes zero-link inodes, but after booting to session filesystem goes readonly complaining about unknown journal entries. Problem was stable, I've met it 5 times in a row after upgrading. Downgrading to  6.5.6.arch2.r1204800.60f309231120 had fixed this problem

**Comment by koverstreet** [comment]
Your dmesg log didn't include the relevant errors - reopen if you can get the correct logs.
