### ISSUE TITLE
Mounting a bcachefs subvolume

### ISSUE THREAD

**Issue by shmerl** [koverstreet/bcachefs#612]
Not sure if this is the right place to open a feature request, but it would be nice for bcachefs to support subvolume mounting, similar to how btrfs supports it.

I.e. doing something like:

```
mount -o subvol=foo <device> <path>
```

This would allow a neat way to mount them without the need to mount the main filesystem somewhere first.

**Comment by Madouura** [comment]
This might be better suited in https://github.com/koverstreet/bcachefs-tools.
AFAIK there isn't anything kernel-wise preventing you from mounting a subvolume?
Btrfs subvolumes (API-wise) are just folders on root too.

**Comment by shmerl** [comment]
Thanks, for the pointer, opened: https://github.com/koverstreet/bcachefs-tools/issues/181

I'll close it here then.
