### ISSUE TITLE
Erasure code: pointer to nonexistent stripe 1003

### ISSUE THREAD

**Issue by nadalle** [koverstreet/bcachefs#62]
I created a VM with erasure code, and got this error after some light load (copying a kernel tree into the filesystem, writing a few large files):

```
Aug 22 15:28:20 hekate kernel: [  199.222019] bcachefs (aa02aed4-5d7e-49ac-9e75-1acc2e8d7259): pointer to nonexistent stripe 1003
Aug 22 15:28:20 hekate kernel: [  199.222030] bcachefs (aa02aed4-5d7e-49ac-9e75-1acc2e8d7259): emergency read only
```

Device layout:
SSD tier: 2 disks, 11 GiB
HDD tier: 3 disks, 99 GiB

SSD tier is the promote_target
HDD tier is the background_target and the foreground_target

Replicas = 2

Mount options: erasure_code=1

A dump of the filesystem was previously sent to koverstreet in a file: nonexistant-strip-1003.tar.xz

The kernel was built from revision 14f68409bec43faff9d7480632488def385e0638
on Aug 22, 2019.

**Comment by koverstreet** [comment]
Fixed by a7c3679ec9
