### ISSUE TITLE
Restoring from a snapshot fails

### ISSUE THREAD

**Issue by guzz46** [koverstreet/bcachefs#623]
Transferring a file from a snapshot to the directory that the snapshot was taken from fails, the file transfers OK, and the size of the file is correct, but the contents are empty, however transferring a file from the snapshot to another drive works fine.

**Comment by guzz46** [comment]
So I created a new snapshot and this time transferring files back to the same partition works fine.

**Comment by koverstreet** [comment]
Fixed by ccb84ff7cbb6
