### ISSUE TITLE
bcachefs fsck should check if filesystem is mounted

### ISSUE THREAD

**Issue by nadalle** [koverstreet/bcachefs#63]
A user on IRC reported that they destroyed their filesystem by running bcachefs fsck while mounted.

They stated that they'd erroneously believed that bcachefs had online fsck, and would use some sort of syscall to verify its state safely.

The bcachefs tool should verify the filesystem is unmounted and print an error before running destructive operations.

**Comment by koverstreet** [comment]
I just tested this, on both single device and multi device filesystems

# bcachefs fsck /dev/sdb
/dev/sdb is mounted read-write - aborting

If someone figures out a way to get fsck to run on a mounted fs, reopen...
