### ISSUE TITLE
New array with 4k - dead in 3 days time

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#65]
A standard formated array with 2 drives in background and a nvme in foreground/ promote results in many many io errors on the nvme. Created with:

```
bcachefs format --replicas=1 --background_target=hdd --block_size=4k  --group hdd /dev/sdb1 /dev/sdc1 \
--foreground_target=nvme --promote_target=nvme --group nvme /dev/nvme0n1p2
```

The array was created 3 days ago and now I all have to recreate it due to fix_errors,reconstruct_alloc not being able to fix it. 

The machine was frozen with the latest master and I have to sysrq it, after that with norecovery and rsync it spouts out this ![photo6030657949791268856](https://user-images.githubusercontent.com/16306097/64550750-43c51a00-d33c-11e9-82f6-c91a43fe4408.jpg)

[dmesg.txt](https://github.com/koverstreet/bcachefs/files/3591720/dmesg.txt)

**Comment by marcin-github** [comment]
Isn't related to issue #64 and issue #61 ?

**Comment by nicman23** [comment]
for 61 no for 64 i am not sure

**Comment by nicman23** [comment]
another array now with 512 sectors died, displaying #61

**Comment by setreadygo** [comment]
Make sure you check that you don't have a bad SATA cable or chipset on your hdds. One of my sata controllers was slowly dying, we also both had the makepkg issue with archlinux. I was getting tons of checksum errors like you. I was first getting failures in bcfs and then started to get it with ext4/btrfs. Took me a month of random failures for me to figure that one out...... Stupid maxwell chips.

**Comment by nicman23** [comment]
i do have some old sata cables but the thing is that with the backport branch i did not have any issues

**Comment by koverstreet** [comment]
I'm starting to strongly suspect a bug in the block layer, not bcachefs. I just synced the bcachefs-v4.19-backport branch with current master - can you give that a try?

**Comment by nicman23** [comment]
sure but it might take some days for the issue to surface

**Comment by nicman23** [comment]
so far so good, i did have some hangs with qemu and windows vms but it might be the old kernel not being happy with ryzen + new asega
