### ISSUE TITLE
QUESTION: Erasure coding status?

### ISSUE THREAD

**Issue by TurkeyMan** [koverstreet/bcachefs#657]
Sorry to post a question to the issue tracker.

Where are we at with erasure coding? I'm upgrading a media server, which is a large storage pool of relatively low importance data. I want to move away from ZFS since it's so inflexible, and I want tiered access.
Is bcachefs ready to try out, or still too early?
I have 6x 16tb drives to start with, intending to use 2 parity in a raid-6 style configuration, and the intention is to expand it progressively. I'll also add an SSD as a promote target.

If something goes catastrophically wrong, the data isn't particularly sensitive.
Should I try this?

**Comment by nrdxp** [comment]
I noticed that, even with erasure coding turned on, that parity was always listed as 0 with `bcachefs fs usage`, and I found the `CONFIG_BCACHEFS_ERASURE_CODING` kernel config option which is not set by default, so I assume it is disabled at the kernel level by default, and given the warning at the cli level: `--erasure_code          Enable erasure coding (DO NOT USE YET)`, I'd assume it's not ready for production yet.

**Comment by koverstreet** [comment]
yeah. Code wise it's close, but I am _swamped_ with other things, it needs thorough testing and I can't handle the additional debugging load right now
