### ISSUE TITLE
Installing OS to a VM on a bcachefs raid1 array leads to hang

### ISSUE THREAD

**Issue by reivanen** [koverstreet/bcachefs#661]
I have been trying to install ubuntu 22.04 to a linux 6.8 kvm qcow2 file (nocow) on a bcachefs relicas=2 filesystem, but it is freezing mid install (happened 2 times) 

The host journal log show this kind of messages:

17:19:13 kernel:  ? bch2_btree_iter_peek_slot+0x18b/0x740 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  __bch2_bucket_nocow_lock+0xb7/0x120 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  bch2_nocow_write+0x8c3/0x11c0 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  ? __bch2_write+0xdaf/0x13b0 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  __bch2_write+0xdaf/0x13b0 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  ? __bch2_increment_clock+0x2d/0x140 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  ? bch2_direct_write+0x6f9/0xce0 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  bch2_direct_write+0x6f9/0xce0 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]
17:19:13 kernel:  bch2_write_iter+0x142/0xc70 [bcachefs f393ee8538d649baab95f28547fea17a03dfef18]

And when i try to kill -9 the stuck virtual machine process nothing happens. It seems it has fucked up the kernel so bad it is unable to kill the process.

**Comment by reivanen** [comment]
not only did the install lead to a hang but it seems probable also a couple previous VM crashes are related to this also.

Sad that no engagement has happened.

Best way to have no problems is to ignore all problems.

**Comment by koverstreet** [comment]
It's only been 2 days and I've been busy with helping a user recover from actual data loss.

I'll get to this, be patient.

**Comment by reivanen** [comment]
Thank you for acknowledging,  but there is probably little more to be had regarding this because i had to reformat to ext4 to keep things going and no important data was at issue. Gotta love modern world where 1 TB can just be considered ephemeral ;)

**Comment by reivanen** [comment]
notice the error messages printed are not started by bcachefs: and i only found out about them because they contain bcachefs before the uuid, which i grepped with.

**Comment by colttt** [comment]
can you please post how you create you bcachefs and also the superblock

**Comment by reivanen** [comment]
i cannot post the superblock obviously as it does not exist. How i created the filesystem? As every guide tells you. Aside from label to both disks i only specified --replicas=2 ... and then set attribute --nocow on the virtual image file.

**Comment by andy-amii** [comment]
I suspect this and #662 might be closely related.

**Comment by koverstreet** [comment]
Sorry for the long delay in getting to this; I'm going to close this since you said you reformatted, but please reopen if you're still able to hit this and willing to test a fix.

The first thing I'll need is a better backtrace - I'm not sure what that is from your kernel log, but it doesn't look like a legit backtrace. Make sure you're compiling your kernel with frame pointers to get that.
