### ISSUE TITLE
bcachefs cannot be used as the root directory

### ISSUE THREAD

**Issue by kindusmithkindu** [koverstreet/bcachefs#666]
In Linuxmint, if you do this, you will be prompted that the disk cannot be found when starting grub because the file system is not supported. I can repair grub and manually boot into the system, but it is too troublesome every time. This is what I have done before. After a few days of trying bcachafs, I can’t recall the specific details, so I fell back to ext4.

**Comment by bhzhu203** [comment]
Maybe you could try Bcachefs in the /home directory .Grub2 does not support Bcachefs yet.
