### ISSUE TITLE
Data Recovery Questions

### ISSUE THREAD

**Issue by Ironlenny** [koverstreet/bcachefs#676]
So I was a dumbass and intentionally overwrote my Bcachefs caching device during a system upgrade, thinking I could just mount the backing device. I honestly don't know what I was thinking.

What options do I have to recover my data? Is it possible to attach the backing device to a bcache device? To a new bcachefs filesystem? Will a utility like TestDisk help? Am I just hosed?

Edit: I do have backups, but I don't know how recent they are.

**Comment by raldone01** [comment]
What was the setup of your bcachefs? (Format command)

If you plug in all the remaining drives and try to mount one of them what is the error output in your terminal and dmesg?

You may be able to recover some data by mounting with `fsck,fix_errors` mount options. You should create a backup copy (dd or pv) of all bcache drives before doing so. Also unplug the backups and verify them on another machine to avoid further human error.

**Comment by notcancername** [comment]
Out of curiosity: since cache devices have `durability=0`, shouldn't mounting the backing device be perfectly fine?

**Comment by raldone01** [comment]
Well it depends on the type of cache that was used. A writeback cache would be problematic. A write through cache _should_ be no problem. That's why I asked for the format command.

**Comment by Ironlenny** [comment]
Forgot this was open. I found a recent enough backup so I stop trying to recover the filesystem. But to answer you alls questions, I had the caching device set to `durability=1` and `writeback`. I was interested in performance as it was for my workstation.

**Comment by Ironlenny** [comment]
Forgot this was open. I found a recent enough backup so I stop trying to recover the filesystem. But to answer you alls questions, I had the caching device set to `durability=1` and `writeback`. I was interested in performance as it was for my workstation.
