### ISSUE TITLE
Ran out of journal space.

### ISSUE THREAD

**Issue by YellowOnion** [koverstreet/bcachefs#699]
Journal space runs out on latest "for-upstream" branch.

revert to 6.9 works.

**Comment by koverstreet** [comment]
you know the deal, post a log

**Comment by YellowOnion** [comment]
![20240626_165624_8479364282372040011_20240626183353.jpg](https://github.com/koverstreet/bcachefs/assets/364160/d44d80af-5ecd-46cf-b65b-120d096171a9)

@koverstreet

**Comment by koverstreet** [comment]
that's not the journal running out of space, that's mount getting interrupted by a signal, doofus

**Comment by koverstreet** [comment]
that's probably it
and no, the bug isn't in tools, we just have no way to disable checking for pending signals in a general way
