### ISSUE TITLE
Can't mount anymore. ERROR - bcachefs::commands::mount: Fatal error: No such file or directory

### ISSUE THREAD

**Issue by dflvunoooooo** [koverstreet/bcachefs#702]
Since the last update I am unable to mount my hdd. I am using arch linux and try to mount a 10 Gb WD Red hdd. If I try to mount, I get the error `ERROR - bcachefs::commands::mount: Fatal error: No such file or directory`. It doesn't matter how I try to mount, `bcachefs mount /dev/mapper/daten /mnt-filme`, `bcachefs mount -k wait /dev/mapper/daten /mnt-filme`, `bcachefs mount /dev/mapper/daten /mnt-filme -o ro,fsck,no_splitbrain_check,fix_errors`, `mount -t bcachefs /dev/mapper/daten /mnt-filme` all do not work. 
dmsg reports about bcachefs:
```
[  +0,099012] bcachefs (dm-0): mounting version 1.7: mi_btree_bitmap opts=nojournal_transaction_names
[  +0,000004] bcachefs (dm-0): recovering from unclean shutdown
[  +0,000002] bcachefs (dm-0): superblock requires following recovery passes to be run:
                check_subvols,check_dirents
[  +0,000004] bcachefs (dm-0): Version upgrade from 1.3: rebalance_work to 1.7: mi_btree_bitmap incomplete
              Doing compatible version upgrade from 1.3: rebalance_work to 1.7: mi_btree_bitmap
                running recovery passes: check_allocations
[ 1. Jul 16:14] bcachefs (dm-0): journal read done, replaying entries 735901-735901
[  +0,374787] bcachefs (dm-0): alloc_read... done
[  +0,000734] bcachefs (dm-0): stripes_read... done
[  +0,000011] bcachefs (dm-0): snapshots_read... done
[  +0,000223] bcachefs (dm-0): check_allocations... done
[ 1. Jul 16:18] bcachefs (dm-0): going read-write
[  +0,002373] bcachefs (dm-0): journal_replay... done
[  +0,000487] bcachefs (dm-0): check_subvols...
[  +0,000310] bcachefs (dm-0): check_subvol: snapshot tree 0 not found
[  +0,000223] bcachefs (dm-0): inconsistency detected - emergency read only at journal seq 735910
[  +0,000030] bcachefs (dm-0): bch2_check_subvols(): error ENOENT_snapshot_tree
[  +0,000041] bcachefs (dm-0): unable to write journal to sufficient devices
[  +0,001960] bcachefs (dm-0): bch2_fs_recovery(): error ENOENT_snapshot_tree
[  +0,000136] bcachefs (dm-0): bch2_fs_start(): error starting filesystem ENOENT_snapshot_tree
[  +0,001886] bcachefs (dm-0): unshutdown complete, journal seq 735910
```

Some information 
```
[henry@mopsam ~]$  uname -a
Linux mopsam 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux

[henry@mopsam ~]$ find /lib/modules/$(uname -r) -type f -name '*.ko*' |grep bcachefs
/lib/modules/6.9.7-arch1-1/kernel/fs/bcachefs/bcachefs.ko.zst

[henry@mopsam ~]$  cat /proc/filesystems |grep bcachefs
        bcachefs

local/bcachefs-tools 3:1.9.2-1
    BCacheFS filesystem utilities
```
I don't know what to do. Any help would be very welcome.

**Comment by jpsollie** [comment]
this is likely due to metadata corruption in the kernel that has the 1.3 version.
If you have this kernel still lying around, can you check it with in-kernel fsck? meaning: mount -o fsck,force_repair=yes (dev) (random mountpoint).
if that is clean, you may be able to try a vanilla 6.8 kernel first before going to 6.9

**Comment by dflvunoooooo** [comment]
> this is likely due to metadata corruption in the kernel that has the 1.3 version. If you have this kernel still lying around, can you check it with in-kernel fsck? meaning: mount -o fsck,force_repair=yes (dev) (random mountpoint). if that is clean, you may be able to try a vanilla 6.8 kernel first before going to 6.9

I tried every kernel from 6.8.1 to 6.8.9 none is working. Neither with the normal mount command nor with yours including fsck. I tried different bcachefs-tools version for each kernel and get either an `ERROR - bcachefs::commands::cmd_mount: Fatal error: Invalid argument` or a `ERROR - bcachefs::commands::cmd_mount: Fatal error: No such file or directory` error.

The newest kernel 6.10 does not work either.

Is there anything I can do?

**Comment by dflvunoooooo** [comment]
Is there nothing I can do to rescue my data? :'(

**Comment by koverstreet** [comment]
Sorry, I've just been working through a backlog.

Try 6.11 first; if that doesn't work, join the IRC channel and get me a metadata dump (we'll walk you through it) - irc.oftc.net #bcache

**Comment by dflvunoooooo** [comment]
No problem, thank you for your reply!

I still get `Error: No such file or directory` with 6.11. I will join the IRC channel.

**Comment by koverstreet** [comment]
And, it sounds like we got this fixed.
