### ISSUE TITLE
Out of Memory with background_compression

### ISSUE THREAD

**Issue by BjarneSeger** [koverstreet/bcachefs#723]
I recently moved about 1.5 TB over to a bcachefs partition with encryption enabled and background_cpmression set to zstd:15. It is still compressing but when I run games or even just Steam on the same machine the usually crash after some time telling me they ran out of memory. This did not happen before moving to bcachefs.
I use Kernel 6.10.3 with 64GB of RAM.
This seemed to be related to be related to #384 and the proposed workaround does indeed reduce the amount of memory used temporarily, but that issue was closed as resolved about four months ago.

**Comment by koverstreet** [comment]
Enable memory allocation profiling, and then post the logs of your OOMs

**Comment by BjarneSeger** [comment]
[dmesg.txt](https://gist.github.com/BjarneSeger/c07a1cef945eaf4e62fc0c0e51c286df)
Like this?

**Comment by koverstreet** [comment]
I don't see any memory allocation profiling output in there, did you enable it?

**Comment by BjarneSeger** [comment]
I enabled `CONFIG_MEM_ALLOC_PROFILING` and `CONFIG_MEM_ALLOC_PROFILING_DEBUG` but there is still seemingly no profiling in dmesg and /proc/allocinfo is empty. Anything else I should enable?

**Comment by koverstreet** [comment]
MEM_ALLOC_PROFILING should have been it, you must have tripped over some sort of bug. What kernel version are you on?

**Comment by BjarneSeger** [comment]
This appeared on 6.10.3 and 6.10.4, but seems resolved as of 6.10.5 (at least with my minimal testing). At first I thought it might be related to whatever causes MEM_ALLOC_PROFILING to not work but that does not seem to be the case.
