### ISSUE TITLE
Graphical utility to check the explicit status of fragmentation.

### ISSUE THREAD

**Issue by wooowchik** [koverstreet/bcachefs#724]
People on Windows got programs like this to check and maintain the current level of fragmentation etc :
![distrix](https://github.com/user-attachments/assets/c24cb7ef-ef78-4b2d-af64-fc32c70a9bc5)

So I were and I'm always wondering - Why on linux we never ever had some similar programs to check in a graphical mode the current fragmentation?

**Comment by koverstreet** [comment]
that might exist in gnome or kde land - it's not something for bcachefs to implement, we implement fiemap which is what userspace would need to implement this.
