### ISSUE TITLE
bio_full interface has changed

### ISSUE THREAD

**Issue by vale981** [koverstreet/bcachefs#74]
https://github.com/koverstreet/bcachefs/blob/ce9c3373f2936da244dc80e945e2dc944fd23fec/fs/bcachefs/fs-io.c#L1422

Hi,
In July the interface to `bio_full` has changed to include an extra parameter.
https://github.com/torvalds/linux/commit/79d08f89bb1b5c2c1ff90d9bb95497ab9e8aa7e0#diff-8879dc40eb3fe482b177882ce3c94f04R113

I am sorry if that issue is out of place here, as I am experiencing a build error for an AUR package and will also file a bug there, but I thought it may be good to let you know.

Thanks

**Comment by nicman23** [comment]
b81d050a4ef4b4ef8e1c8f96cb27cbd247c36a29

**Comment by Valmar33** [comment]
Okay, I've added a stopgap `git revert` for https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.2.1&id=c785529bebceeaf38db8ebf9b50ff3a173fb18c6 into the PKGBUILD, and it builds fine. :)

**Comment by nicman23** [comment]
btw if anyone needs 5.4-rc3 (and later) you can use this but it is more for my usage

2773c7f90f4b3d6aa5801c789a0bd1ea9c4848ff
