### ISSUE TITLE
bcachefs does not handle ancient timestamps

### ISSUE THREAD

**Issue by bnoordhuis** [koverstreet/bcachefs#743]
I'm not the discoverer of this bug but it came to me via https://github.com/NixOS/nixpkgs/issues/338114 by way of https://github.com/libuv/libuv/issues/4526:
```
utimensat(AT_FDCWD, "test_file", [{tv_sec=-14245441, tv_nsec=750000000} /* 1969-07-20T03:55:59.750000000+0100 */, {tv_sec=-14245441, tv_nsec=750000000} /* 1969-07-20T03:55:59.750000000+0100 */], 0) = 0
statx(AT_FDCWD, "test_file", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID|STATX_SUBVOL, stx_blksize=512, stx_attributes=0, stx_nlink=1, stx_uid=1000, stx_gid=994, stx_mode=S_IFREG|0600, stx_ino=940489127, stx_size=0, stx_blocks=0, stx_attributes_mask=STATX_ATTR_IMMUTABLE|STATX_ATTR_APPEND|STATX_ATTR_NODUMP|STATX_ATTR_AUTOMOUNT|STATX_ATTR_MOUNT_ROOT|STATX_ATTR_DAX, stx_atime={tv_sec=-14245440, tv_nsec=4044967296}, stx_btime={tv_sec=1725458156, tv_nsec=298521042} /* 2024-09-04T15:55:56.298521042+0200 */, stx_ctime={tv_sec=1725458156, tv_nsec=299521072} /* 2024-09-04T15:55:56.299521072+0200 */, stx_mtime={tv_sec=-14245440, tv_nsec=4044967296}, stx_rdev_major=0, stx_rdev_minor=0, stx_dev_major=259, stx_dev_minor=2, stx_mnt_id=0x2f, stx_subvol=0x6}) = 0
```
Observe how `{tv_sec=-14245441, tv_nsec=750000000}` goes in but `{tv_sec=-14245440, tv_nsec=4044967296}` comes out - that's over 4 billion nanoseconds. Issue looks to be present in mainline.

cc @alyssais

**Comment by colexbruhn** [comment]
Just chiming in to say that I've also encountered this bug. 

Looks like it's primarily affecting folks running on NixOS and causing build failures. There's a PR over there to disable the test in question as a workaround NixOS/nixpkgs#338330 for now.

**Comment by alyssais** [comment]
I have a patch for this.  Will submit it later today.

**Comment by alyssais** [comment]
https://lore.kernel.org/linux-bcachefs/20240907160024.605850-3-hi@alyssa.is/

**Comment by koverstreet** [comment]
Is that patch sufficient, or do we also need support for timestamps outside
the range of 64 bit nanoseconds?

The on disk format supports 96 bit nanoseconds, it just needs to be plumbed.

**Comment by alyssais** [comment]
Yes, I think you're right.  In that case, you might want to replace the Closes trailer with a Link.
