### ISSUE TITLE
Feature request: Make some files always stay in promote device

### ISSUE THREAD

**Issue by fpemud** [koverstreet/bcachefs#758]
I'm currently using btrfs+bcache for my production storage. I've noticed an issue: after heavy I/O activity (like watching some HD movies), the next reboot results in very slow read times because system files seem to be displaced from the SSD by the movie data.

Based on my understanding of how btrfs and bcache work, I don't believe this "pain point" can be solved with the current btrfs+bcache setup.

Would it be possible for bcachefs to allow setting flags or xattr on files to keep them always in cache, or assign higher cache priority, ensuring they remain on SSD?

Thank you for considering this enhancement.

**Comment by koverstreet** [comment]
yes, just set foreground_target and background_target to the ssd
