### ISSUE TITLE
ENOMEM_journal_keys_sort on mount, during journal replay, even with norecovery

### ISSUE THREAD

**Issue by tristandruyen** [koverstreet/bcachefs#769]
When trying to mount my filesystem I get a `Cannot allocate memory` error.
This first occured on mainline@[6efbea77](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6efbea77b390604a7be7364583e19cd2d6a1291b).
I have 128 GB's of ECC RAM, which seems like it should be enough ....

### Existing Troubleshooting

I tried mounting via a rescue-iso with the latest `bcachefs-for-upstream` to fix it, but that did not help.
Adding `-o norecovery` does not help either.

#### Troubleshooting Upgrade

bcachefs-tools 1.12.0+4f9293b (latest git master)
kernel https://github.com/koverstreet/bcachefs/commit/bc6d2d10418e1bfdb95b16f5dd4cca42d5dec766 (latest bcachefs-for-upstream)

#### Initial Occurance

bcachefs-tools 1.11
kernel 6.11-mainline@[6efbea77](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6efbea77b390604a7be7364583e19cd2d6a1291b)

### Crash logs in dmesg
```
Oct 18 13:37:48 rescue-iso kernel: bcachefs (22d3e827-0ac1-4c66-ab88-bcd8b1cfd788): Too many journal keys for slowpath; have 60113363 compacted, buf size 67108864, processed 88450966 keys at seq 125887984
Oct 18 13:37:48 rescue-iso kernel: bcachefs (22d3e827-0ac1-4c66-ab88-bcd8b1cfd788): bch2_fs_recovery(): error ENOMEM_journal_keys_sort
Oct 18 13:37:48 rescue-iso kernel: bcachefs (22d3e827-0ac1-4c66-ab88-bcd8b1cfd788): bch2_fs_start(): error starting filesystem ENOMEM_journal_keys_sort
```

### Bcachefs tools Verbose output
```
nix run github:koverstreet/bcachefs-tools -- mount -v UUID=22d3e827-0ac1-4c66-ab88-bcd8b1cfd788 /mnt
[INFO  src/commands/mount.rs:313] mounting with params: device: /dev/dm-0:/dev/dm-1:/dev/dm-10:/dev/dm-11:/dev/dm-2:/dev/dm-3:/dev/dm-4:/dev/dm-5:/dev/dm-6:/dev/dm-7:/dev/dm-8:/dev/dm-9, target: /mnt, options:
[INFO  src/commands/mount.rs:43] mounting filesystem
mount: /dev/dm-0:/dev/dm-1:/dev/dm-10:/dev/dm-11:/dev/dm-2:/dev/dm-3:/dev/dm-4:/dev/dm-5:/dev/dm-6:/dev/dm-7:/dev/dm-8:/dev/dm-9: Cannot allocate memory
```

### Full Verbose Logs

- Full dmesg & show-super output is in [this gist](https://gist.github.com/tristandruyen/91f8c4601d812e95c32f251e7d397d76)

### Likely unrelated older issues with this filesystem

I had some other issues with the same filesystem, though they seem unrelated to me. For reference:

- https://old.reddit.com/r/bcachefs/comments/1g5t38z/mounting_root_filesystem_hangs_indefinitely/ (resolved by switching to mainline)
- https://old.reddit.com/r/bcachefs/comments/1f36zja/is_there_any_way_to_limitavoid_high_memory_usage/ (unresolved)

**Comment by koverstreet** [comment]
Oof, big filesystem?

There's a 2 GB limit on max allocation size, time to lift that

**Comment by tristandruyen** [comment]
> Oof, big filesystem?

2x1TB U2 NVMe SSDs as promote & foreground
10x16TB SATA HDDs as background
~ 75TB used

**Comment by koverstreet** [comment]
Can you try my bcachefs-for-upstream branch? Get it from github, the website is down at the moment

**Comment by tristandruyen** [comment]
https://github.com/koverstreet/bcachefs/commit/81f8ef6863d2a40bd67b604d46f9a63b6e708818
Seems to fix it, it's now fsck'ing which takes quite some time, but looking good and already further along than before.
