### ISSUE TITLE
BUG() soft lockup when performing find -inum (6.12-rc3)

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#770]
[decoded_stacktrace.txt](https://github.com/user-attachments/files/17435439/decoded_stacktrace.txt)
rsync whole filesystem gave a few damaged inodes, find -inum causes BUG() reports of soft lockups

**Comment by jpsollie** [comment]
*UPDATE*
- after a clean reboot, the issue is still there
- downgrading to my 6.11 kernel (having a 1.12 fs) made the issue disappear

**Comment by jpsollie** [comment]
UPDATE 2:
bisecting it gave f14a630ed881163fdab2040422ae0991bafd28c3 as the faulty commit

**Comment by g2p** [comment]
That commit isn't upstream, is it?

**Comment by jpsollie** [comment]
checkout koverstreet/master ...
then try this:

git log -p f14a630ed881163fdab2040422ae0991bafd28c3

**Comment by koverstreet** [comment]
i don't have that commit

**Comment by koverstreet** [comment]
Did you try my bcachefs-for-upstream branch? I think this is fixed in rc4

**Comment by jpsollie** [comment]
ok, no offence, but that is extremely weird...
How can I see where this commit is in?
```
commit f14a630ed881163fdab2040422ae0991bafd28c3
Author: Kent Overstreet <kent.overstreet@linux.dev>
Date:   Wed Oct 2 21:23:41 2024 -0400

    bcachefs: bch2_inode_or_descendents_is_open()

    fsck can now correctly check if inodes in interior snapshot nodes are
    open/in use.

    - Tweak the vfs inode rhashtable so that the subvolume ID isn't hashed,
      meaning inums in different subvolumes will hash to the same slot. Note
      that this is a hack, and will cause problems if anyone ever has the
      same file in many different snapshots open all at the same time.

    - Then check if any of those subvolumes is a descendent of the snapshot
      ID being checked

    Signed-off-by: Kent Overstreet <kent.overstreet@linux.dev>
```

**Comment by jpsollie** [comment]
It indeed was fixed in rc4.  Case closed
