### ISSUE TITLE
mount -o remount fails with "Invalid value ssd for mount option foreground_target"

### ISSUE THREAD

**Issue by antihutka** [koverstreet/bcachefs#84]
Trying to remount a filesystem fails:
```
root@hammy:~# mount /mnt/storp/ -o remount
mount: /mnt/storp: permission denied.
root@hammy:~# dmesg
[...]
[ 7790.398775] bcachefs: bch2_parse_mount_opts() Invalid value ssd for mount option foreground_target
```

**Comment by koverstreet** [comment]
I can't reproduce this, can you post what commands you used for formatting and initially mounting?

**Comment by antihutka** [comment]
I don't have the exact commands, but it's a pretty standard ssd+hdd setup. I can reproduce it with this:
```
# truncate -s 128m f0
# truncate -s 128m f1
# mkdir m
# bcachefs format --group ssd f0 --group hdd f1 --data_replicas=1 --metadata_replicas=1 --foreground_target=ssd --background_target=hdd --promote_target=ssd
# losetup /dev/loop0 f0
# losetup /dev/loop1 f1
# mount -t bcachefs /dev/loop0:/dev/loop1 m

# mount
[...]
/dev/loop0:/dev/loop1 on /root/bc-temp/m type bcachefs (rw,relatime,foreground_target=ssd,background_target=hdd,promote_target=ssd)
# mount -o remount m
mount: /root/bc-temp/m: permission denied.
# dmesg
[...]
[ 1470.379413] bcachefs: bch2_parse_mount_opts() Invalid value ssd for mount option foreground_target
```

**Comment by RlndVt** [comment]
My system seems to be showing the same issue. But even though the errors are being thrown, nothing seems wrong and the system boots fine. My format command was something along the lines of:

    # bcachefs format --group ssd /dev/sda2 /dev/sdb2 --group hdd /dev/sdc --data_replicas=1 --metadata_replicas=2 --foreground_target=ssd --background_target=hdd --promote_target=ssd

![boot log](https://user-images.githubusercontent.com/1658570/76465660-61a43200-63e6-11ea-90ca-3cab0efb13f3.jpg)
![drive info](https://user-images.githubusercontent.com/1658570/76465666-649f2280-63e6-11ea-8e07-6e6e7e014819.jpg)

**Comment by yshui** [comment]
I have the same issue
