### ISSUE TITLE
show-super fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by minorsecond** [koverstreet/bcachefs#85]
When running `sudo bcachefs show-super /mnt`, I get the following error:

```
io_submit err: Invalid argument
bcachefs: linux/blkdev.c:258: aio_completion_thread: Assertion `!(atomic_read(&running_requests) != 0)' failed.
Aborted
```

Anyone come across this yet?

**Comment by minorsecond** [comment]
Issue was that I was using the wrong device. `sudo bcachefs show-super /dev/sdb` was the correct command.

**Comment by nadalle** [comment]
bcachefs-tools was using the wrong exit sequence on an IO error here, which caused the spurious assertion instead of a correct message.
