### ISSUE TITLE
discard seems not work

### ISSUE THREAD

**Issue by marcin-github** [koverstreet/bcachefs#87]
It looks that discard isn't send to lower layer.
``` 
# cat /sys/fs/bcachefs/cfe24ee6-8fa9-4380-8159-e2e04bbe2fe5/options/discard
1
```
but qcow2 image still occupies a lot of space after deleting huge file (according to what `du` says.

**Comment by koverstreet** [comment]
Discard needs to be reimplemented, it's currently done shortly prior to reusing buckets instead of after they become empty
