### ISSUE TITLE
bcachefs tool looks at physical instead of logical block size

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#89]
https://github.com/koverstreet/bcachefs-tools/blob/abbe66b6a5051027fd63b2a4cd4cb1d4b09410f6/tools-util.c#L254

should be BLKSSZGET instead of BLKPBSZGET

**Comment by antihutka** [comment]
This is the issue I hit in #83. min(physical_size, page_size) would likely be a good default block size, since we probably want to avoid partial block writes on 512e drives, while logical size should be the hard lower limit.

**Comment by nicman23** [comment]
my issue is that only 2 of my 4 devices support 4k and that is a change in the kernel (read regression) - BLKPBSZGET used to report logical.

so if it is indeed better to have 4k min that is also ok but the issue is if there are only devices supporting 512 block sizes (and bcachefs format goes ahead and creates a 512 block size fs)

**Comment by antihutka** [comment]
Any size between logical size and page size should work fine, but using a size smaller than physical size can slow down writes, sometimes significantly.

On native 4k drives, 4k block size has to be used.
On 4k drives emulating 512b blocks, it's probably a good idea to default to 4k.
On native 512b drives it's OK to use 512b blocks, but you might run into issues when adding more devices later - from what I can see, bcachefs can't handle mixed block size devices.
On devices with >4k physical block size, 4k has to be used, as bcachefs doesn't support blocks larger than page_size.

**Comment by nicman23** [comment]
> On native 512b drives it's OK to use 512b blocks

that is my use case (along with drives with logical 512 support)
