### ISSUE TITLE
fsck - Another kernel panic with trans iter

### ISSUE THREAD

**Issue by nicman23** [koverstreet/bcachefs#90]
there is corruption on the fs, some files that exist but cannot be read and cannot be removed.

booting without fsck (but with fix_errors) works

sorry for the picture, the serial port in my motherboard doesn't work for some reason

![IMG_20200127_100547](https://user-images.githubusercontent.com/16306097/73159303-e6651600-40ee-11ea-9c30-256f13da8671.jpg)

bcache fsck -p output:

[error.txt](https://github.com/koverstreet/bcachefs/files/4117303/error.txt)

**Comment by koverstreet** [comment]
Pushed a fix - there might still be other iterator leaks though. Can you try with current master?

**Comment by nicman23** [comment]
yeah give me an hour

**Comment by nicman23** [comment]
it did work - however i got unreachable directories and cannot mount with -o fsck (but can with fix_errors,fsck)

![IMG_20200128_172339](https://user-images.githubusercontent.com/16306097/73280567-65457600-41f7-11ea-8e0b-165d75658b57.jpg)

**Comment by RlndVt** [comment]
I seem to have the same issue, but mounting with `fix_errors,fsck` also causes a kernel panic.

![Kernel Panic](https://user-images.githubusercontent.com/1658570/76129746-807e7f00-6008-11ea-8727-f4ac38ecb869.jpg)

fsck without -p
[output.txt](https://github.com/koverstreet/bcachefs/files/4300911/output.txt)

fsck with -p
[output-p.txt](https://github.com/koverstreet/bcachefs/files/4300910/output-p.txt)

**Comment by RlndVt** [comment]
Attempted [this commit](https://github.com/koverstreet/bcachefs/commit/b9a3fe332f19305859cd269da1ff0f9f25041fbf) as suggested on the IRC, this caused mount to get stuck (100% cpu for a few minutes, forced reboot.) 

Afterwards I rebooted and ran fsck -p; similar output but other c line.

 `bcachefs: libbcachefs/btree_iter.c:1880: btree_trans_iter_alloc: Assertion `0' failed.`

Rebuilding with the new master now. (d051feef0d3838b0ce7341b334b3da9baed116f3)

**Comment by RlndVt** [comment]
Fixed with 7e07e19c29a31d2c719eb16f7e9061ad5aba5099
