### ISSUE TITLE
Unable to mount partition

### ISSUE THREAD

**Issue by eadwu** [koverstreet/bcachefs#92]
It looks like it's getting stuck on the fsck run. Is there any way to recover the partition?

It's looking like I might've fell into d9bb516b2d79fd1ad412e2c8e828182fe6e851c1.

**Comment by eadwu** [comment]
Using a `bcachefs-tools` built using the sources from b47904df3c6249c30213854bdeab003e64a09877, I manage to get past journal replaying in fsck but it hangs during an inode deletion.

**Comment by koverstreet** [comment]
Can you dump the filesystem metadata with bcachefs dump? I'm not having any luck reproducing this one so far

**Comment by koverstreet** [comment]
Scratch that, I figured it out - fix will be up shortly.

**Comment by koverstreet** [comment]
Fixed by 08d4121b91
