### ISSUE TITLE
mount work but fstab not 

### ISSUE THREAD

**Issue by 53845714nF** [koverstreet/bcachefs#96]
Hello Community,
I have some strange behaviour, I edit this to my fstab:

`/dev/sdc:/dev/sdd      /mnt    bcachefs        rw,errors=remount-ro,metadata_replicas=2,data_replicas=2        0       0`

If I reboot my computer, I get in to recovery modus. I think the mount time exceeding the time limit.
But if I boot up and add this line to fstab and mount this in the runnig system it works (and works fast):

```
time mount -a -o remount -vvv
/                        : ignored
none                     : ignored
/media/cdrom0            : ignored
/mnt                     : successfully mounted

real 0m4.933s
user 0m0.000s
sys 0m0.614s
```

I tried this also with this long device numbers of my harddrive but the same behaviour. 

fstab like this:
`/dev/disk/by-id/wwn-0x600221909a08590024b08578233c4a87:/dev/disk/by-id/wwn-0x600221909a08590024b0858323e53d9c  /mnt    bcachefs        rw,errors=remount-ro,metadata_replicas=2,data_replicas=2        0       0
`

Is this a bug, or do I something wrong?

**Comment by rwcarlsen** [comment]
Do you use systemd?  I seem to recall reading somewhere that systemd tries to parse the fstab, but it doesn't understand the colon-syntax for multiple devices and so it gets hung up and never completes the mount process.  So in short - it just won't work.  I had to write my own mount scrip and systemd unit file that I used to mount a bcachefs home directory with multiple devices.

**Comment by 53845714nF** [comment]
Thank you for your answer.
That's a stupid behavior, of the computer. Thanks for the workaround. It's not as clean as putting it on the fstab, but it should work.

**Comment by RlndVt** [comment]
> Do you use systemd? I seem to recall reading somewhere that systemd tries to parse the fstab, but it doesn't understand the colon-syntax for multiple devices and so it gets hung up and never completes the mount process. So in short - it just won't work. I had to write **my own mount script and systemd unit file** that I used to mount a bcachefs home directory with multiple devices.

Could you provide your (or an example) mount script/systemd unit file?

**Comment by 53845714nF** [comment]
Hello I can share my Unit Script, I hope it help you. 

With the command  `systemctl edit –force –full bcachefs-mount.service` can you create a new Unit file. This create a file withe namen: `bcachefs-mount.service` located in the directory: `/etc/systemd/system/`. 

This file can be edit like this:
```
[Unit]
Description=bcachefs mount
DefaultDependencies=no
After=basic.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'mount -t bcachefs /dev/sdc:/dev/sdd /mnt'

[Install]
WantedBy=multi-user.target
```

**Comment by colttt** [comment]
do you know in which systemd-version this shoudl work?

**Comment by 53845714nF** [comment]
I tried with the newest bcachefs on Debian Buster 10. I use systemd 241. I know the latest version is 245. 
@RlndVt What version of systemd are you using? Which operating system did you use for testing?

**Comment by RlndVt** [comment]
On arch with systemd 245.5-2.

I might need to swallow my words, but this is my `fstab` entry:

```
/dev/sda2:/dev/sdb2:/dev/sdc	/         	bcachefs  	rw,relatime,fix_errors,fsck,metadata_replicas=2	0 0
```

Which systemd translates to:

```
$ cat /run/systemd/generator/-.mount 
# Automatically generated by systemd-fstab-generator

[Unit]
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
SourcePath=/etc/fstab
Before=local-fs.target
After=blockdev@dev-sda2:-dev-sdb2:-dev-sdc.target

[Mount]
Where=/
What=/dev/sda2:/dev/sdb2:/dev/sdc
Type=bcachefs
Options=rw,relatime,fix_errors,fsck,metadata_replicas=2
```

The only line that looks suspicious to me is the `After=`. For me my system boots so I think it works. Otherwise creating a [drop-in file](https://wiki.archlinux.org/index.php/Systemd#Drop-in_files) that splits the `After=` line into multiple entries might work.
